var c=void 0,h=!0,j=!1;function l(a){return a instanceof aa?(a.a&&(a.x=a.a(),a.a=0),a.x):a}function m(a){return new aa(a)}function aa(a){this.a=a}function n(a,b){function d(){var d=b.concat(Array.prototype.slice.call(arguments));return n(a,d)}a=a instanceof aa?l(a):a;if(!a.apply)return a;var e=a.arity?a.arity:a.length;if(b.length===e)return a.apply(null,b);if(b.length>e)return e=b.splice(0,e),n(a.apply(null,e),b);d.arity=e-b.length;return d}function r(a){throw t(a)[1];}
function u(a){return v(a,[1])}function v(a,b,d){var e=d?d:0;return e>=a.length?l(b):[2,[1,a.charAt(e)],m(function(){return v(a,b,e+1)})]}function t(a){for(var a=l(a),b="";2==a[0];)a=ba(a),b+=a[0],a=a[1];return[1,b]}function ba(a){var b=l(a[1])[1];if("\\"==b){var d="",a=l(a[2]);if(1==a)return["\\",a];for(b=l(a[1])[1];"0"<=b&&"9">=b;)d+=b,a=l(a[2]),b=l(a[1])[1];if(0==d.length)return["\\",a];b=String.fromCharCode(Number(d));return[b,a]}return[b,l(a[2])]}
function ca(a,b,d){return a.addEventListener?(a.addEventListener(b,d,j),[1,0,h]):a.attachEvent?(a.attachEvent("on"+b,d),[1,0,h]):[1,0,j]}function da(a){return[1,0,65<=a&&90>=a||97<=a&&122>=a||229==a||228==a||246==a||197==a||196==a||214==a]}function ea(a,b,d){a[b]=d;return[1,0]}function w(a){return(a=document.getElementById(a))?[1,0,[2,[1,a]]]:[1,0,[1]]}
var fa=[9,c],ha=[13,c],ia=[1,"load"],ja=[1,"mousemove"],ka=[1,"mouseover"],la=[1,"mouseout"],ma=[1,"click"],na=[1,"dblclick"],oa=[1,"mousedown"],pa=[1,"mouseup"],qa=[1,"keypress"],ra=[1,"keyup"],sa=[1,"keydown"],ta=[1,"unload"],ua=[1,"change"],va=[1,"focus"],wa=[1,"blur"];
function xa(a,b,d){function e(b){l(d);"change"==b&&"text"==a.type.toLowerCase()&&ca(a,"keyup",args);var e;switch(b){case "click":case "dblclick":case "mouseup":case "mousedown":e=function(a){n(d,[[1,a.button],0])};break;case "keypress":case "keyup":case "keydown":e=function(a){n(d,[[1,a.keyCode],0])};break;default:e=function(){n(d,[0])}}var b=ca(a,b,e),f=b[2];return[1,b[1],m(function(){return l(f)?h:j})]}switch(l(b)[0]){case 1:var b=l(ia)[1],f=e(b);break;case 2:b=l(ta)[1];f=e(b);break;case 3:b=l(ua)[1];
f=e(b);break;case 4:b=l(va)[1];f=e(b);break;case 5:b=l(wa)[1];f=e(b);break;case 6:b=l(ja)[1];f=e(b);break;case 7:b=l(ka)[1];f=e(b);break;case 8:b=l(la)[1];f=e(b);break;case 9:b=l(ma)[1];f=e(b);break;case 10:b=l(na)[1];f=e(b);break;case 11:b=l(oa)[1];f=e(b);break;case 12:b=l(pa)[1];f=e(b);break;case 13:b=l(qa)[1];f=e(b);break;case 14:b=l(ra)[1];f=e(b);break;case 15:b=l(sa)[1],f=e(b)}return f}var ya=m(function(){return u("formulaInput")}),za=m(function(){return t(ya)});
function x(a){for(var b=0;;){a=l(a);if(1==a[0])return l(b);b=b+1|0;a=a[2]}}function y(a,b){for(;;){var d=l(b);if(1==d[0])var e=[1];else if(e=d[1],d=d[2],n(a,[e]))e=[2,e,function(a,b){return m(function(){return y(a,b)})}(a,d)];else{b=d;continue}return e}}var Ba=[1];function z(a,b){var d=l(a);if(1==d[0])d=l(b);else var e=d[2],d=[2,d[1],m(function(){return z(e,b)})];return d}var Ca=[1,"-"];
function Da(a,b){for(;;){if(10>a)return[2,[1,String.fromCharCode(48+a|0)],b];var d=[2,[1,String.fromCharCode(48+a%10|0)],b],a=(a-a%10)/10,b=d}}function Ea(a,b){if(0>a)var d=l(a),e=-2147483648==d?[2,Ca,m(function(){return Da(214748364,m(function(){return Da(8,b)}))})]:[2,Ca,m(function(){return Da(-d,b)})];else e=Da(a,b);return e}var A=[1];
function Fa(a,b){var d=v("error at character ",m(function(){var d=l(a)[1],f=m(function(){return v(": ",b)}),d=Ea(d,A);return z(d,f)})),d=t(d)[1];"undefined"!=typeof alert?alert(d):print(d);return[1,0,Ba]}var Ga=m(function(){return u(" could be found!")});function C(a){var b=v("No element with ID ",m(function(){return z(a,Ga)}));return r(b)}
var Ha=m(function(){return u("sdnfCode")}),Ma=m(function(){return C(Ha)}),Na=m(function(){return u("nnfCode")}),Oa=m(function(){return C(Na)}),Pa=m(function(){return u("simplifiedCode")}),Qa=m(function(){return C(Pa)}),Ra=m(function(){return u("innerHTML")}),Sa=m(function(){return t(Ra)}),Ta=m(function(){return t(Pa)}),Ua=m(function(){return t(Ra)}),Va=m(function(){return t(Na)}),Wa=m(function(){return t(Ra)}),Xa=m(function(){return t(Ha)}),Ya=m(function(){return t(Ra)}),Za=m(function(){return u("dnfCode")}),
$a=m(function(){return t(Za)}),ab=m(function(){return t(Ra)}),bb=m(function(){return u("scnfCode")}),cb=m(function(){return t(bb)}),db=m(function(){return t(Ra)}),eb=m(function(){return u("cnfCode")}),fb=m(function(){return t(eb)}),gb=m(function(){return u("eof")}),hb=m(function(){return v("tokenizer: ",gb)}),ib=m(function(){return C(eb)}),jb=m(function(){return C(bb)}),kb=m(function(){return C(Za)});function lb(a){return 5==l(a)[0]?h:j}function mb(a){return 6==l(a)[0]?h:j}
var nb=[1,")"],ob=[2,nb,A],yb=[1,"("],E=[2],zb=m(function(){return F(E)}),H=[1],Ab=m(function(){return F(H)}),Bb=[2,nb,A];function Cb(){return j}var Db=[2,[1,"0"],A],Eb=[2,[1,"1"],A],Fb=[2,nb,A],Gb=[1,"!"];function Hb(a,b){var d=l(b);switch(d[0]){case 1:var e=l(Ab);break;case 2:e=l(zb);break;case 3:e=F(d);break;case 4:e=F(d);break;default:e=n(a,[d])?F(d):[2,yb,m(function(){var a=F(d);return z(a,Fb)})]}return e}
function F(a){a=l(a);switch(a[0]){case 1:var b=l(Eb);break;case 2:b=l(Db);break;case 3:b=l(a[1]);break;case 4:var d=a[1],b=[2,Gb,m(function(){return Hb(Cb,d)})];break;case 5:var e=a[2],b=m(function(){return v(" ^ ",m(function(){return Hb(lb,e)}))}),f=l(a[1]);switch(f[0]){case 1:b=z(Ab,b);break;case 2:b=z(zb,b);break;case 3:a=F(f);b=z(a,b);break;case 4:a=F(f);b=z(a,b);break;case 5:a=F(f);b=z(a,b);break;default:b=z([2,yb,m(function(){var a=F(f);return z(a,Fb)})],b)}break;case 6:var g=a[2],b=m(function(){return v(" v ",
m(function(){return Hb(mb,g)}))}),i=l(a[1]);switch(i[0]){case 1:b=z(Ab,b);break;case 2:b=z(zb,b);break;case 3:a=F(i);b=z(a,b);break;case 4:a=F(i);b=z(a,b);break;case 6:a=F(i);b=z(a,b);break;default:b=z([2,yb,m(function(){var a=F(i);return z(a,Fb)})],b)}break;case 7:var o=a[1],s=a[2],b=[2,yb,m(function(){var a=m(function(){return v(") -> (",m(function(){var a=F(s);return z(a,Bb)}))}),b=F(o);return z(b,a)})];break;case 8:var q=a[1],B=a[2],b=[2,yb,m(function(){var a=m(function(){return v(") <-> (",m(function(){var a=
F(B);return z(a,ob)}))}),b=F(q);return z(b,a)})]}return b}
function Ib(a){var b=Jb,a=l(a);switch(a[0]){case 1:var d=[1];break;case 2:d=[2];break;case 3:d=[3,a[1]];break;case 4:var e=a[1],d=[4,m(function(){return n(b,[e])})];break;case 5:var f=a[1],g=a[2],d=[5,m(function(){return n(b,[f])}),m(function(){return n(b,[g])})];break;case 6:var i=a[1],o=a[2],d=[6,m(function(){return n(b,[i])}),m(function(){return n(b,[o])})];break;case 7:var s=a[1],q=a[2],d=[7,m(function(){return n(b,[s])}),m(function(){return n(b,[q])})];break;case 8:var B=a[1],D=a[2],d=[8,m(function(){return n(b,
[B])}),m(function(){return n(b,[D])})]}return d}function Jb(a){return Ib(a)}function I(a){a=l(a);switch(a[0]){case 5:var b=a[1],d=a[2],a=[6,m(function(){return I(b)}),m(function(){return I(d)})];break;case 6:var e=a[1],f=a[2],a=[5,m(function(){return I(e)}),m(function(){return I(f)})];break;default:a=[4,a]}return a}
function Kb(a){a=l(a);if(4==a[0]){var b=l(a[1]);switch(b[0]){case 5:var d=b[1],e=b[2],a=[6,m(function(){return I(d)}),m(function(){return I(e)})];break;case 6:var f=b[1],g=b[2],a=[5,m(function(){return I(f)}),m(function(){return I(g)})];break;default:a=l(a)}}else a=l(a);return a}
function J(a,b){return n(a,[m(function(){var d=l(b);switch(d[0]){case 1:var e=[1];break;case 2:e=[2];break;case 3:e=l(d);break;case 4:var f=d[1],e=[4,m(function(){return J(a,f)})];break;case 5:var g=d[1],i=d[2],e=[5,m(function(){return J(a,g)}),m(function(){return J(a,i)})];break;case 6:var o=d[1],s=d[2],e=[6,m(function(){return J(a,o)}),m(function(){return J(a,s)})];break;case 7:var q=d[1],B=d[2],e=[7,m(function(){return J(a,q)}),m(function(){return J(a,B)})];break;case 8:var D=d[1],p=d[2],e=[8,
m(function(){return J(a,D)}),m(function(){return J(a,p)})]}return e})])}function Lb(a){a=l(a);if(4==a[0])var b=l(a[1]),a=4==b[0]?l(b[1]):l(a);else a=l(a);return a}function K(a,b){var d=l(a);if(5==d[0])var e=d[1],f=d[2],g=[5,m(function(){return K(b,e)}),m(function(){return K(b,f)})];else if(g=l(b),5==g[0])var i=g[1],o=g[2],g=[5,m(function(){return K(d,i)}),m(function(){return K(d,o)})];else g=[6,d,g];return g}
function Mb(a){a=l(a);if(6==a[0]){var b=a[2],d=l(a[1]);if(5==d[0])var e=d[1],f=d[2],a=[5,m(function(){return K(b,e)}),m(function(){return K(b,f)})];else{var g=l(b);if(5==g[0])var i=g[1],o=g[2],a=[5,m(function(){return K(d,i)}),m(function(){return K(d,o)})];else a=l(a)}}else a=l(a);return a}
function L(a,b){var d=l(a);if(6==d[0])var e=d[1],f=d[2],g=[6,m(function(){return L(b,e)}),m(function(){return L(b,f)})];else if(g=l(b),6==g[0])var i=g[1],o=g[2],g=[6,m(function(){return L(d,i)}),m(function(){return L(d,o)})];else g=[5,d,g];return g}
function Nb(a){a=l(a);if(5==a[0]){var b=a[2],d=l(a[1]);if(6==d[0])var e=d[1],f=d[2],a=[6,m(function(){return L(b,e)}),m(function(){return L(b,f)})];else{var g=l(b);if(6==g[0])var i=g[1],o=g[2],a=[6,m(function(){return L(d,i)}),m(function(){return L(d,o)})];else a=l(a)}}else a=l(a);return a}function Ob(a){var b=l(a);switch(b[0]){case 7:a=[6,[4,b[1]],b[2]];break;case 8:a=b[1];b=b[2];a=[5,[6,[4,a],b],[6,[4,b],a]];break;default:a=l(b)}return a}function Pb(a){a=l(a)[1];return l(a)}
function M(a,b){var d=l(b);if(1==d[0])d=[1];else var e=d[1],f=d[2],d=[2,m(function(){return n(a,[e])}),m(function(){return M(a,f)})];return d}function Sb(a,b){var d=l(a);if(1==d[0])var e=[1];else{var e=d[1],f=d[2],d=l(b);if(1==d[0])e=[1];else var g=d[2],e=[2,[1,e,d[1]],m(function(){return Sb(f,g)})]}return e}function Tb(a,b,d){d=l(d);if(1==d[0])d=[1];else var e=d[1],f=d[2],d=n(a,[b,e])?l(f):[2,e,m(function(){return Tb(a,b,f)})];return d}function N(a){a=l(a)[1];return l(a)}
function Ub(a,b,d){return Tb(m(function(){return N(a)}),b,d)}function Vb(a,b,d){a:{for(;;){d=l(d);if(1==d[0]){a=l(b);break a}var e=d[2],b=Ub(a,d[1],b),d=e}a=c}return a}var Wb=m(function(){return u("List.maximumBy: empty list")}),Xb=m(function(){return r(Wb)});function O(a,b,d){for(;;){d=l(d);if(1==d[0])a=j;else{var e=d[2];if(n(N,[a,b,d[1]]))a=h;else{d=e;continue}}return a}}
function P(a,b){function d(b,f){for(var g;;){var i=l(b);if(1==i[0])g=[1];else if(g=i[1],i=i[2],O(a,g,f)){b=i;continue}else g=[2,g,function(a,b,d,e){return m(function(){return e(d,[2,a,b])})}(g,f,i,d)];return g}}return d(b,A)}function Yb(a){a=l(a)[2];return l(a)}function Zb(a,b){var d=l(a)[1],e=l(b)[1];return d==e}var $b=[1,Zb,function(a,b){var d=l(a)[1],e=l(b)[1];return d!=e}];
function ac(a,b){return[1,function(d,e){var f=l(a)[1],g=l(d),i=g[1],g=g[2],o=l(e);return n(f,[i,o[1]])?n(N,[b,g,o[2]]):j},function(d,e){var f=l(a)[1],g=l(d),i=g[1],g=g[2],o=l(e);return n(f,[i,o[1]])?n(N,[b,g,o[2]])?j:h:h}]}function bc(a,b,d){for(;;){var e=l(b);if(1==e[0])a=1==l(d)[0]?h:j;else{var b=e[1],e=e[2],f=l(d);if(1==f[0])a=j;else if(d=f[2],n(N,[a,b,f[1]])){b=e;continue}else a=j}return a}}function cc(a,b,d){return bc(a,b,d)?j:h}
function dc(a){return[1,function(b,d){return bc(a,b,d)},function(b,d){return cc(a,b,d)}]}
var ec=m(function(){return dc($b)}),fc=[1,function(a,b){switch(l(a)[0]){case 1:switch(l(b)[0]){case 1:var d=h;break;case 2:d=j;break;case 3:d=j}var e=d;break;case 2:e=2==l(b)[0]?h:j;break;case 3:e=3==l(b)[0]?h:j}return e},function(a,b){switch(l(a)[0]){case 1:switch(l(b)[0]){case 1:var d=j;break;case 2:d=h;break;case 3:d=h}var e=d;break;case 2:e=2==l(b)[0]?j:h;break;case 3:e=3==l(b)[0]?j:h}return e}],gc=m(function(){return dc(fc)}),Q=m(function(){return ac(gc,ec)});
function hc(a){var b=m(function(){return[1,x(a)]});return n(y,[function(d){var e;a:{e=function(a){return O(Q,a,d)};for(var f=a;;){f=l(f);if(1==f[0])e=h;else{var g=f[2];if(n(e,[f[1]])){f=g;continue}else e=j}break a}e=c}e?(e=l(b)[1],f=x(d),e=e<f?j:h):e=h;return e}])}function ic(a){return P(Q,a)}var jc=m(function(){return dc(Q)});function kc(a){function b(a){a=l(a);if(1==a[0])a=l(d);else var f=a[2],a=n(hc,[a[1],m(function(){return b(f)})]);return a}var a=M(ic,a),d=P(jc,a);return b(d)}
function lc(a,b){function d(b,f){for(;;){var g=l(f);if(1==g[0])g=[1];else{var i=g[2];if(n(a,[g[1]]))g=[2,[1,b],function(a,b,d){return m(function(){return b(a+1|0,d)})}(b,d,i)];else{b=b+1|0;f=i;continue}}return g}}return d(0,b)}var mc=m(function(){return u("Prelude.(!!): negative index\n")}),nc=m(function(){return r(mc)}),oc=m(function(){return u("Prelude.(!!): index too large\n")}),pc=m(function(){return r(oc)}),qc=m(function(){return u(": empty list")}),rc=m(function(){return u("Prelude.")});
function sc(a){var b=z(rc,m(function(){return z(a,qc)}));return r(b)}var tc=m(function(){return u("head")}),uc=m(function(){return sc(tc)});function wc(a){a=l(a);if(1==a[0])a=[1];else var b=a[2],a=z(a[1],m(function(){return wc(b)}));return a}function yc(a){a=l(a);if(1==a[0])a=[1];else var b=a[2],a=l(a[1])[2],a=z(a,m(function(){return yc(b)}));return a}function zc(a){for(var b=0;;){var d=l(a);if(1==d[0])return l(b);a=d[2];d=l(d[1])[1];b=b+d|0}}function ld(a){return 3==l(a)[0]?h:j}
function md(a){a=l(a)[1];a=lc(ld,a);return[1,x(a)]}function nd(a,b){for(;;){var d=l(b);if(1==d[0])return l(a);var e=d[1],d=d[2],f=M(md,a),f=zc(f),g=M(md,e),g=zc(g);f<g?a=e:f==g&&(a=e);b=d}}
function od(a,b,d){return z(b,m(function(){function e(b,d){for(var f;;){var g=l(b);if(1==g[0])f=[1];else{f=g[1];var g=g[2],i;a:{i=a;for(var p=f,k=d;;){k=l(k);if(1==k[0])i=j;else{var G=k[2];if(n(i,[p,k[1]]))i=h;else{k=G;continue}}break a}i=c}if(i){b=g;continue}else f=[2,f,function(a,b,d,e){return m(function(){return e(d,[2,a,b])})}(f,d,g,e)]}return f}}var f;a:{f=e(d,A);for(var g=b;;){g=l(g);if(1==g[0]){f=l(f);break a}var i=g[2];f=Tb(a,g[1],f);g=i}f=c}return f}))}
function pd(a,b,d,e){var f=l(d);if(1==f[0])e=l(b);else{var d=f[1],g=f[2],e=l(e);if(1==e[0])e=l(b);else var i=e[2],e=n(a,[d,e[1],m(function(){return pd(a,b,g,i)})])}return e}function qd(a){a=l(a)[2];return l(a)}function rd(a,b){for(var d;;){d=l(b);if(1==d[0])d=h;else{var e=d[2];if(n(qd,[Q,a,d[1]])){b=e;continue}else d=j}return d}}
function sd(a,b,d){b=l(b);if(1==b[0])d=[1];else{var e=b[1],f=b[2],d=l(d);if(1==d[0])d=[1];else var g=d[1],i=d[2],d=[2,m(function(){return n(a,[e,g])}),m(function(){return sd(a,f,i)})]}return d}function td(a,b){switch(l(a)[0]){case 1:switch(l(b)[0]){case 1:var d=[1];break;case 2:d=[3];break;case 3:d=[3]}var e=d;break;case 2:e=2==l(b)[0]?[2]:[3];break;case 3:l(b),e=[3]}return e}
function ud(a,b,d){switch(l(a)[0]){case 1:switch(l(b)[0]){case 1:var e=l(d);break;case 2:e=[2,j,d];break;case 3:e=[2,j,d]}var f=e;break;case 2:f=2==l(b)[0]?l(d):[2,j,d];break;case 3:f=3==l(b)[0]?l(d):[2,j,d]}return f}
function vd(a,b,d,e){b=l(b);if(1==b[0]){var f=l(e);if(1==f[0])e=z(a,d),e=P(Q,e);else var g=m(function(){return z(a,d)}),i=f[2],o=l(f[1]),s=o[1],q=o[2],B=m(function(){var a=m(function(){return lc(ld,s)});return y(function(b){var b=l(b)[1],d=lc(ld,b);bc($b,a,d)?(b=pd(ud,A,s,b),b=1==x(b)?h:j):b=j;return b},i)}),e=z(A,m(function(){return M(function(a){var a=l(a),b=a[1],d=a[2];return[1,m(function(){return sd(td,s,b)}),m(function(){return od(Zb,q,d)})]},B)})),e=vd(m(function(){return 1==l(B)[0]?O(Q,o,f)?
[2,o,g]:l(g):l(g)}),i,m(function(){var a=l(B);if(1==a[0])a=l(f);else var b=[2,o,a],a=y(function(a){return rd(a,b)},f);return a}),e)}else var D=b[2],p=l(b[1]),k=p[1],G=p[2],ga=m(function(){var a=m(function(){return lc(ld,k)});return y(function(b){var b=l(b)[1],d=lc(ld,b);bc($b,a,d)?(b=pd(ud,A,k,b),b=1==x(b)?h:j):b=j;return b},D)}),e=z(e,m(function(){return M(function(a){var a=l(a),b=a[1],d=a[2];return[1,m(function(){return sd(td,k,b)}),m(function(){return od(Zb,G,d)})]},ga)})),e=vd(m(function(){return 1==
l(ga)[0]?O(Q,p,d)?[2,p,a]:l(a):l(a)}),D,m(function(){var a=l(ga);if(1==a[0])a=l(d);else var b=[2,p,a],a=y(function(a){return rd(a,b)},d);return a}),e);return e}function wd(a){return[2,[2,[1,a],A],m(function(){var b=l(a);return 2147483647==b?[1]:wd(b+1|0)})]}var xd=m(function(){return wd(0)});function R(a,b,d){d=l(d);if(1==d[0])b=l(b);else var e=d[1],f=d[2],b=n(a,[b,m(function(){return R(a,e,f)})]);return b}var yd=m(function(){return u("foldr1")}),zd=m(function(){return sc(yd)});
function Ad(a,b){return[6,a,b]}
function S(a,b,d){d=l(d);switch(d[0]){case 1:var e=n(a,[H,b]);break;case 2:e=n(a,[E,b]);break;case 3:e=n(a,[d,b]);break;case 4:var f=d[1],e=n(a,[d,m(function(){return S(a,b,f)})]);break;case 5:var g=d[1],i=d[2],e=n(a,[d,m(function(){return S(a,m(function(){return S(a,b,i)}),g)})]);break;case 6:var o=d[1],s=d[2],e=n(a,[d,m(function(){return S(a,m(function(){return S(a,b,s)}),o)})]);break;case 7:var q=d[1],B=d[2],e=n(a,[d,m(function(){return S(a,m(function(){return S(a,b,B)}),q)})]);break;case 8:var D=
d[1],p=d[2],e=n(a,[d,m(function(){return S(a,m(function(){return S(a,b,p)}),D)})])}return e}function Bd(a,b){return[5,a,b]}function Cd(a){var b=l(a);if(1==b[0])a=l(zd);else if(a=b[1],b=l(b[2]),1==b[0])a=l(a);else var d=b[1],e=b[2],a=[5,a,m(function(){return R(Bd,d,e)})];return a}function Dd(a,b,d){switch(l(b)[0]){case 1:var e=[2,[3,a],d];break;case 2:e=[2,[4,[3,a]],d];break;case 3:e=l(d)}return e}
function Ed(a,b,d){d=l(d);if(1==d[0])d=[2,b,A];else var e=d[1],f=d[2],d=3==n(a,[b,e])[0]?[2,e,m(function(){return Ed(a,b,f)})]:[2,b,d];return d}function Fd(a,b){for(var d;;){d=l(a);if(1==d[0])d=1==l(b)[0]?h:j;else{var e=d[1];d=d[2];var f=l(b);if(1==f[0])d=j;else{var g=f[1],f=f[2],e=l(e)[1],g=l(g)[1];if(e==g){a=d;b=f;continue}else d=j}}return d}}
var Gd=[1,function(a,b){var d=l(a);if(1==d[0])d=1==l(b)[0]?h:j;else{var e=d[1],d=d[2],f=l(b);if(1==f[0])d=j;else var g=f[1],f=f[2],e=l(e)[1],g=l(g)[1],d=e==g?Fd(d,f):j}return d},function(a,b){return Fd(a,b)?j:h}];function T(a,b){for(var d;;){d=l(a);if(1==d[0])d=1==l(b)[0]?[2]:[1];else{var e=d[1];d=d[2];var f=l(b);if(1==f[0])d=[3];else{var g=f[1],f=f[2],e=l(e)[1],g=l(g)[1];if(e==g){a=d;b=f;continue}else d=e<=g?[1]:[3]}}return d}}
function Hd(a,b){var d=l(a);3==d[0]?(d=d[1],d=O(Gd,d,b)?l(b):Ed(T,d,b)):d=l(b);return d}function Id(a){a=l(a)[2];return l(a)?[1]:[2]}function Jd(a){for(;;){var b=l(a);if(1==b[0])a=[1];else{var a=b[2],b=l(b[1]),d=b[1];if(l(b[2]))a=[2,function(a){return m(function(){return M(Id,a)})}(d),function(a){return m(function(){return Jd(a)})}(a)];else continue}return a}}function Kd(a){a=l(a)[1];return l(a)}function Ld(a){a=l(a)[2];return l(a)}var Md=m(function(){return u("Prelude.undefined")}),Nd=m(function(){return r(Md)});
function Od(a,b){var d=l(a);if(d){var e=l(b);if(1==e[0])e=[1];else var f=e[2],e=[2,e[1],m(function(){return Od(d-1|0,f)})]}else e=[1];return e}var Pd=[2,A,A];function Qd(a){a=l(a);if(1==a[0])a=[1];else var b=a[2],a=[2,[2,a[1],A],m(function(){return Qd(b)})];return a}
function Rd(a,b){var d=m(function(){var d=l(b);if(1==d[0])d=Qd(a);else var f=d[1],g=d[2],i=m(function(){return Rd(f,g)}),o=function(a){a=l(a);if(1==a[0])a=[1];else var b=a[1],d=a[2],e=m(function(){return o(d)}),f=function(a){a=l(a);if(1==a[0])a=l(e);else var d=a[2],a=[2,[2,b,a[1]],m(function(){return f(d)})];return a},a=f(i);return a},d=o(a);return d});return 1==l(a)[0]?1==l(b)[0]?l(Pd):l(d):l(d)}
function Sd(a){a=l(a);if(1==a[0])a=[1];else var b=a[1],d=a[2],a=m(function(){var a=l(d);if(1==a[0])a=Qd(b);else var f=a[1],g=a[2],i=m(function(){return Rd(f,g)}),o=function(a){a=l(a);if(1==a[0])a=[1];else var b=a[1],d=a[2],e=m(function(){return o(d)}),f=function(a){a=l(a);if(1==a[0])a=l(e);else var d=a[2],a=[2,[2,b,a[1]],m(function(){return f(d)})];return a},a=f(i);return a},a=o(b);return a}),a=1==l(b)[0]?1==l(d)[0]?l(Pd):l(a):l(a);return a}
var Td=m(function(){return u("Maybe.fromJust: Nothing")}),Ud=m(function(){return r(Td)}),Vd=m(function(){return u("Logic.eval.reduce: Impossible")}),Wd=m(function(){return r(Vd)}),Xd=[1,1.605959309876327E19,1.3945565038419476E19,[1,1.605959309876327E19,1.3945565038419476E19,m(function(){return u("base")}),m(function(){return u("Control.Exception.Base")}),m(function(){return u("PatternMatchFail")})],A];function Yd(){return l(Xd)}
function Zd(a){var a=l(a),b=a[2],a=l(a[1])[1],d=l(a),e=m(function(){var a=n(d,[b]),g=a[1],a=a[2],i=n(Yd,[m(function(){var a=l(e);return 1==a[0]?l(Ud):l(a[1])})]),o=i[2];return l(g==i[1])?l(a==o)?[2,b]:[1]:[1]});return l(e)}
var $d=[1,","],ae=[1,"]"],be=[1,"["],ce=[1,function(a,b,d){a=l(b)[1];return z(a,d)},function(a){a=l(a)[1];return l(a)},function(a,b){var d=l(a);if(1==d[0])d=v("[]",b);else var e=d[1],f=d[2],d=[2,be,m(function(){var a=l(e)[1];return z(a,m(function(){function a(b){b=l(b);if(1==b[0])b=l(d);else var e=b[1],f=b[2],b=[2,$d,m(function(){var b=l(e)[1];return z(b,m(function(){return a(f)}))})];return b}var d=[2,ae,b];return a(f)}))})];return d}],ee=m(function(){return[1,Yd,ce,de,Zd]});
function de(a){return[1,ee,a]}var fe=m(function(){return u("Non-exhaustive patterns in")}),ge=[1," "],he=[2,[1,"\n"],A];function ie(a){a=l(a)[1];return"|"==l(a)?j:h}function je(a,b){var d=l(b);if(1==d[0])d=[1,A,A];else{var e=d[1],f=d[2];if(n(a,[e]))var g=m(function(){var b=je(a,f);return[1,b[1],b[2]]}),d=[1,[2,e,m(function(){var a=l(g)[1];return l(a)})],m(function(){var a=l(g)[2];return l(a)})];else d=[1,A,d]}return d}
var ke=m(function(){var a=[1,m(function(){function a(b,d){return z(b,m(function(){return v(": ",m(function(){return z(fe,m(function(){return z(d,he)}))}))}))}var b=u("PropositionalLogic/Logic.hs:(150,11)-(151,26)|function toBool"),f=je(ie,b),b=f[1],g=l(f[2]);1==g[0]?b=a(b,A):(f=g[2],g=l(g[1])[1],b="|"==l(g)?a(b,[2,ge,f]):a(b,A));return b})],b=de;throw m(function(){return n(b,[a])});});
function le(a,b){switch(J(function(b){b=l(b);switch(b[0]){case 1:var d=[1];break;case 2:d=[2];break;case 3:a:{b=b[1];for(d=a;;){var g=l(d);if(1==g[0])b=[1];else{var d=g[2],g=l(g[1]),i=g[2];if(n(N,[Gd,b,g[1]]))b=[2,i];else continue}break a}b=c}d=1==b[0]?l(Ud):l(b[1])?[1]:[2];break;case 4:switch(l(b[1])[0]){case 1:b=[2];break;case 2:b=[1];break;default:b=l(Wd)}d=b;break;case 5:d=b[2];switch(l(b[1])[0]){case 1:switch(l(d)[0]){case 1:b=[1];break;case 2:b=[2];break;default:b=l(ke)}break;case 2:b=[2];break;
default:b=l(ke)}d=b;break;case 6:d=b[2];switch(l(b[1])[0]){case 1:b=[1];break;case 2:switch(l(d)[0]){case 1:b=[1];break;case 2:b=[2];break;default:b=l(ke)}break;default:b=l(ke)}d=b;break;case 7:d=le(a,[6,[4,b[1]],b[2]])?[1]:[2];break;case 8:d=b[1],b=b[2],d=le(a,[5,[6,[4,d],b],[6,[4,b],d]])?[1]:[2]}return d},b)[0]){case 1:var d=h;break;case 2:d=j;break;default:d=l(ke)}return d}var me=m(function(){return Sd(A)});function ne(a,b){var d=l(a)[1],e=l(b)[1];return Fd(d,e)}
function oe(a,b,d){return od(ne,[2,[1,a,b],A],d)}function pe(a){a=l(a)[3];return l(a)}function qe(a){a=l(a)[6];return l(a)}function re(a){a=l(a)[5];return l(a)}function se(a){a=l(a)[4];return l(a)}
function te(){var a=ue,b=ve;return[1,m(function(){return ac(m(function(){return Kd(a)}),m(function(){return Kd(b)}))}),function(d,e){var f=l(a)[2],g=l(d),i=g[1],g=g[2],o=l(e),s=o[2];switch(n(f,[i,o[1]])[0]){case 1:var q=[1];break;case 2:q=n(Ld,[b,g,s]);break;case 3:q=[3]}return q},function(d,e){var f=l(a)[2],g=l(d),i=g[1],g=g[2],o=l(e),s=o[2];switch(n(f,[i,o[1]])[0]){case 1:var q=h;break;case 2:q=n(pe,[b,g,s]);break;case 3:q=j}return q},function(d,e){var f=l(a)[2],g=l(d),i=g[1],g=g[2],o=l(e),s=o[2];
switch(n(f,[i,o[1]])[0]){case 1:var q=j;break;case 2:q=n(se,[b,g,s]);break;case 3:q=h}return q},function(d,e){var f=l(a)[2],g=l(d),i=g[1],g=g[2],o=l(e),s=o[2];switch(n(f,[i,o[1]])[0]){case 1:var q=j;break;case 2:q=n(re,[b,g,s]);break;case 3:q=h}return q},function(d,e){var f=l(a)[2],g=l(d),i=g[1],g=g[2],o=l(e),s=o[2];switch(n(f,[i,o[1]])[0]){case 1:var q=h;break;case 2:q=n(qe,[b,g,s]);break;case 3:q=j}return q},function(d,e){var f=l(a)[2],g=l(d),i=g[1],g=g[2],o=l(e),s=o[1],o=o[2];switch(n(f,[i,s])[0]){case 1:var q=
[1,s,o];break;case 2:q=n(qe,[b,g,o])?[1,s,o]:[1,i,g];break;case 3:q=[1,i,g]}return q},function(d,e){var f=l(a)[2],g=l(d),i=g[1],g=g[2],o=l(e),s=o[1],o=o[2];switch(n(f,[i,s])[0]){case 1:var q=[1,i,g];break;case 2:q=n(qe,[b,g,o])?[1,i,g]:[1,s,o];break;case 3:q=[1,s,o]}return q}]}function we(a,b,d){for(;;){var e=l(b);if(1==e[0])a=1==l(d)[0]?[2]:[1];else{var b=e[1],e=e[2],f=l(d);if(1==f[0])a=[3];else if(d=f[2],b=n(Ld,[a,b,f[1]]),2==b[0]){b=e;continue}else a=l(b)}return a}}
var ve=[1,[1,function(a,b){return l(a)?l(b):l(b)?j:h},function(a,b){return l(a)?l(b)?j:h:l(b)}],function(a,b){return l(a)?l(b)?[2]:[3]:l(b)?[1]:[2]},function(a,b){if(l(a)){l(b);var d=j}else d=l(b);return d},function(a,b){if(l(a)){l(b);var d=h}else d=l(b)?j:h;return d},function(a,b){if(l(a))var d=l(b)?j:h;else l(b),d=j;return d},function(a,b){if(l(a))var d=l(b);else l(b),d=h;return d},function(a,b){if(l(a)){l(b);var d=h}else d=l(b);return d},function(a,b){if(l(a))var d=l(b);else l(b),d=j;return d}],
ue=[1,Gd,T,function(a,b){return 1==T(a,b)[0]?h:j},function(a,b){return 1==T(a,b)[0]?j:h},function(a,b){return 3==T(a,b)[0]?h:j},function(a,b){return 3==T(a,b)[0]?j:h},function(a,b){return 3==T(a,b)[0]?l(a):l(b)},function(a,b){return 3==T(a,b)[0]?l(b):l(a)}],xe=m(function(){return[1,m(function(){var a=m(function(){return Kd(ue)}),b=m(function(){return Kd(ve)});return[1,m(function(){return n(bc,[m(function(){return ac(a,b)})])}),m(function(){return n(cc,[m(function(){return ac(a,b)})])})]}),m(function(){var a=
m(function(){return te()});return l(function(b,d){return we(a,b,d)})}),function(a,b){return 1==we(m(function(){return te()}),a,b)[0]?h:j},function(a,b){return 1==we(m(function(){return te()}),a,b)[0]?j:h},function(a,b){return 3==we(m(function(){return te()}),a,b)[0]?h:j},function(a,b){return 3==we(m(function(){return te()}),a,b)[0]?j:h},function(a,b){return 3==we(m(function(){return te()}),a,b)[0]?l(a):l(b)},function(a,b){return 3==we(m(function(){return te()}),a,b)[0]?l(b):l(a)}]}),ye=[2,h,[2,j,
A]],ze=m(function(){return[2,ye,ze]});function Ae(a,b){for(;;){var d=l(b);if(1==d[0])d=j;else{var e=d[2];if(n(a,[d[1]]))d=h;else{b=e;continue}}return d}}function Be(a){for(var b=A;;){a=l(a);if(1==a[0])return l(b);b=[2,a[1],b];a=a[2]}}
function U(a,b){for(var d;;){d=function(a,b){return m(function(){switch(l(a)[0]){case 1:switch(l(b)[0]){case 1:var d=h;break;case 2:d=j;break;case 3:d=j;break;case 4:d=j;break;case 5:d=j;break;case 6:d=j;break;case 7:d=j;break;case 8:d=j}var e=d;break;case 2:switch(l(b)[0]){case 1:var f=j;break;case 2:f=h;break;case 3:f=j;break;case 4:f=j;break;case 5:f=j;break;case 6:f=j;break;case 7:f=j;break;case 8:f=j}e=f;break;case 3:switch(l(b)[0]){case 3:d=h;break;case 4:d=j;break;case 5:d=j;break;case 6:d=
j;break;case 7:d=j;break;case 8:d=j;break;default:d=j}e=d;break;case 4:switch(l(b)[0]){case 3:d=j;break;case 4:d=h;break;case 5:d=j;break;case 6:d=j;break;case 7:d=j;break;case 8:d=j;break;default:d=j}e=d;break;case 5:switch(l(b)[0]){case 3:d=j;break;case 4:d=j;break;case 5:d=h;break;case 6:d=j;break;case 7:d=j;break;case 8:d=j;break;default:d=j}e=d;break;case 6:switch(l(b)[0]){case 3:d=j;break;case 4:d=j;break;case 5:d=j;break;case 6:d=h;break;case 7:d=j;break;case 8:d=j;break;default:d=j}e=d;break;
case 7:switch(l(b)[0]){case 3:d=j;break;case 4:d=j;break;case 5:d=j;break;case 6:d=j;break;case 7:d=h;break;case 8:d=j;break;default:d=j}e=d;break;case 8:switch(l(b)[0]){case 3:d=j;break;case 4:d=j;break;case 5:d=j;break;case 6:d=j;break;case 7:d=j;break;case 8:d=h;break;default:d=j}e=d}return e})}(a,b);var e=l(a);switch(e[0]){case 3:var e=e[1],f=l(b);d=3==f[0]?Fd(e,f[1]):l(d);break;case 4:e=e[1];f=l(b);if(4==f[0]){d=f[1];a=e;b=d;continue}else d=l(d);break;case 5:var f=e[1],e=e[2],g=l(b);if(5==g[0])if(d=
g[2],U(f,g[1])){a=e;b=d;continue}else d=j;else d=l(d);break;case 6:f=e[1];e=e[2];g=l(b);if(6==g[0])if(d=g[2],U(f,g[1])){a=e;b=d;continue}else d=j;else d=l(d);break;case 7:f=e[1];e=e[2];g=l(b);if(7==g[0])if(d=g[2],U(f,g[1])){a=e;b=d;continue}else d=j;else d=l(d);break;case 8:f=e[1];e=e[2];g=l(b);if(8==g[0])if(d=g[2],U(f,g[1])){a=e;b=d;continue}else d=j;else d=l(d);break;default:d=l(d)}return d}}
var V=[1,U,function(a,b){return U(a,b)?j:h}],Ce=[4,H],De=[2,E,[2,Ce,A]],Ee=[4,E],Fe=[2,H,[2,Ee,A]],Ge=[2,H,[2,Ee,A]],He=[2,E,[2,Ce,A]];
function Ie(a){if(Ae(function(b){return O(V,b,a)},Ge))var b=[1];else{var d=m(function(){return Be(a)}),e=function(a){a=l(a);if(1==a[0])a=j;else{var b=a[1],f=a[2],a=m(function(){return e(f)}),g=l(d);if(1==g[0])a=l(a);else{var i=g[1],p=g[2],k=m(function(){var a=l(i);if(4==a[0])a=U(b,a[1]);else var d=l(b),a=4==d[0]?U(d[1],a):j;return a}),g=l(b);switch(g[0]){case 1:if(2==l(i)[0])a=h;else if(l(k))a=h;else a:{for(g=p;;){p=l(g);if(1==p[0])a=l(a);else switch(g=p[2],p=l(p[1]),p[0]){case 2:a=h;break;case 4:if(U(H,
p[1]))a=h;else continue;break;default:continue}break a}a=c}break;case 2:if(1==l(i)[0])a=h;else if(l(k))a=h;else a:{for(g=p;;){p=l(g);if(1==p[0])a=l(a);else switch(g=p[2],p=l(p[1]),p[0]){case 1:a=h;break;case 4:if(U(E,p[1]))a=h;else continue;break;default:continue}break a}a=c}break;default:if(l(k))a=h;else a:{for(;;){k=l(p);if(1==k[0])a=l(a);else if(p=k[2],k=l(k[1]),4==k[0])if(U(g,k[1]))a=h;else continue;else{var G=l(g);if(4==G[0])if(U(G[1],k))a=h;else continue;else continue}break a}a=c}}}}return a};
if(e(a))b=[1];else{var b=P(V,a),f=Vb(V,b,He);if(1==f[0])b=[2];else if(b=f[1],f=l(f[2]),1==f[0])b=l(b);else var g=f[1],i=f[2],b=[6,b,m(function(){return R(Ad,g,i)})]}}return b}function Je(a){var b=l(a);if(6==b[0])var d=b[2],a=m(function(){return Je(d)}),b=Je(b[1]),a=z(b,a);else a=[2,b,A];return a}function Ke(a){var b=l(a);switch(b[0]){case 5:var d=b[2],a=m(function(){return Ke(d)}),e=Ke(b[1]),a=z(e,a);break;case 6:a=[2,m(function(){return Je(b)}),A];break;default:a=[2,[2,b,A],A]}return a}
var Le=[4,E],Me=[2,H,[2,Le,A]],Ne=[4,H],Oe=[2,E,[2,Ne,A]],Pe=[2,H,[2,Le,A]],Qe=[2,E,[2,Ne,A]];
function Re(a){if(Ae(function(b){return O(V,b,a)},Qe))var b=[2];else{var d=m(function(){return Be(a)}),e=function(a){a=l(a);if(1==a[0])a=j;else{var b=a[1],f=a[2],a=m(function(){return e(f)}),g=l(d);if(1==g[0])a=l(a);else{var i=g[1],p=g[2],k=m(function(){var a=l(i);if(4==a[0])a=U(b,a[1]);else var d=l(b),a=4==d[0]?U(d[1],a):j;return a}),g=l(b);switch(g[0]){case 1:if(2==l(i)[0])a=h;else if(l(k))a=h;else a:{for(g=p;;){p=l(g);if(1==p[0])a=l(a);else switch(g=p[2],p=l(p[1]),p[0]){case 2:a=h;break;case 4:if(U(H,
p[1]))a=h;else continue;break;default:continue}break a}a=c}break;case 2:if(1==l(i)[0])a=h;else if(l(k))a=h;else a:{for(g=p;;){p=l(g);if(1==p[0])a=l(a);else switch(g=p[2],p=l(p[1]),p[0]){case 1:a=h;break;case 4:if(U(E,p[1]))a=h;else continue;break;default:continue}break a}a=c}break;default:if(l(k))a=h;else a:{for(;;){k=l(p);if(1==k[0])a=l(a);else if(p=k[2],k=l(k[1]),4==k[0])if(U(g,k[1]))a=h;else continue;else{var G=l(g);if(4==G[0])if(U(G[1],k))a=h;else continue;else continue}break a}a=c}}}}return a};
if(e(a))b=[2];else{var b=P(V,a),f=Vb(V,b,Pe);if(1==f[0])b=[1];else if(b=f[1],f=l(f[2]),1==f[0])b=l(b);else var g=f[1],i=f[2],b=[5,b,m(function(){return R(Bd,g,i)})]}}return b}function Se(a){var b=l(a);if(5==b[0])var d=b[2],a=m(function(){return Se(d)}),b=Se(b[1]),a=z(b,a);else a=[2,b,A];return a}function Te(a){var b=l(a);switch(b[0]){case 5:a=[2,m(function(){return Se(b)}),A];break;case 6:var d=b[2],a=m(function(){return Te(d)}),e=Te(b[1]),a=z(e,a);break;default:a=[2,[2,b,A],A]}return a}
var Ue=m(function(){return u("parser: input not exhausted")}),Ve=[3],W=[1,0];function We(a,b){var d=n(a,[b]);if(1==d[0])d=[1,d[1]];else{var e=l(d[1]),d=e[1],e=e[2],f=We(a,d);1==f[0]?d=[2,[1,d,[2,e,A]]]:(d=l(f[1]),d=[2,[1,d[1],[2,e,d[2]]]])}return d}var X=m(function(){return u("not satisfied")}),Y=[1,A,X],Xe=[1,Y];
function Ye(a){a=l(a);if(1==a[0])a=l(Xe);else{var b=a[2],d=l(a[1]),e=l(d[1]);switch(e){case "\t":a=[2,[1,b,d]];break;case "\n":a=[2,[1,b,d]];break;case "\v":a=[2,[1,b,d]];break;case "\f":a=[2,[1,b,d]];break;case "\r":a=[2,[1,b,d]];break;case " ":a=[2,[1,b,d]];break;case "p":a=[2,[1,b,d]];break;default:a=l(9==e.charCodeAt(0)||10==e.charCodeAt(0)||13==e.charCodeAt(0)||32==e.charCodeAt(0))?[2,[1,b,d]]:[1,[1,a,X]]}}return a}
var Ze=[12],$e=[1,Y],af=[10],bf=m(function(){return u("->")}),cf=[1,function(a,b){var d=l(a)[1],e=l(b)[1];return d==e},function(a,b){var d=l(a)[1],e=l(b)[1];return d!=e}];function df(a,b){var d=l(a);if(d){var e=l(b);if(1==e[0])e=[1,A,A];else var f=e[2],g=m(function(){var a=df(d-1|0,f);return[1,a[1],a[2]]}),e=[1,[2,e[1],m(function(){var a=l(g)[1];return l(a)})],m(function(){var a=l(g)[2];return l(a)})]}else e=[1,A,b];return e}var ef=[1,")"],ff=[1,"("];
function gf(a){a=l(a)[1];a=u_towlower(a.charCodeAt(0),0)[2];if(1114111>=a>>>0)a=[1,String.fromCharCode(a)];else var b=l([1,a])[1],a=v("Prelude.chr: bad argument: ",m(function(){return 0>b?[2,ff,m(function(){return Ea(b,[2,ef,A])})]:Ea(b,A)})),a=r(a);return a}
function hf(a){var b=m(function(){return[1,x(a)]}),d=m(function(){return M(gf,a)});return l(function(e){var f;a:{f=d;for(var g=m(function(){return M(gf,e)});;){var i=l(f);if(1==i[0])f=h;else{f=i[1];var i=i[2],o=l(g);if(1==o[0])f=j;else if(g=o[2],n(N,[cf,f,o[1]])){f=i;continue}else f=j}break a}f=c}if(f){var s=m(function(){var a=l(b)[1];0>a?a=[1,e,A]:(a=df(a,e),a=[1,a[2],a[1]]);return a});f=[2,[1,m(function(){var a=l(s)[1];return l(a)}),m(function(){var a=l(s)[2];return l(a)})]]}else f=[1,[1,e,a]];
return f})}var jf=m(function(){return hf(bf)}),kf=[11],lf=m(function(){return u("<->")}),mf=m(function(){return hf(lf)}),nf=[9],of=[1,Y],pf=m(function(){return u("v\u2228")}),qf=[8],rf=[1,Y],sf=m(function(){return u("^\u2227")}),tf=[7],uf=[1,Y],vf=m(function(){return u("!\u00ac")}),wf=[5],xf=[2,[1,")"],A],yf=m(function(){return hf(xf)}),zf=[4],Af=[2,[1,"("],A],Bf=m(function(){return hf(Af)}),Cf=[6],Df=[1,Y],Ef=[1,Y];
function Ff(a){a=l(a);if(1==a[0])a=l(Ef);else var b=a[2],d=l(a[1]),a=l(da(d[1].charCodeAt(0))[2])?[2,[1,b,d]]:[1,[1,a,X]];return a}
var Gf=[1,Y],Hf=[2],If=[2,[1,"0"],A],Jf=m(function(){return hf(If)}),Kf=[2,function(a){a=n(Jf,[a]);1==a[0]?a=[1,a[1]]:(a=l(a[1]),a=[2,[1,a[1],[1,Hf,W,a[2]]]]);return a},[2,function(a){var b=l(a);if(1==b[0])a=l(Gf);else{var d=b[2],a=l(b[1]);l(da(a[1].charCodeAt(0))[2])?(b=We(Ff,d),1==b[0]?a=[1,b[1]]:(b=l(b[1]),a=[2,[1,b[1],[1,Cf,W,[2,a,b[2]]]]])):a=[1,[1,b,X]]}return a},[2,function(a){var b=l(a);if(1==b[0])a=l(Df);else{var d=b[2],a=l(b[1]),e=a[1];l(da(e.charCodeAt(0))[2])?"v"==l(e)?a=[1,[1,b,X]]:(b=
l(d),1==b[0]?a=[2,[1,A,[1,Cf,W,[2,a,A]]]]:(d=l(b[1])[1].charCodeAt(0),a=l(da(d)[2])?[1,[1,b,gb]]:[2,[1,b,[1,Cf,W,[2,a,A]]]])):a=[1,[1,b,X]]}return a},[2,function(a){a=n(Bf,[a]);1==a[0]?a=[1,a[1]]:(a=l(a[1]),a=[2,[1,a[1],[1,zf,W,a[2]]]]);return a},[2,function(a){a=n(yf,[a]);1==a[0]?a=[1,a[1]]:(a=l(a[1]),a=[2,[1,a[1],[1,wf,W,a[2]]]]);return a},[2,function(a){a=l(a);if(1==a[0])a=l(uf);else var b=a[1],d=a[2],a=O(cf,b,vf)?[2,[1,d,[1,tf,W,[2,b,A]]]]:[1,[1,a,X]];return a},[2,function(a){a=l(a);if(1==a[0])a=
l(rf);else var b=a[1],d=a[2],a=O(cf,b,sf)?[2,[1,d,[1,qf,W,[2,b,A]]]]:[1,[1,a,X]];return a},[2,function(a){a=l(a);if(1==a[0])a=l(of);else var b=a[1],d=a[2],a=O(cf,b,pf)?[2,[1,d,[1,nf,W,[2,b,A]]]]:[1,[1,a,X]];return a},[2,function(a){a=n(mf,[a]);1==a[0]?a=[1,a[1]]:(a=l(a[1]),a=[2,[1,a[1],[1,kf,W,a[2]]]]);return a},[2,function(a){a=n(jf,[a]);1==a[0]?a=[1,a[1]]:(a=l(a[1]),a=[2,[1,a[1],[1,af,W,a[2]]]]);return a},[2,function(a){a=l(a);return 1==a[0]?l($e):[2,[1,a[2],[1,Ze,W,[2,a[1],A]]]]},A]]]]]]]]]]];
function Lf(a,b,d){a=n(a,[d]);return 1==a[0]?n(b,[d]):l(a)}var Mf=[1],Nf=[2,[1,"1"],A],Of=m(function(){return hf(Nf)});function Pf(a){a=n(Of,[a]);1==a[0]?a=[1,a[1]]:(a=l(a[1]),a=[2,[1,a[1],[1,Mf,W,a[2]]]]);return a}var Qf=m(function(){return R(Lf,Pf,Kf)});function Rf(a){var b=We(Ye,a);1==b[0]?a=n(Qf,[a]):(a=l(b[1]),a=[2,[1,a[1],[1,Ve,W,a[2]]]]);return a}var Sf=[1,-1];function Tf(a){a=l(a)[1];return 3==l(a)[0]?j:h}
function Uf(a,b){var d=n(a,[b]);if(1==d[0])d=l(d);else var e=l(d[1]),d=e[2],e=l(e[1]),d=1==e[0]?[2,[1,A,d]]:[1,[1,e,gb]];return d}var Z=[1,A,X],Vf=[1,Z];function Wf(a){a=l(a);if(1==a[0])a=l(Vf);else var b=a[2],d=l(a[1])[1],a=2==l(d)[0]?[2,[1,b,E]]:[1,[1,a,X]];return a}var Xf=[1,Z];function Yf(a){a=l(a);if(1==a[0])a=l(Xf);else var b=a[2],d=l(a[1]),e=d[3],a=6==l(d[1])[0]?[2,[1,b,[3,e]]]:[1,[1,a,X]];return a}var Zf=[4,H],$f=[1,Z];
function ag(a){a=l(a);if(1==a[0])a=l($f);else{var b=a[2],d=l(a[1])[1];7==l(d)[0]?(a=l(b),1==a[0]?(a=l(bg),1==a[0]?a=l(a):(a=l(a[1]),a=[2,[1,a[1],[4,a[2]]]])):(b=a[2],d=l(a[1])[1],1==l(d)[0]?a=[2,[1,b,Zf]]:(a=n($,[a]),1==a[0]?a=l(a):(a=l(a[1]),a=[2,[1,a[1],[4,a[2]]]])))):a=[1,[1,a,X]]}return a}var cg=[1,Z],dg=[1,Z];
function eg(a,b){var d=l(b);if(1==d[0])d=l(cg);else{var e=d[2],f=l(d[1])[1];if(4==l(f)[0])if(d=n(a,[e]),1==d[0])d=l(d);else if(e=l(d[1]),d=e[2],e=l(e[1]),1==e[0])d=l(dg);else var f=e[2],g=l(e[1])[1],d=5==l(g)[0]?[2,[1,f,d]]:[1,[1,e,X]];else d=[1,[1,d,X]]}return d}
var gg=m(function(){var a=M(eg,fg);if(1==a[0])a=l(zd);else{var b=a[1],a=l(a[2]);if(1==a[0])a=l(b);else var d=a[1],e=a[2],f=m(function(){return R(Lf,d,e)}),a=l(function(a){var d=n(b,[a]);return 1==d[0]?n(f,[a]):l(d)})}return a}),hg=m(function(){return[2,gg,A]}),ig=m(function(){return[2,ag,hg]}),jg=m(function(){return[2,Yf,ig]}),$=m(function(){return R(Lf,Wf,jg)}),bg=m(function(){return n($,[A])}),kg=[1,Z];
function lg(a){a=l(a);if(1==a[0])a=l(kg);else var b=a[2],d=l(a[1])[1],a=9==l(d)[0]?[2,[1,b,Ad]]:[1,[1,a,X]];return a}var mg=m(function(){return R(Lf,lg,A)});
function ng(a,b){function d(a,d){var e=og(a);if(1==e[0])if(e=l(a),1==e[0])if(e=n($,[A]),1==e[0])e=l(e);else var e=l(e[1]),f=e[2],e=[2,[1,e[1],m(function(){return n(d,[b,f])})]];else{var g=e[2],D=l(e[1])[1];if(1==l(D)[0])e=[2,[1,g,m(function(){return n(d,[b,H])})]];else if(e=n($,[e]),1==e[0])e=l(e);else var e=l(e[1]),p=e[2],e=[2,[1,e[1],m(function(){return n(d,[b,p])})]]}else var e=l(e[1]),k=e[2],e=[2,[1,e[1],m(function(){return n(d,[b,k])})]];return e}var e=l(a);if(1==e[0]){var f=n(mg,[A]);1==f[0]?
f=[1,f[1]]:(f=l(f[1]),f=d(f[1],f[2]))}else{var f=e[2],g=l(e[1])[1];8==l(g)[0]?(e=og(f),1==e[0]?(f=l(f),1==f[0]?(f=n($,[A]),1==f[0]?f=l(f):(f=l(f[1]),f=[2,[1,f[1],[5,b,f[2]]]])):(e=f[2],g=l(f[1])[1],1==l(g)[0]?f=[2,[1,e,[5,b,H]]]:(f=n($,[f]),1==f[0]?f=l(f):(f=l(f[1]),f=[2,[1,f[1],[5,b,f[2]]]])))):(f=l(e[1]),f=[2,[1,f[1],[5,b,f[2]]]])):(f=n(mg,[e]),1==f[0]?f=[1,f[1]]:(f=l(f[1]),f=d(f[1],f[2])))}return f}
function og(a){a=l(a);if(1==a[0])if(a=l(bg),1==a[0])a=l(a);else var a=l(a[1]),b=a[1],d=a[2],e=function(a,b){function d(a,e){var g=f(a);if(1==g[0])if(g=l(a),1==g[0])if(g=n($,[A]),1==g[0])g=l(g);else var g=l(g[1]),i=g[2],g=[2,[1,g[1],m(function(){return n(e,[b,i])})]];else{var q=g[2],o=l(g[1])[1];if(1==l(o)[0])g=[2,[1,q,m(function(){return n(e,[b,H])})]];else if(g=n($,[g]),1==g[0])g=l(g);else var g=l(g[1]),p=g[2],g=[2,[1,g[1],m(function(){return n(e,[b,p])})]]}else var g=l(g[1]),B=g[2],g=[2,[1,g[1],
m(function(){return n(e,[b,B])})]];return g}var e=l(a);if(1==e[0]){var g=n(mg,[A]);1==g[0]?g=[1,g[1]]:(g=l(g[1]),g=d(g[1],g[2]))}else{var g=e[2],i=l(e[1])[1];8==l(i)[0]?(e=f(g),1==e[0]?(g=l(g),1==g[0]?(g=n($,[A]),1==g[0]?g=l(g):(g=l(g[1]),g=[2,[1,g[1],[5,b,g[2]]]])):(e=g[2],i=l(g[1])[1],1==l(i)[0]?g=[2,[1,e,[5,b,H]]]:(g=n($,[g]),1==g[0]?g=l(g):(g=l(g[1]),g=[2,[1,g[1],[5,b,g[2]]]])))):(g=l(e[1]),g=[2,[1,g[1],[5,b,g[2]]]])):(g=n(mg,[e]),1==g[0]?g=[1,g[1]]:(g=l(g[1]),g=d(g[1],g[2])))}return g},f=function(a){a=
l(a);if(1==a[0])a=e(b,d);else{var f=a[2],g=l(a[1])[1];1==l(g)[0]?a=e(f,H):(a=n($,[a]),1==a[0]?a=l(a):(a=l(a[1]),a=e(a[1],a[2])))}return a},a=e(b,d);else{var g=a[2],i=l(a[1])[1];1==l(i)[0]?a=ng(g,H):(a=n($,[a]),1==a[0]?a=l(a):(a=l(a[1]),a=ng(a[1],a[2])))}return a}function pg(a,b){return[8,a,b]}var qg=[1,Z];function rg(a){a=l(a);if(1==a[0])a=l(qg);else var b=a[2],d=l(a[1])[1],a=11==l(d)[0]?[2,[1,b,pg]]:[1,[1,a,X]];return a}var sg=m(function(){return R(Lf,rg,A)}),tg=m(function(){return n(sg,[A])});
function ug(a,b){function d(b,d){var e=vg(b);if(1==e[0])if(e=og(b),1==e[0])if(e=l(b),1==e[0])if(e=l(bg),1==e[0])e=l(e);else var e=l(e[1]),f=e[2],e=[2,[1,e[1],m(function(){return n(d,[a,f])})]];else{var g=e[2],D=l(e[1])[1];if(1==l(D)[0])e=[2,[1,g,m(function(){return n(d,[a,H])})]];else if(e=n($,[e]),1==e[0])e=l(e);else var e=l(e[1]),p=e[2],e=[2,[1,e[1],m(function(){return n(d,[a,p])})]]}else var e=l(e[1]),k=e[2],e=[2,[1,e[1],m(function(){return n(d,[a,k])})]];else var e=l(e[1]),G=e[2],e=[2,[1,e[1],
m(function(){return n(d,[a,G])})]];return e}var e=l(b);if(1==e[0]){var f=l(tg);1==f[0]?f=[1,f[1]]:(f=l(f[1]),f=d(f[1],f[2]))}else{var f=e[2],g=l(e[1])[1];10==l(g)[0]?(e=vg(f),1==e[0]?(e=og(f),1==e[0]?(f=l(f),1==f[0]?(f=l(bg),1==f[0]?f=l(f):(f=l(f[1]),f=[2,[1,f[1],[7,a,f[2]]]])):(e=f[2],g=l(f[1])[1],1==l(g)[0]?f=[2,[1,e,[7,a,H]]]:(f=n($,[f]),1==f[0]?f=l(f):(f=l(f[1]),f=[2,[1,f[1],[7,a,f[2]]]])))):(f=l(e[1]),f=[2,[1,f[1],[7,a,f[2]]]])):(f=l(e[1]),f=[2,[1,f[1],[7,a,f[2]]]])):(f=n(sg,[e]),1==f[0]?f=[1,
f[1]]:(f=l(f[1]),f=d(f[1],f[2])))}return f}
function vg(a){var b=og(a);if(1==b[0])if(a=l(a),1==a[0])if(a=l(bg),1==a[0])a=l(a);else var a=l(a[1]),d=a[1],e=a[2],f=function(a,b){function d(a,e){var f=g(a);if(1==f[0])if(f=l(a),1==f[0])if(f=n($,[A]),1==f[0])f=l(f);else var f=l(f[1]),i=f[2],f=[2,[1,f[1],m(function(){return n(e,[b,i])})]];else{var q=f[2],k=l(f[1])[1];if(1==l(k)[0])f=[2,[1,q,m(function(){return n(e,[b,H])})]];else if(f=n($,[f]),1==f[0])f=l(f);else var f=l(f[1]),o=f[2],f=[2,[1,f[1],m(function(){return n(e,[b,o])})]]}else var f=l(f[1]),
p=f[2],f=[2,[1,f[1],m(function(){return n(e,[b,p])})]];return f}var e=l(a);if(1==e[0]){var f=n(mg,[A]);1==f[0]?f=[1,f[1]]:(f=l(f[1]),f=d(f[1],f[2]))}else{var f=e[2],i=l(e[1])[1];8==l(i)[0]?(e=g(f),1==e[0]?(f=l(f),1==f[0]?(f=n($,[A]),1==f[0]?f=l(f):(f=l(f[1]),f=[2,[1,f[1],[5,b,f[2]]]])):(e=f[2],i=l(f[1])[1],1==l(i)[0]?f=[2,[1,e,[5,b,H]]]:(f=n($,[f]),1==f[0]?f=l(f):(f=l(f[1]),f=[2,[1,f[1],[5,b,f[2]]]])))):(f=l(e[1]),f=[2,[1,f[1],[5,b,f[2]]]])):(f=n(mg,[e]),1==f[0]?f=[1,f[1]]:(f=l(f[1]),f=d(f[1],f[2])))}return f},
g=function(a){a=l(a);if(1==a[0])a=f(d,e);else{var b=a[2],g=l(a[1])[1];1==l(g)[0]?a=f(b,H):(a=n($,[a]),1==a[0]?a=l(a):(a=l(a[1]),a=f(a[1],a[2])))}return a},i=function(a,b){function f(b,i){var k=o(b);if(1==k[0])if(k=g(b),1==k[0])if(k=l(b),1==k[0])k=[2,[1,d,m(function(){return n(i,[a,e])})]];else{var p=k[2],s=l(k[1])[1];if(1==l(s)[0])k=[2,[1,p,m(function(){return n(i,[a,H])})]];else if(k=n($,[k]),1==k[0])k=l(k);else var k=l(k[1]),B=k[2],k=[2,[1,k[1],m(function(){return n(i,[a,B])})]]}else var k=l(k[1]),
D=k[2],k=[2,[1,k[1],m(function(){return n(i,[a,D])})]];else var k=l(k[1]),G=k[2],k=[2,[1,k[1],m(function(){return n(i,[a,G])})]];return k}var i=l(b);if(1==i[0]){var k=l(tg);1==k[0]?k=[1,k[1]]:(k=l(k[1]),k=f(k[1],k[2]))}else{var k=i[2],s=l(i[1])[1];10==l(s)[0]?(i=o(k),1==i[0]?(i=g(k),1==i[0]?(k=l(k),1==k[0]?k=[2,[1,d,[7,a,e]]]:(i=k[2],s=l(k[1])[1],1==l(s)[0]?k=[2,[1,i,[7,a,H]]]:(k=n($,[k]),1==k[0]?k=l(k):(k=l(k[1]),k=[2,[1,k[1],[7,a,k[2]]]])))):(k=l(i[1]),k=[2,[1,k[1],[7,a,k[2]]]])):(k=l(i[1]),k=[2,
[1,k[1],[7,a,k[2]]]])):(k=n(sg,[i]),1==k[0]?k=[1,k[1]]:(k=l(k[1]),k=f(k[1],k[2])))}return k},o=function(a){var b=g(a);if(1==b[0])if(a=l(a),1==a[0])a=i(e,d);else{var b=a[2],f=l(a[1])[1];1==l(f)[0]?a=i(H,b):(a=n($,[a]),1==a[0]?a=l(a):(a=l(a[1]),a=i(a[2],a[1])))}else a=l(b[1]),a=i(a[2],a[1]);return a},a=i(e,d);else{var b=a[2],s=l(a[1])[1];1==l(s)[0]?a=ug(H,b):(a=n($,[a]),1==a[0]?a=l(a):(a=l(a[1]),a=ug(a[2],a[1])))}else a=l(b[1]),a=ug(a[2],a[1]);return a}
function wg(a){var b=vg(a);if(1==b[0])if(b=og(a),1==b[0])if(a=l(a),1==a[0])a=l(bg);else var b=a[2],d=l(a[1])[1],a=1==l(d)[0]?[2,[1,b,H]]:n($,[a]);else a=l(b);else a=l(b);return a}
var yg=[1,Z],zg=[2,function(a){a=l(a);if(1==a[0])a=l(yg);else var b=a[2],d=l(a[1])[1],a=1==l(d)[0]?[2,[1,b,H]]:[1,[1,a,X]];return a},[2,Wf,[2,Yf,A]]],Ag=m(function(){return[2,ag,zg]}),fg=m(function(){return[2,wg,Ag]}),Cg=m(function(){var a=M(Uf,fg);if(1==a[0])a=l(zd);else{var b=a[1],a=l(a[2]);if(1==a[0])a=l(b);else var d=a[1],e=a[2],f=m(function(){return R(Lf,d,e)}),a=l(function(a){var d=n(b,[a]);return 1==d[0]?n(f,[a]):l(d)})}return a});
function Dg(a,b){var d=l(b);if(1==d[0])d=[1];else var e=d[2],d=l(d[1]),f=d[3],d=[2,[1,d[1],a,f],m(function(){return Dg(m(function(){var b=l(a)[1],d=x(f);return[1,b+d|0]}),e)})];return d}
function Eg(a){var b=We(Rf,a);if(1==b[0])var d=l(b[1]),e=d[1],f=d[2],g=Fa(m(function(){var b=x(a),d=x(e);return[1,b-d|0]}),m(function(){return v("tokenizer: ",f)}));else{var i=l(b[1]),o=i[2],s=l(i[1]);if(1==s[0]){var q=n(Cg,[m(function(){var a=Dg(W,o);return y(Tf,a)})]);if(1==q[0]){var B=l(q[1]),D=B[2],p=l(B[1]);if(1==p[0])var k=Fa(Sf,D);else var G=p[1],k=Fa(m(function(){var a=l(G)[2];return l(a)}),D);var ga=k}else{var Qb=l(q[1]),Aa=Qb[2],Rb=l(Qb[1]);if(1==Rb[0]){var xg=l(fb)[1],vc=l(w(xg)[2]);if(1==
vc[0])var xc=l(ib);else{var Bg=l(vc[1])[1],Hg=l(db)[1],pb=m(function(){return Ib(m(function(){return J(Lb,m(function(){return J(Kb,m(function(){return Ib(m(function(){return J(Ob,Aa)}))}))}))}))}),Ac=m(function(){return Ib(m(function(){return J(Mb,pb)}))}),Ig=F(Ac),Jg=t(Ig)[1];ea(Bg,Hg,Jg);var Kg=l(cb)[1],Bc=l(w(Kg)[2]);if(1==Bc[0])var Cc=l(jb);else{var Lg=l(Bc[1])[1],Mg=l(ab)[1],Ia=m(function(){var a=Ke(Ac);return M(Ie,a)});if(Ae(function(a){return O(V,a,Ia)},De))var Dc=[2];else{var Ng=m(function(){return Be(Ia)}),
Ec=function(a){a=l(a);if(1==a[0])a=j;else{var b=a[1],d=a[2],a=m(function(){return Ec(d)}),e=l(Ng);if(1==e[0])a=l(a);else{var f=e[1],g=e[2],i=m(function(){var a=l(f);if(4==a[0])a=U(b,a[1]);else var d=l(b),a=4==d[0]?U(d[1],a):j;return a}),e=l(b);switch(e[0]){case 1:if(2==l(f)[0])a=h;else if(l(i))a=h;else a:{for(e=g;;){g=l(e);if(1==g[0])a=l(a);else switch(e=g[2],g=l(g[1]),g[0]){case 2:a=h;break;case 4:if(U(H,g[1]))a=h;else continue;break;default:continue}break a}a=c}break;case 2:if(1==l(f)[0])a=h;else if(l(i))a=
h;else a:{for(e=g;;){g=l(e);if(1==g[0])a=l(a);else switch(e=g[2],g=l(g[1]),g[0]){case 1:a=h;break;case 4:if(U(E,g[1]))a=h;else continue;break;default:continue}break a}a=c}break;default:if(l(i))a=h;else a:{for(;;){i=l(g);if(1==i[0])a=l(a);else if(g=i[2],i=l(i[1]),4==i[0])if(U(e,i[1]))a=h;else continue;else{var k=l(e);if(4==k[0])if(U(k[1],i))a=h;else continue;else continue}break a}a=c}}}}return a};if(Ec(Ia))var Fc=[2];else{var Og=P(V,Ia),qb=Vb(V,Og,Fe);if(1==qb[0])var Gc=[1];else{var Hc=qb[1],rb=l(qb[2]);
if(1==rb[0])var Ic=l(Hc);else var Pg=rb[1],Qg=rb[2],Ic=[5,Hc,m(function(){return R(Bd,Pg,Qg)})];Gc=Ic}Fc=Gc}Dc=Fc}var Rg=F(Dc),Sg=t(Rg)[1];ea(Lg,Mg,Sg);var Tg=l($a)[1],Jc=l(w(Tg)[2]);if(1==Jc[0])var Kc=l(kb);else{var Ug=l(Jc[1])[1],Vg=l(Ya)[1],Lc=m(function(){return Ib(m(function(){return J(Nb,pb)}))}),Wg=F(Lc),Xg=t(Wg)[1];ea(Ug,Vg,Xg);var Yg=l(Xa)[1],Mc=l(w(Yg)[2]);if(1==Mc[0])var Nc=l(Ma);else{var Zg=l(Mc[1])[1],$g=l(Wa)[1],Ja=m(function(){var a=Te(Lc);return M(Re,a)});if(Ae(function(a){return O(V,
a,Ja)},Me))var Oc=[1];else{var ah=m(function(){return Be(Ja)}),Pc=function(a){a=l(a);if(1==a[0])a=j;else{var b=a[1],d=a[2],a=m(function(){return Pc(d)}),e=l(ah);if(1==e[0])a=l(a);else{var f=e[1],g=e[2],i=m(function(){var a=l(f);if(4==a[0])a=U(b,a[1]);else var d=l(b),a=4==d[0]?U(d[1],a):j;return a}),e=l(b);switch(e[0]){case 1:if(2==l(f)[0])a=h;else if(l(i))a=h;else a:{for(e=g;;){g=l(e);if(1==g[0])a=l(a);else switch(e=g[2],g=l(g[1]),g[0]){case 2:a=h;break;case 4:if(U(H,g[1]))a=h;else continue;break;
default:continue}break a}a=c}break;case 2:if(1==l(f)[0])a=h;else if(l(i))a=h;else a:{for(e=g;;){g=l(e);if(1==g[0])a=l(a);else switch(e=g[2],g=l(g[1]),g[0]){case 1:a=h;break;case 4:if(U(E,g[1]))a=h;else continue;break;default:continue}break a}a=c}break;default:if(l(i))a=h;else a:{for(;;){i=l(g);if(1==i[0])a=l(a);else if(g=i[2],i=l(i[1]),4==i[0])if(U(e,i[1]))a=h;else continue;else{var k=l(e);if(4==k[0])if(U(k[1],i))a=h;else continue;else continue}break a}a=c}}}}return a};if(Pc(Ja))var Qc=[1];else{var bh=
P(V,Ja),sb=Vb(V,bh,Oe);if(1==sb[0])var Rc=[2];else{var Sc=sb[1],tb=l(sb[2]);if(1==tb[0])var Tc=l(Sc);else var ch=tb[1],dh=tb[2],Tc=[6,Sc,m(function(){return R(Ad,ch,dh)})];Rc=Tc}Qc=Rc}Oc=Qc}var eh=F(Oc),fh=t(eh)[1];ea(Zg,$g,fh);var gh=l(Va)[1],Uc=l(w(gh)[2]);if(1==Uc[0])var Vc=l(Oa);else{var hh=l(Uc[1])[1],ih=l(Ua)[1],jh=F(pb),kh=t(jh)[1];ea(hh,ih,kh);var lh=l(Ta)[1],Wc=l(w(lh)[2]);if(1==Wc[0])var Xc=l(Qa);else{var mh=l(Wc[1])[1],nh=l(Sa)[1],Yc=S(Hd,A,Aa),ub=x(Yc),Ka=function(a){a=l(a);if(1==a[0])a=
[1];else var b=a[1],d=m(function(){return pd(oe,A,Yc,b)}),e=Ka(a[2]),a=m(function(){return le(d,Aa)}),f=m(function(){return Kd(xe)}),e=Tb(function(a,b){return n(N,[f,m(function(){var b=l(a)[1];return l(b)}),m(function(){var a=l(b)[1];return l(a)})])},[1,d,Nd],e),a=Ed(function(a,b){return n(Ld,[xe,m(function(){var b=l(a)[1];return l(b)}),m(function(){var a=l(b)[1];return l(a)})])},[1,d,a],e);return a};if(0>=ub)var Zc=Ka(me);else{if(0<=ub)var oh=Od(ub,ze),ph=Sd(oh),$c=Ka(ph);else $c=Ka(me);Zc=$c}var qh=
Jd(Zc),ad=Sb(qh,xd),bd,La=vd(A,ad,ad,A),vb,cd=function(a){for(;;){var b=l(a);if(1==b[0])a=[1];else if(a=b[2],b=lc(function(a){return function(b){b=Yb(b);return O($b,a,b)}}(b[1]),La),1==x(b))a=[2,function(a,b){return m(function(){var d=l(b);if(1==d[0])d=l(uc);else if(d=l(d[1])[1],0>d)d=l(nc);else a:{for(var e=a;;){var f=l(e);if(1==f[0])d=l(pc);else if(e=f[1],f=f[2],d=l(d)){d=d-1|0;e=f;continue}else d=l(e);break a}d=c}return d})}(La,b),function(a,b){return m(function(){return b(a)})}(a,cd)];else continue;
return a}},rh=M(Yb,La),sh=wc(rh),th=P($b,sh);vb=cd(th);bd=z(vb,m(function(){function a(b,d){var e;a:{e=b;for(var f=d;;){var g=l(f);if(1==g[0]){e=l(e);break a}var f=g[1],g=g[2],i=x(e),k=x(f);i<k||i!=k&&(e=f);f=g}e=c}var o=x(e);e=x(b);f=m(function(){function a(b){var d=l(b);if(1==d[0])b=[1,A,A];else var b=d[1],e=d[2],d=x(b),f=m(function(){var b=a(e);return[1,b[1],b[2]]}),b=o==d?[1,[2,b,m(function(){var a=l(f)[1];return l(a)})],m(function(){var a=l(f)[2];return l(a)})]:[1,m(function(){var a=l(f)[1];
return l(a)}),[2,b,m(function(){var a=l(f)[2];return l(a)})]];return b}var b=a(d);return[1,b[1],b[2]]});o==e?(e=l(f)[1],e=nd(b,e)):(e=l(f)[1],e=l(e),e=1==e[0]?l(Xb):nd(e[1],e[2]));return e}function b(a){a=l(a);if(1==a[0])a=[1];else var e=a[1],f=a[2],a=[2,m(function(){function a(b){for(;;){var d=l(b);if(1==d[0])b=[1];else{var b=d[1],d=d[2],f=Yb(b);if(O($b,e,f))b=[2,[2,b,A],function(a,b){return m(function(){return b(a)})}(d,a)];else{b=d;continue}}return b}}return a(d)}),m(function(){return b(f)})];
return a}var d=Vb(Q,La,vb),e=yc(d),e=P($b,e),e=b(e);if(1==e[0])e=[1];else{var f=e[1],g=l(e[2]);if(1==g[0])e=l(f);else{var i=g[1];a:{e=m(function(){function a(b){b=l(b);if(1==b[0])b=[1];else var d=b[1],e=b[2],f=m(function(){return a(e)}),g=function(a){a=l(a);if(1==a[0])a=l(f);else var b=a[1],e=a[2],a=[2,m(function(){return z(d,b)}),m(function(){return g(e)})];return a},b=g(i);return b}var b=a(f);return kc(b)});for(g=g[2];;){g=l(g);if(1==g[0]){e=l(e);break a}var k=g[2],e=function(a,b){return m(function(){function d(a){a=
l(a);if(1==a[0])a=[1];else var e=a[1],f=a[2],g=m(function(){return d(f)}),i=function(a){a=l(a);if(1==a[0])a=l(g);else var b=a[1],d=a[2],a=[2,m(function(){return z(e,b)}),m(function(){return i(d)})];return a},a=i(b);return a}var e=d(a);return kc(e)})}(e,g[1]),g=k}e=c}}e=1==e[0]?[1]:a(e[1],e[2])}return e}));var uh=M(Pb,bd),vh=m(function(){return S(Hd,A,Aa)}),dd=function(a){for(;;){var b=l(a);if(1==b[0])a=[1];else if(a=b[2],b=pd(Dd,A,vh,b[1]),1==b[0])continue;else a=[2,b,function(a,b){return m(function(){return b(a)})}(a,
dd)];return a}},ed=dd(uh);if(1==ed[0])var fd=[1];else{var wb=M(Cd,ed);if(1==wb[0])var gd=l(zd);else{var hd=wb[1],xb=l(wb[2]);if(1==xb[0])var id=l(hd);else var wh=xb[1],xh=xb[2],id=[6,hd,m(function(){return R(Ad,wh,xh)})];gd=id}fd=gd}var yh=F(fd),zh=t(yh)[1],Xc=[1,ea(mh,nh,zh)[1],Ba]}Vc=Xc}Nc=Vc}Kc=Nc}Cc=Kc}xc=Cc}var jd=xc}else var Ah=Rb[1],jd=Fa(m(function(){var a=l(Ah)[2];return l(a)}),Ue);ga=jd}var kd=ga}else kd=Fa(m(function(){var b=x(a),d=x(s);return[1,b-d|0]}),hb);g=kd}return g}
var Fg=[1,"value"],Gg=m(function(){return C(ya)}),Bh=m(function(){return t(ya)});function Ch(){var a=l(Bh)[1],a=l(w(a)[2]);if(1==a[0])a=l(Gg);else var a=l(a[1])[1],b=l(Fg)[1],a=[1,0,a[b].toString()],d=a[2],a=[1,a[1],m(function(){return u(l([1,d])[1])})];return a}function Dh(){var a=Ch();return Eg(a[2])}var Eh=m(function(){return u("analyzeButton")}),Fh=m(function(){return C(Eh)}),Gh=m(function(){return t(Eh)});function Hh(a,b){var d=l(a)[1];13==l(d)?(d=Ch(),d=Eg(d[2])):d=[1,b,Ba];return d}
var Ih=m(function(){return C(ya)});function Jh(){var a=l(Gh)[1],a=l(w(a)[2]);1==a[0]?a=l(Fh):(a=l(a[1])[1],xa(a,fa,Dh),a=l(za)[1],a=l(w(a)[2]),1==a[0]?a=l(Ih):(a=l(a[1])[1],a=xa(a,ha,Hh)));return a}window.onload=function(){l(l(Jh)(0))};
