var d=void 0,g=!0,i=!1;function k(a){return a instanceof ba?(a.a&&(a.x=a.a(),a.a=0),a.x):a}function m(a){return new ba(a)}function ba(a){this.a=a}function n(a,b){function c(){var c=b.concat(Array.prototype.slice.call(arguments));return n(a,c)}a=a instanceof ba?k(a):a;if(!a.apply)return a;var e=a.arity?a.arity:a.length;if(b.length===e)return a.apply(null,b);if(b.length>e)return e=b.splice(0,e),n(a.apply(null,e),b);c.arity=e-b.length;return c}function t(a){throw u(a)[1];}
function v(a){return x(a,[1])}function x(a,b,c){var e=c?c:0;return e>=a.length?k(b):[2,[1,a.charAt(e)],m(function(){return x(a,b,e+1)})]}function u(a){for(var a=k(a),b="";2==a[0];)a=ca(a),b+=a[0],a=a[1];return[1,b]}function ca(a){var b=k(a[1])[1];if("\\"==b){var c="",a=k(a[2]);if(1==a)return["\\",a];for(b=k(a[1])[1];"0"<=b&&"9">=b;)c+=b,a=k(a[2]),b=k(a[1])[1];if(0==c.length)return["\\",a];b=String.fromCharCode(Number(c));return[b,a]}return[b,k(a[2])]}
function da(a,b,c){return a.addEventListener?(a.addEventListener(b,c,i),[1,0,g]):a.attachEvent?(a.attachEvent("on"+b,c),[1,0,g]):[1,0,i]}function ea(a){return[1,0,65<=a&&90>=a||97<=a&&122>=a||229==a||228==a||246==a||197==a||196==a||214==a]}function fa(a,b,c){a[b]=c;return[1,0]}function y(a){return(a=document.getElementById(a))?[1,0,[2,[1,a]]]:[1,0,[1]]}
var ga=[9,d],ha=[13,d],ia=[1,"load"],ja=[1,"mousemove"],ka=[1,"mouseover"],la=[1,"mouseout"],ma=[1,"click"],na=[1,"dblclick"],oa=[1,"mousedown"],pa=[1,"mouseup"],qa=[1,"keypress"],ra=[1,"keyup"],sa=[1,"keydown"],ta=[1,"unload"],ua=[1,"change"],wa=[1,"focus"],xa=[1,"blur"];
function ya(a,b,c){function e(b){k(c);"change"==b&&"text"==a.type.toLowerCase()&&da(a,"keyup",args);var e;switch(b){case "click":case "dblclick":case "mouseup":case "mousedown":e=function(a){n(c,[[1,a.button],0])};break;case "keypress":case "keyup":case "keydown":e=function(a){n(c,[[1,a.keyCode],0])};break;default:e=function(){n(c,[0])}}var b=da(a,b,e),f=b[2];return[1,b[1],m(function(){return k(f)?g:i})]}switch(k(b)[0]){case 1:var b=k(ia)[1],f=e(b);break;case 2:b=k(ta)[1];f=e(b);break;case 3:b=k(ua)[1];
f=e(b);break;case 4:b=k(wa)[1];f=e(b);break;case 5:b=k(xa)[1];f=e(b);break;case 6:b=k(ja)[1];f=e(b);break;case 7:b=k(ka)[1];f=e(b);break;case 8:b=k(la)[1];f=e(b);break;case 9:b=k(ma)[1];f=e(b);break;case 10:b=k(na)[1];f=e(b);break;case 11:b=k(oa)[1];f=e(b);break;case 12:b=k(pa)[1];f=e(b);break;case 13:b=k(qa)[1];f=e(b);break;case 14:b=k(ra)[1];f=e(b);break;case 15:b=k(sa)[1],f=e(b)}return f}var za=m(function(){return v("formulaInput")}),Aa=m(function(){return u(za)});
function z(a){for(var b=0;;){a=k(a);if(1==a[0])return k(b);b=b+1|0;a=a[2]}}function A(a,b){for(;;){var c=k(b);if(1==c[0])var e=[1];else if(e=c[1],c=c[2],n(a,[e]))e=[2,e,function(a,b){return m(function(){return A(a,b)})}(a,c)];else{b=c;continue}return e}}var Ba=[1];function B(a,b){var c=k(a);if(1==c[0])c=k(b);else var e=c[2],c=[2,c[1],m(function(){return B(e,b)})];return c}var Ca=[1,"-"];
function Da(a,b){for(;;){if(10>a)return[2,[1,String.fromCharCode(48+a|0)],b];var c=[2,[1,String.fromCharCode(48+a%10|0)],b],a=(a-a%10)/10,b=c}}function Ea(a,b){if(0>a)var c=k(a),e=-2147483648==c?[2,Ca,m(function(){return Da(214748364,m(function(){return Da(8,b)}))})]:[2,Ca,m(function(){return Da(-c,b)})];else e=Da(a,b);return e}var C=[1];
function Fa(a,b){var c=x("error at character ",m(function(){var c=k(a)[1],f=m(function(){return x(": ",b)}),c=Ea(c,C);return B(c,f)})),c=u(c)[1];"undefined"!=typeof alert?alert(c):print(c);return[1,0,Ba]}var Ga=m(function(){return v(" could be found!")});function D(a){var b=x("No element with ID ",m(function(){return B(a,Ga)}));return t(b)}
var Ha=m(function(){return v("sdnfCode")}),Ia=m(function(){return D(Ha)}),Ja=m(function(){return v("nnfCode")}),Ka=m(function(){return D(Ja)}),La=m(function(){return v("simplifiedCode")}),Ma=m(function(){return D(La)}),Na=m(function(){return v("innerHTML")}),Oa=m(function(){return u(Na)}),Pa=m(function(){return u(La)}),Qa=m(function(){return u(Na)}),Ra=m(function(){return u(Ja)}),Sa=m(function(){return u(Na)}),Ta=m(function(){return u(Ha)}),Ua=m(function(){return u(Na)}),Va=m(function(){return v("dnfCode")}),
Wa=m(function(){return u(Va)}),Xa=m(function(){return u(Na)}),Ya=m(function(){return v("scnfCode")}),Za=m(function(){return u(Ya)}),$a=m(function(){return u(Na)}),ab=m(function(){return v("cnfCode")}),bb=m(function(){return u(ab)}),cb=m(function(){return v("eof")}),db=m(function(){return x("tokenizer: ",cb)}),eb=m(function(){return D(ab)}),fb=m(function(){return D(Ya)}),gb=m(function(){return D(Va)});function hb(a){return 5==k(a)[0]?g:i}function ib(a){return 6==k(a)[0]?g:i}
var jb=[1,")"],kb=[2,jb,C],lb=[1,"("],E=[2],mb=m(function(){return F(E)}),G=[1],nb=m(function(){return F(G)}),ob=[2,jb,C];function pb(){return i}var qb=[2,[1,"0"],C],rb=[2,[1,"1"],C],sb=[2,jb,C],tb=[1,"!"];function ub(a,b){var c=k(b);switch(c[0]){case 1:var e=k(nb);break;case 2:e=k(mb);break;case 3:e=F(c);break;case 4:e=F(c);break;default:e=n(a,[c])?F(c):[2,lb,m(function(){var a=F(c);return B(a,sb)})]}return e}
function F(a){a=k(a);switch(a[0]){case 1:var b=k(rb);break;case 2:b=k(qb);break;case 3:b=k(a[1]);break;case 4:var c=a[1],b=[2,tb,m(function(){return ub(pb,c)})];break;case 5:var e=a[2],b=m(function(){return x(" ^ ",m(function(){return ub(hb,e)}))}),f=k(a[1]);switch(f[0]){case 1:b=B(nb,b);break;case 2:b=B(mb,b);break;case 3:a=F(f);b=B(a,b);break;case 4:a=F(f);b=B(a,b);break;case 5:a=F(f);b=B(a,b);break;default:b=B([2,lb,m(function(){var a=F(f);return B(a,sb)})],b)}break;case 6:var h=a[2],b=m(function(){return x(" v ",
m(function(){return ub(ib,h)}))}),j=k(a[1]);switch(j[0]){case 1:b=B(nb,b);break;case 2:b=B(mb,b);break;case 3:a=F(j);b=B(a,b);break;case 4:a=F(j);b=B(a,b);break;case 6:a=F(j);b=B(a,b);break;default:b=B([2,lb,m(function(){var a=F(j);return B(a,sb)})],b)}break;case 7:var o=a[1],r=a[2],b=[2,lb,m(function(){var a=m(function(){return x(") -> (",m(function(){var a=F(r);return B(a,ob)}))}),b=F(o);return B(b,a)})];break;case 8:var q=a[1],w=a[2],b=[2,lb,m(function(){var a=m(function(){return x(") <-> (",m(function(){var a=
F(w);return B(a,kb)}))}),b=F(q);return B(b,a)})]}return b}
function vb(a){var b=wb,a=k(a);switch(a[0]){case 1:var c=[1];break;case 2:c=[2];break;case 3:c=[3,a[1]];break;case 4:var e=a[1],c=[4,m(function(){return n(b,[e])})];break;case 5:var f=a[1],h=a[2],c=[5,m(function(){return n(b,[f])}),m(function(){return n(b,[h])})];break;case 6:var j=a[1],o=a[2],c=[6,m(function(){return n(b,[j])}),m(function(){return n(b,[o])})];break;case 7:var r=a[1],q=a[2],c=[7,m(function(){return n(b,[r])}),m(function(){return n(b,[q])})];break;case 8:var w=a[1],p=a[2],c=[8,m(function(){return n(b,
[w])}),m(function(){return n(b,[p])})]}return c}function wb(a){return vb(a)}
function H(a,b){return n(a,[m(function(){var c=k(b);switch(c[0]){case 1:var e=[1];break;case 2:e=[2];break;case 3:e=k(c);break;case 4:var f=c[1],e=[4,m(function(){return H(a,f)})];break;case 5:var h=c[1],j=c[2],e=[5,m(function(){return H(a,h)}),m(function(){return H(a,j)})];break;case 6:var o=c[1],r=c[2],e=[6,m(function(){return H(a,o)}),m(function(){return H(a,r)})];break;case 7:var q=c[1],w=c[2],e=[7,m(function(){return H(a,q)}),m(function(){return H(a,w)})];break;case 8:var p=c[1],s=c[2],e=[8,
m(function(){return H(a,p)}),m(function(){return H(a,s)})]}return e})])}function I(a,b){var c=k(a);if(5==c[0])var e=c[1],f=c[2],h=[5,m(function(){return I(b,e)}),m(function(){return I(b,f)})];else if(h=k(b),5==h[0])var j=h[1],o=h[2],h=[5,m(function(){return I(c,j)}),m(function(){return I(c,o)})];else h=[6,c,h];return h}
function xb(a){a=k(a);if(6==a[0]){var b=a[2],c=k(a[1]);if(5==c[0])var e=c[1],f=c[2],a=[5,m(function(){return I(b,e)}),m(function(){return I(b,f)})];else{var h=k(b);if(5==h[0])var j=h[1],o=h[2],a=[5,m(function(){return I(c,j)}),m(function(){return I(c,o)})];else a=k(a)}}else a=k(a);return a}function yb(a){return vb(m(function(){return H(xb,a)}))}
function J(a,b){var c=k(a);if(6==c[0])var e=c[1],f=c[2],h=[6,m(function(){return J(b,e)}),m(function(){return J(b,f)})];else if(h=k(b),6==h[0])var j=h[1],o=h[2],h=[6,m(function(){return J(c,j)}),m(function(){return J(c,o)})];else h=[5,c,h];return h}
function zb(a){a=k(a);if(5==a[0]){var b=a[2],c=k(a[1]);if(6==c[0])var e=c[1],f=c[2],a=[6,m(function(){return J(b,e)}),m(function(){return J(b,f)})];else{var h=k(b);if(6==h[0])var j=h[1],o=h[2],a=[6,m(function(){return J(c,j)}),m(function(){return J(c,o)})];else a=k(a)}}else a=k(a);return a}function Ab(a){return vb(m(function(){return H(zb,a)}))}
function K(a){a=k(a);switch(a[0]){case 5:var b=a[1],c=a[2],a=[6,m(function(){return K(b)}),m(function(){return K(c)})];break;case 6:var e=a[1],f=a[2],a=[5,m(function(){return K(e)}),m(function(){return K(f)})];break;default:a=[4,a]}return a}
function Bb(a){a=k(a);if(4==a[0]){var b=k(a[1]);switch(b[0]){case 5:var c=b[1],e=b[2],a=[6,m(function(){return K(c)}),m(function(){return K(e)})];break;case 6:var f=b[1],h=b[2],a=[5,m(function(){return K(f)}),m(function(){return K(h)})];break;default:a=k(a)}}else a=k(a);return a}function Cb(a){a=k(a);if(4==a[0])var b=k(a[1]),a=4==b[0]?k(b[1]):k(a);else a=k(a);return a}function Db(a){return vb(m(function(){return H(Cb,m(function(){return H(Bb,a)}))}))}
function Eb(a){var b=k(a);switch(b[0]){case 7:a=[6,[4,b[1]],b[2]];break;case 8:a=b[1];b=b[2];a=[5,[6,[4,a],b],[6,[4,b],a]];break;default:a=k(b)}return a}function Fb(a){return vb(m(function(){return H(Eb,a)}))}function Gb(a){a=k(a)[1];return k(a)}function L(a,b){var c=k(b);if(1==c[0])c=[1];else var e=c[1],f=c[2],c=[2,m(function(){return n(a,[e])}),m(function(){return L(a,f)})];return c}function Hb(a){return L(Gb,a)}
function Ib(a,b){var c=k(a);if(1==c[0])var e=[1];else{var e=c[1],f=c[2],c=k(b);if(1==c[0])e=[1];else var h=c[2],e=[2,[1,e,c[1]],m(function(){return Ib(f,h)})]}return e}function Jb(a,b,c){c=k(c);if(1==c[0])c=[1];else var e=c[1],f=c[2],c=n(a,[b,e])?k(f):[2,e,m(function(){return Jb(a,b,f)})];return c}function M(a){a=k(a)[1];return k(a)}function Kb(a,b,c){return Jb(m(function(){return M(a)}),b,c)}
function Lb(a,b,c){a:{for(;;){c=k(c);if(1==c[0]){a=k(b);break a}var e=c[2],b=Kb(a,c[1],b),c=e}a=d}return a}var Mb=m(function(){return v("List.maximumBy: empty list")}),Nb=m(function(){return t(Mb)});function N(a,b,c){for(;;){c=k(c);if(1==c[0])a=i;else{var e=c[2];if(n(M,[a,b,c[1]]))a=g;else{c=e;continue}}return a}}
function O(a,b){function c(b,f){for(var h;;){var j=k(b);if(1==j[0])h=[1];else if(h=j[1],j=j[2],N(a,h,f)){b=j;continue}else h=[2,h,function(a,b,c,e){return m(function(){return e(c,[2,a,b])})}(h,f,j,c)];return h}}return c(b,C)}function Ob(a){a=k(a)[2];return k(a)}function Pb(a,b){var c=k(a)[1],e=k(b)[1];return c==e}var P=[1,Pb,function(a,b){var c=k(a)[1],e=k(b)[1];return c!=e}];
function Qb(a,b){return[1,function(c,e){var f=k(a)[1],h=k(c),j=h[1],h=h[2],o=k(e);return n(f,[j,o[1]])?n(M,[b,h,o[2]]):i},function(c,e){var f=k(a)[1],h=k(c),j=h[1],h=h[2],o=k(e);return n(f,[j,o[1]])?n(M,[b,h,o[2]])?i:g:g}]}function Rb(a,b,c){for(;;){var e=k(b);if(1==e[0])a=1==k(c)[0]?g:i;else{var b=e[1],e=e[2],f=k(c);if(1==f[0])a=i;else if(c=f[2],n(M,[a,b,f[1]])){b=e;continue}else a=i}return a}}function Sb(a,b,c){return Rb(a,b,c)?i:g}
function Tb(a){return[1,function(b,c){return Rb(a,b,c)},function(b,c){return Sb(a,b,c)}]}
var Ub=m(function(){return Tb(P)}),Vb=[1,function(a,b){switch(k(a)[0]){case 1:switch(k(b)[0]){case 1:var c=g;break;case 2:c=i;break;case 3:c=i}var e=c;break;case 2:e=2==k(b)[0]?g:i;break;case 3:e=3==k(b)[0]?g:i}return e},function(a,b){switch(k(a)[0]){case 1:switch(k(b)[0]){case 1:var c=i;break;case 2:c=g;break;case 3:c=g}var e=c;break;case 2:e=2==k(b)[0]?i:g;break;case 3:e=3==k(b)[0]?i:g}return e}],Wb=m(function(){return Tb(Vb)}),Q=m(function(){return Qb(Wb,Ub)});
function Xb(a){var b=m(function(){return[1,z(a)]});return n(A,[function(c){var e;a:{e=function(a){return N(Q,a,c)};for(var f=a;;){f=k(f);if(1==f[0])e=g;else{var h=f[2];if(n(e,[f[1]])){f=h;continue}else e=i}break a}e=d}e?(e=k(b)[1],f=z(c),e=e<f?i:g):e=g;return e}])}function Yb(a){return O(Q,a)}var Zb=m(function(){return Tb(Q)});function $b(a){function b(a){a=k(a);if(1==a[0])a=k(c);else var f=a[2],a=n(Xb,[a[1],m(function(){return b(f)})]);return a}var a=L(Yb,a),c=O(Zb,a);return b(c)}
function ac(a,b){function c(b,f){for(;;){var h=k(f);if(1==h[0])h=[1];else{var j=h[2];if(n(a,[h[1]]))h=[2,[1,b],function(a,b,c){return m(function(){return b(a+1|0,c)})}(b,c,j)];else{b=b+1|0;f=j;continue}}return h}}return c(0,b)}var bc=m(function(){return v("Prelude.(!!): negative index\n")}),cc=m(function(){return t(bc)}),dc=m(function(){return v("Prelude.(!!): index too large\n")}),ec=m(function(){return t(dc)}),fc=m(function(){return v(": empty list")}),gc=m(function(){return v("Prelude.")});
function hc(a){var b=B(gc,m(function(){return B(a,fc)}));return t(b)}var ic=m(function(){return v("head")}),R=m(function(){return hc(ic)});function jc(a){a=k(a);if(1==a[0])a=[1];else var b=a[2],a=B(a[1],m(function(){return jc(b)}));return a}function kc(a){a=k(a);if(1==a[0])a=[1];else var b=a[2],a=k(a[1])[2],a=B(a,m(function(){return kc(b)}));return a}function lc(a){for(var b=0;;){var c=k(a);if(1==c[0])return k(b);a=c[2];c=k(c[1])[1];b=b+c|0}}function mc(a){return 3==k(a)[0]?g:i}
function nc(a){a=k(a)[1];a=ac(mc,a);return[1,z(a)]}function oc(a,b){for(;;){var c=k(b);if(1==c[0])return k(a);var e=c[1],c=c[2],f=L(nc,a),f=lc(f),h=L(nc,e),h=lc(h);f<h?a=e:f==h&&(a=e);b=c}}
function pc(a,b,c){return B(b,m(function(){function e(b,c){for(var f;;){var j=k(b);if(1==j[0])f=[1];else{f=j[1];var j=j[2],h;a:{h=a;for(var s=f,l=c;;){l=k(l);if(1==l[0])h=i;else{var aa=l[2];if(n(h,[s,l[1]]))h=g;else{l=aa;continue}}break a}h=d}if(h){b=j;continue}else f=[2,f,function(a,b,c,e){return m(function(){return e(c,[2,a,b])})}(f,c,j,e)]}return f}}var f;a:{f=e(c,C);for(var h=b;;){h=k(h);if(1==h[0]){f=k(f);break a}var j=h[2];f=Jb(a,h[1],f);h=j}f=d}return f}))}
function qc(a,b,c,e){var f=k(c);if(1==f[0])e=k(b);else{var c=f[1],h=f[2],e=k(e);if(1==e[0])e=k(b);else var j=e[2],e=n(a,[c,e[1],m(function(){return qc(a,b,h,j)})])}return e}function rc(a){a=k(a)[2];return k(a)}function sc(a,b){for(var c;;){c=k(b);if(1==c[0])c=g;else{var e=c[2];if(n(rc,[Q,a,c[1]])){b=e;continue}else c=i}return c}}
function tc(a,b,c){b=k(b);if(1==b[0])c=[1];else{var e=b[1],f=b[2],c=k(c);if(1==c[0])c=[1];else var h=c[1],j=c[2],c=[2,m(function(){return n(a,[e,h])}),m(function(){return tc(a,f,j)})]}return c}function uc(a,b){switch(k(a)[0]){case 1:switch(k(b)[0]){case 1:var c=[1];break;case 2:c=[3];break;case 3:c=[3]}var e=c;break;case 2:e=2==k(b)[0]?[2]:[3];break;case 3:k(b),e=[3]}return e}
function vc(a,b,c){switch(k(a)[0]){case 1:switch(k(b)[0]){case 1:var e=k(c);break;case 2:e=[2,i,c];break;case 3:e=[2,i,c]}var f=e;break;case 2:f=2==k(b)[0]?k(c):[2,i,c];break;case 3:f=3==k(b)[0]?k(c):[2,i,c]}return f}
function wc(a,b,c,e){b=k(b);if(1==b[0]){var f=k(e);if(1==f[0])e=B(a,c),e=O(Q,e);else var h=m(function(){return B(a,c)}),j=f[2],o=k(f[1]),r=o[1],q=o[2],w=m(function(){var a=m(function(){return ac(mc,r)});return A(function(b){var b=k(b)[1],c=ac(mc,b);Rb(P,a,c)?(b=qc(vc,C,r,b),b=1==z(b)?g:i):b=i;return b},j)}),e=B(C,m(function(){return L(function(a){var a=k(a),b=a[1],c=a[2];return[1,m(function(){return tc(uc,r,b)}),m(function(){return pc(Pb,q,c)})]},w)})),e=wc(m(function(){return 1==k(w)[0]?N(Q,o,f)?
[2,o,h]:k(h):k(h)}),j,m(function(){var a=k(w);if(1==a[0])a=k(f);else var b=[2,o,a],a=A(function(a){return sc(a,b)},f);return a}),e)}else var p=b[2],s=k(b[1]),l=s[1],aa=s[2],va=m(function(){var a=m(function(){return ac(mc,l)});return A(function(b){var b=k(b)[1],c=ac(mc,b);Rb(P,a,c)?(b=qc(vc,C,l,b),b=1==z(b)?g:i):b=i;return b},p)}),e=B(e,m(function(){return L(function(a){var a=k(a),b=a[1],c=a[2];return[1,m(function(){return tc(uc,l,b)}),m(function(){return pc(Pb,aa,c)})]},va)})),e=wc(m(function(){return 1==
k(va)[0]?N(Q,s,c)?[2,s,a]:k(a):k(a)}),p,m(function(){var a=k(va);if(1==a[0])a=k(c);else var b=[2,s,a],a=A(function(a){return sc(a,b)},c);return a}),e);return e}function xc(a){return[2,[2,[1,a],C],m(function(){var b=k(a);return 2147483647==b?[1]:xc(b+1|0)})]}var yc=m(function(){return xc(0)});function zc(a){return L(Ob,a)}function Ac(a){return k(a)?[1]:[2]}function Bc(a){a=n(zc,[a]);return L(Ac,a)}var Cc=[1];function Dc(a){return k(a)}
function S(a,b,c){c=k(c);switch(c[0]){case 1:var e=n(a,[G,b]);break;case 2:e=n(a,[E,b]);break;case 3:e=n(a,[c,b]);break;case 4:var f=c[1],e=n(a,[c,m(function(){return S(a,b,f)})]);break;case 5:var h=c[1],j=c[2],e=n(a,[c,m(function(){return S(a,m(function(){return S(a,b,j)}),h)})]);break;case 6:var o=c[1],r=c[2],e=n(a,[c,m(function(){return S(a,m(function(){return S(a,b,r)}),o)})]);break;case 7:var q=c[1],w=c[2],e=n(a,[c,m(function(){return S(a,m(function(){return S(a,b,w)}),q)})]);break;case 8:var p=
c[1],s=c[2],e=n(a,[c,m(function(){return S(a,m(function(){return S(a,b,s)}),p)})])}return e}var Ec=m(function(){return v("foldl1")}),Fc=m(function(){return hc(Ec)});function Gc(a,b,c){a:{for(;;){c=k(c);if(1==c[0]){a=k(b);break a}var e=c[2],b=function(a,b,c){return m(function(){return n(c,[a,b])})}(b,c[1],a),c=e}a=d}return a}function T(a,b,c){c=k(c);if(1==c[0])b=k(b);else var e=c[1],f=c[2],b=n(a,[b,m(function(){return T(a,e,f)})]);return b}
var Hc=m(function(){return v("foldr1")}),Ic=m(function(){return hc(Hc)}),Jc=[1,function(a,b){function c(a){a=k(a);if(1==a[0])a=k(f);else var b=a[2],a=n(h,[a[1],m(function(){return c(b)})]);return a}var e=k(a),f=e[1],h=e[2];return c(b)},function(a,b,c){function e(a){a=k(a);if(1==a[0])a=k(f);else var c=a[1],r=a[2],a=n(h,[m(function(){return n(b,[c])}),m(function(){return e(r)})]);return a}var a=k(a),f=a[1],h=a[2];return e(c)},function(a,b,c){function e(c){c=k(c);if(1==c[0])c=k(b);else var h=c[2],c=
n(a,[c[1],m(function(){return e(h)})]);return c}return e(c)},Gc,function(a,b){var c=k(b);if(1==c[0])var e=k(Ic);else if(e=c[1],c=k(c[2]),1==c[0])e=k(e);else var f=c[1],h=c[2],e=n(a,[e,m(function(){return T(a,f,h)})]);return e},function(a,b){var c=k(b);return 1==c[0]?k(Fc):Gc(a,c[1],c[2])}];function Kc(a){a=k(a)[5];return k(a)}function Lc(a,b){return[5,a,b]}var Mc=m(function(){return n(Kc,[Jc,Lc])});function Nc(a,b){return[6,a,b]}var Oc=m(function(){return n(Kc,[Jc,Nc])});
function Pc(a,b,c){switch(k(b)[0]){case 1:var e=[2,[3,a],c];break;case 2:e=[2,[4,[3,a]],c];break;case 3:e=k(c)}return e}function Qc(a,b,c){c=k(c);if(1==c[0])c=[2,b,C];else var e=c[1],f=c[2],c=3==n(a,[b,e])[0]?[2,e,m(function(){return Qc(a,b,f)})]:[2,b,c];return c}function U(a){a=k(a)[1];return k(a)}function Rc(a){a=k(a)[2];return k(a)}function Sc(a,b,c){return N(m(function(){return U(a)}),b,c)?k(c):Qc(m(function(){return Rc(a)}),b,c)}
function Tc(a,b){for(var c;;){c=k(a);if(1==c[0])c=1==k(b)[0]?g:i;else{var e=c[1];c=c[2];var f=k(b);if(1==f[0])c=i;else{var h=f[1],f=f[2],e=k(e)[1],h=k(h)[1];if(e==h){a=c;b=f;continue}else c=i}}return c}}function Uc(a,b){for(var c;;){c=k(a);if(1==c[0])c=1==k(b)[0]?[2]:[1];else{var e=c[1];c=c[2];var f=k(b);if(1==f[0])c=[3];else{var h=f[1],f=f[2],e=k(e)[1],h=k(h)[1];if(e==h){a=c;b=f;continue}else c=e<=h?[1]:[3]}}return c}}
var Vc=[1,[1,Tc,function(a,b){return Tc(a,b)?i:g}],Uc,function(a,b){return 1==Uc(a,b)[0]?g:i},function(a,b){return 1==Uc(a,b)[0]?i:g},function(a,b){return 3==Uc(a,b)[0]?g:i},function(a,b){return 3==Uc(a,b)[0]?i:g},function(a,b){return 3==Uc(a,b)[0]?k(a):k(b)},function(a,b){return 3==Uc(a,b)[0]?k(b):k(a)}];function Wc(a,b){var c=k(a);return 3==c[0]?n(Sc,[Vc,c[1],b]):k(b)}function Xc(a,b){return A(function(b){return n(a,[m(function(){return Ob(b)})])},b)}function Yc(a){return k(a)}
var Zc=m(function(){return n(Xc,[Yc])}),$c=[1],ad=m(function(){return v("Prelude.undefined")}),bd=m(function(){return t(ad)});function cd(a,b,c,e){var f=m(function(){return U(a)}),e=Jb(function(a,b){return n(M,[f,m(function(){var b=k(a)[1];return k(b)}),m(function(){var a=k(b)[1];return k(a)})])},[1,b,bd],e);return Qc(function(b,c){return n(Rc,[a,m(function(){var a=k(b)[1];return k(a)}),m(function(){var a=k(c)[1];return k(a)})])},[1,b,c],e)}
function dd(a,b){var c=k(a);if(c){var e=k(b);if(1==e[0])e=[1];else var f=e[2],e=[2,e[1],m(function(){return dd(c-1|0,f)})]}else e=[1];return e}function ed(a){a=k(a)[3];return k(a)}function fd(a){a=k(a)[6];return k(a)}function gd(a){a=k(a)[5];return k(a)}function hd(a){a=k(a)[4];return k(a)}
function id(a,b){return[1,m(function(){return Qb(m(function(){return U(a)}),m(function(){return U(b)}))}),function(c,e){var f=k(a)[2],h=k(c),j=h[1],h=h[2],o=k(e),r=o[2];switch(n(f,[j,o[1]])[0]){case 1:var q=[1];break;case 2:q=n(Rc,[b,h,r]);break;case 3:q=[3]}return q},function(c,e){var f=k(a)[2],h=k(c),j=h[1],h=h[2],o=k(e),r=o[2];switch(n(f,[j,o[1]])[0]){case 1:var q=g;break;case 2:q=n(ed,[b,h,r]);break;case 3:q=i}return q},function(c,e){var f=k(a)[2],h=k(c),j=h[1],h=h[2],o=k(e),r=o[2];switch(n(f,
[j,o[1]])[0]){case 1:var q=i;break;case 2:q=n(hd,[b,h,r]);break;case 3:q=g}return q},function(c,e){var f=k(a)[2],h=k(c),j=h[1],h=h[2],o=k(e),r=o[2];switch(n(f,[j,o[1]])[0]){case 1:var q=i;break;case 2:q=n(gd,[b,h,r]);break;case 3:q=g}return q},function(c,e){var f=k(a)[2],h=k(c),j=h[1],h=h[2],o=k(e),r=o[2];switch(n(f,[j,o[1]])[0]){case 1:var q=g;break;case 2:q=n(fd,[b,h,r]);break;case 3:q=i}return q},function(c,e){var f=k(a)[2],h=k(c),j=h[1],h=h[2],o=k(e),r=o[1],o=o[2];switch(n(f,[j,r])[0]){case 1:var q=
[1,r,o];break;case 2:q=n(fd,[b,h,o])?[1,r,o]:[1,j,h];break;case 3:q=[1,j,h]}return q},function(c,e){var f=k(a)[2],h=k(c),j=h[1],h=h[2],o=k(e),r=o[1],o=o[2];switch(n(f,[j,r])[0]){case 1:var q=[1,j,h];break;case 2:q=n(fd,[b,h,o])?[1,j,h]:[1,r,o];break;case 3:q=[1,r,o]}return q}]}function jd(a,b,c){for(;;){var e=k(b);if(1==e[0])a=1==k(c)[0]?[2]:[1];else{var b=e[1],e=e[2],f=k(c);if(1==f[0])a=[3];else if(c=f[2],b=n(Rc,[a,b,f[1]]),2==b[0]){b=e;continue}else a=k(b)}return a}}
function kd(a,b){return[1,m(function(){var c=m(function(){return U(a)}),e=m(function(){return U(b)});return[1,m(function(){return n(Rb,[m(function(){return Qb(c,e)})])}),m(function(){return n(Sb,[m(function(){return Qb(c,e)})])})]}),m(function(){var c=m(function(){return id(a,b)});return k(function(a,b){return jd(c,a,b)})}),function(c,e){return 1==jd(m(function(){return id(a,b)}),c,e)[0]?g:i},function(c,e){return 1==jd(m(function(){return id(a,b)}),c,e)[0]?i:g},function(c,e){return 3==jd(m(function(){return id(a,
b)}),c,e)[0]?g:i},function(c,e){return 3==jd(m(function(){return id(a,b)}),c,e)[0]?i:g},function(c,e){return 3==jd(m(function(){return id(a,b)}),c,e)[0]?k(c):k(e)},function(c,e){return 3==jd(m(function(){return id(a,b)}),c,e)[0]?k(e):k(c)}]}
var ld=[1,[1,function(a,b){return k(a)?k(b):k(b)?i:g},function(a,b){return k(a)?k(b)?i:g:k(b)}],function(a,b){return k(a)?k(b)?[2]:[3]:k(b)?[1]:[2]},function(a,b){if(k(a)){k(b);var c=i}else c=k(b);return c},function(a,b){if(k(a)){k(b);var c=g}else c=k(b)?i:g;return c},function(a,b){if(k(a))var c=k(b)?i:g;else k(b),c=i;return c},function(a,b){if(k(a))var c=k(b);else k(b),c=g;return c},function(a,b){if(k(a)){k(b);var c=g}else c=k(b);return c},function(a,b){if(k(a))var c=k(b);else k(b),c=i;return c}],
md=m(function(){return n(kd,[Vc,ld])}),nd=[2,C,C];function od(a){a=k(a);if(1==a[0])a=[1];else var b=a[2],a=[2,[2,a[1],C],m(function(){return od(b)})];return a}
function pd(a,b){var c=m(function(){var c=k(b);if(1==c[0])c=od(a);else var f=c[1],h=c[2],j=m(function(){return pd(f,h)}),o=function(a){a=k(a);if(1==a[0])a=[1];else var b=a[1],c=a[2],e=m(function(){return o(c)}),f=function(a){a=k(a);if(1==a[0])a=k(e);else var c=a[2],a=[2,[2,b,a[1]],m(function(){return f(c)})];return a},a=f(j);return a},c=o(a);return c});return 1==k(a)[0]?1==k(b)[0]?k(nd):k(c):k(c)}
function qd(a){a=k(a);if(1==a[0])a=[1];else var b=a[1],c=a[2],a=m(function(){var a=k(c);if(1==a[0])a=od(b);else var f=a[1],h=a[2],j=m(function(){return pd(f,h)}),o=function(a){a=k(a);if(1==a[0])a=[1];else var b=a[1],c=a[2],e=m(function(){return o(c)}),f=function(a){a=k(a);if(1==a[0])a=k(e);else var c=a[2],a=[2,[2,b,a[1]],m(function(){return f(c)})];return a},a=f(j);return a},a=o(b);return a}),a=1==k(b)[0]?1==k(c)[0]?k(nd):k(a):k(a);return a}
function rd(a,b,c){a:{for(var e=m(function(){return U(a)});;){var f=k(c);if(1==f[0])b=[1];else{var c=f[2],f=k(f[1]),h=f[2];if(n(M,[e,b,f[1]]))b=[2,h];else continue}break a}b=d}return b}
var sd=m(function(){return v("Maybe.fromJust: Nothing")}),td=m(function(){return t(sd)}),ud=m(function(){return v("Logic.eval.reduce: Impossible")}),vd=m(function(){return t(ud)}),wd=[1,1.605959309876327E19,1.3945565038419476E19,[1,1.605959309876327E19,1.3945565038419476E19,m(function(){return v("base")}),m(function(){return v("Control.Exception.Base")}),m(function(){return v("PatternMatchFail")})],C];function xd(){return k(wd)}
function yd(a){var a=k(a),b=a[2],a=k(a[1])[1],c=k(a),e=m(function(){var a=n(c,[b]),h=a[1],a=a[2],j=n(xd,[m(function(){var a=k(e);return 1==a[0]?k(td):k(a[1])})]),o=j[2];return k(h==j[1])?k(a==o)?[2,b]:[1]:[1]});return k(e)}
var zd=[1,","],Ad=[1,"]"],Bd=[1,"["],Cd=[1,function(a,b,c){a=k(b)[1];return B(a,c)},function(a){a=k(a)[1];return k(a)},function(a,b){var c=k(a);if(1==c[0])c=x("[]",b);else var e=c[1],f=c[2],c=[2,Bd,m(function(){var a=k(e)[1];return B(a,m(function(){function a(b){b=k(b);if(1==b[0])b=k(c);else var e=b[1],f=b[2],b=[2,zd,m(function(){var b=k(e)[1];return B(b,m(function(){return a(f)}))})];return b}var c=[2,Ad,b];return a(f)}))})];return c}],Ed=m(function(){return[1,xd,Cd,Dd,yd]});
function Dd(a){return[1,Ed,a]}var Fd=m(function(){return v("Non-exhaustive patterns in")}),Gd=[1," "],Hd=[2,[1,"\n"],C];function Id(a){a=k(a)[1];return"|"==k(a)?i:g}function Jd(a,b){var c=k(b);if(1==c[0])c=[1,C,C];else{var e=c[1],f=c[2];if(n(a,[e]))var h=m(function(){var b=Jd(a,f);return[1,b[1],b[2]]}),c=[1,[2,e,m(function(){var a=k(h)[1];return k(a)})],m(function(){var a=k(h)[2];return k(a)})];else c=[1,C,c]}return c}
var Kd=m(function(){var a=[1,m(function(){function a(b,c){return B(b,m(function(){return x(": ",m(function(){return B(Fd,m(function(){return B(c,Hd)}))}))}))}var b=v("PropositionalLogic/Logic.hs:(152,11)-(153,26)|function toBool"),f=Jd(Id,b),b=f[1],h=k(f[2]);1==h[0]?b=a(b,C):(f=h[2],h=k(h[1])[1],b="|"==k(h)?a(b,[2,Gd,f]):a(b,C));return b})],b=Dd;throw m(function(){return n(b,[a])});});
function Ld(a,b){switch(H(function(b){b=k(b);switch(b[0]){case 1:var c=[1];break;case 2:c=[2];break;case 3:b=n(rd,[Vc,b[1],a]);c=1==b[0]?k(td):k(b[1])?[1]:[2];break;case 4:switch(k(b[1])[0]){case 1:b=[2];break;case 2:b=[1];break;default:b=k(vd)}c=b;break;case 5:c=b[2];switch(k(b[1])[0]){case 1:switch(k(c)[0]){case 1:b=[1];break;case 2:b=[2];break;default:b=k(Kd)}break;case 2:b=[2];break;default:b=k(Kd)}c=b;break;case 6:c=b[2];switch(k(b[1])[0]){case 1:b=[1];break;case 2:switch(k(c)[0]){case 1:b=[1];
break;case 2:b=[2];break;default:b=k(Kd)}break;default:b=k(Kd)}c=b;break;case 7:c=Ld(a,[6,[4,b[1]],b[2]])?[1]:[2];break;case 8:c=b[1],b=b[2],c=Ld(a,[5,[6,[4,c],b],[6,[4,b],c]])?[1]:[2]}return c},b)[0]){case 1:var c=g;break;case 2:c=i;break;default:c=k(Kd)}return c}function Md(a,b){return[2,[1,a,b],C]}function Nd(a,b,c){var e=m(function(){return U(a)});return pc(function(a,b){return n(M,[e,m(function(){var b=k(a)[1];return k(b)}),m(function(){var a=k(b)[1];return k(a)})])},b,c)}
var Od=m(function(){return n(Nd,[Vc])});function Pd(a,b,c){return n(Od,[m(function(){return n(Md,[a,b])}),c])}var Qd=m(function(){return qd(C)}),Rd=[2,g,[2,i,C]],Sd=m(function(){return[2,Rd,Sd]});
function Td(a){function b(a){for(;;){var c=k(a);if(1==c[0])a=[1];else if(a=c[2],c=qc(Pc,C,j,c[1]),1==c[0])continue;else a=[2,c,function(a,b){return m(function(){return b(a)})}(a,b)];return a}}function c(a){for(;;){var b=k(a);if(1==b[0])a=[1];else if(a=b[2],b=ac(function(a){return function(b){b=Ob(b);return N(P,a,b)}}(b[1]),f),1==z(b))a=[2,function(a,b){return m(function(){var c=k(b);if(1==c[0])c=k(R);else if(c=k(c[1])[1],0>c)c=k(cc);else a:{for(var e=a;;){var f=k(e);if(1==f[0])c=k(ec);else if(e=f[1],
f=f[2],c=k(c)){c=c-1|0;e=f;continue}else c=k(e);break a}c=d}return c})}(f,b),function(a,b){return m(function(){return b(a)})}(a,c)];else continue;return a}}var e=n(Hb,[m(function(){return n(Zc,[m(function(){function b(e){e=k(e);if(1==e[0])e=k($c);else var f=e[1],h=e[2],j=m(function(){return qc(Pd,$c,c,f)}),e=n(cd,[md,j,m(function(){return Ld(j,a)}),m(function(){return b(h)})]);return e}var c=n(Dc,[m(function(){return S(Wc,Cc,a)})]),e=z(c);0>=e?e=b(Qd):0<=e?(e=dd(e,Sd),e=qd(e),e=b(e)):e=b(Qd);return e})])})]),
e=L(Bc,e),e=Ib(e,yc),f=wc(C,e,e,C),h,e=L(Ob,f),e=jc(e),e=O(P,e),e=c(e);h=O(Q,e);var e=B(h,m(function(){function a(b,c){var e;a:{e=b;for(var f=c;;){var j=k(f);if(1==j[0]){e=k(e);break a}var f=j[1],j=j[2],h=z(e),r=z(f);h<r||h!=r&&(e=f);f=j}e=d}var q=z(e);e=z(b);f=m(function(){function a(b){var c=k(b);if(1==c[0])b=[1,C,C];else var b=c[1],e=c[2],c=z(b),f=m(function(){var b=a(e);return[1,b[1],b[2]]}),b=q==c?[1,[2,b,m(function(){var a=k(f)[1];return k(a)})],m(function(){var a=k(f)[2];return k(a)})]:[1,
m(function(){var a=k(f)[1];return k(a)}),[2,b,m(function(){var a=k(f)[2];return k(a)})]];return b}var b=a(c);return[1,b[1],b[2]]});q==e?(e=k(f)[1],e=oc(b,e)):(e=k(f)[1],e=k(e),e=1==e[0]?k(Nb):oc(e[1],e[2]));return e}function b(a){a=k(a);if(1==a[0])a=[1];else var e=a[1],f=a[2],a=[2,m(function(){function a(b){for(;;){var c=k(b);if(1==c[0])b=[1];else{var b=c[1],c=c[2],f=Ob(b);if(N(P,e,f))b=[2,[2,b,C],function(a,b){return m(function(){return b(a)})}(c,a)];else{b=c;continue}}return b}}return a(c)}),m(function(){return b(f)})];
return a}var c=Lb(Q,f,h),e=kc(c),e=O(P,e),e=b(e);if(1==e[0])e=[1];else{var j=e[1],l=k(e[2]);if(1==l[0])e=k(j);else{var o=l[1];a:{e=m(function(){function a(b){b=k(b);if(1==b[0])b=[1];else var c=b[1],e=b[2],f=m(function(){return a(e)}),j=function(a){a=k(a);if(1==a[0])a=k(f);else var b=a[1],e=a[2],a=[2,m(function(){return B(c,b)}),m(function(){return j(e)})];return a},b=j(o);return b}var b=a(j);return $b(b)});for(l=l[2];;){l=k(l);if(1==l[0]){e=k(e);break a}var va=l[2],e=function(a,b){return m(function(){function c(a){a=
k(a);if(1==a[0])a=[1];else var e=a[1],f=a[2],j=m(function(){return c(f)}),h=function(a){a=k(a);if(1==a[0])a=k(j);else var b=a[1],c=a[2],a=[2,m(function(){return B(e,b)}),m(function(){return h(c)})];return a},a=h(b);return a}var e=c(a);return $b(e)})}(e,l[1]),l=va}e=d}}e=1==e[0]?[1]:a(e[1],e[2])}return e})),e=L(Gb,e),j=m(function(){return n(Dc,[m(function(){return S(Wc,Cc,a)})])}),o=b(e);return 1==o[0]?[1]:n(Oc,[m(function(){return L(Mc,o)})])}
var Ud=[4,G],Vd=[2,E,[2,Ud,C]],Wd=[4,E],Xd=[2,G,[2,Wd,C]],Yd=m(function(){return n(Kc,[Jc,Nc])});function Zd(a,b){for(;;){var c=k(b);if(1==c[0])c=i;else{var e=c[2];if(n(a,[c[1]]))c=g;else{b=e;continue}}return c}}function $d(a){for(var b=C;;){a=k(a);if(1==a[0])return k(b);b=[2,a[1],b];a=a[2]}}
function V(a,b){for(var c;;){c=function(a,b){return m(function(){switch(k(a)[0]){case 1:switch(k(b)[0]){case 1:var c=g;break;case 2:c=i;break;case 3:c=i;break;case 4:c=i;break;case 5:c=i;break;case 6:c=i;break;case 7:c=i;break;case 8:c=i}var e=c;break;case 2:switch(k(b)[0]){case 1:var f=i;break;case 2:f=g;break;case 3:f=i;break;case 4:f=i;break;case 5:f=i;break;case 6:f=i;break;case 7:f=i;break;case 8:f=i}e=f;break;case 3:switch(k(b)[0]){case 3:c=g;break;case 4:c=i;break;case 5:c=i;break;case 6:c=
i;break;case 7:c=i;break;case 8:c=i;break;default:c=i}e=c;break;case 4:switch(k(b)[0]){case 3:c=i;break;case 4:c=g;break;case 5:c=i;break;case 6:c=i;break;case 7:c=i;break;case 8:c=i;break;default:c=i}e=c;break;case 5:switch(k(b)[0]){case 3:c=i;break;case 4:c=i;break;case 5:c=g;break;case 6:c=i;break;case 7:c=i;break;case 8:c=i;break;default:c=i}e=c;break;case 6:switch(k(b)[0]){case 3:c=i;break;case 4:c=i;break;case 5:c=i;break;case 6:c=g;break;case 7:c=i;break;case 8:c=i;break;default:c=i}e=c;break;
case 7:switch(k(b)[0]){case 3:c=i;break;case 4:c=i;break;case 5:c=i;break;case 6:c=i;break;case 7:c=g;break;case 8:c=i;break;default:c=i}e=c;break;case 8:switch(k(b)[0]){case 3:c=i;break;case 4:c=i;break;case 5:c=i;break;case 6:c=i;break;case 7:c=i;break;case 8:c=g;break;default:c=i}e=c}return e})}(a,b);var e=k(a);switch(e[0]){case 3:var f=e[1],e=k(b);if(3==e[0])a:{c=f;f=e[1];for(e=d;;){c=k(c);if(1==c[0])c=1==k(f)[0]?g:i;else if(e=c[1],c=c[2],f=k(f),1==f[0])c=i;else{var h=f[1],f=f[2],e=k(e)[1],h=
k(h)[1];if(e==h)continue;else e=i;c=e}break a}c=d}else c=k(c);break;case 4:e=e[1];f=k(b);if(4==f[0]){c=f[1];a=e;b=c;continue}else c=k(c);break;case 5:f=e[1];e=e[2];h=k(b);if(5==h[0])if(c=h[2],V(f,h[1])){a=e;b=c;continue}else c=i;else c=k(c);break;case 6:f=e[1];e=e[2];h=k(b);if(6==h[0])if(c=h[2],V(f,h[1])){a=e;b=c;continue}else c=i;else c=k(c);break;case 7:f=e[1];e=e[2];h=k(b);if(7==h[0])if(c=h[2],V(f,h[1])){a=e;b=c;continue}else c=i;else c=k(c);break;case 8:f=e[1];e=e[2];h=k(b);if(8==h[0])if(c=h[2],
V(f,h[1])){a=e;b=c;continue}else c=i;else c=k(c);break;default:c=k(c)}return c}}var ae=[1,V,function(a,b){return V(a,b)?i:g}];
function be(a,b,c){if(Zd(function(a){return N(ae,a,c)},a))var e=[2,m(function(){var b=k(a);return 1==b[0]?k(R):k(b[1])}),C];else{var f=m(function(){return $d(c)}),h=function(a){a=k(a);if(1==a[0])a=i;else{var b=a[1],c=a[2],a=m(function(){return h(c)}),e=k(f);if(1==e[0])a=k(a);else{var w=e[1],p=e[2],s=m(function(){var a=k(w);if(4==a[0])a=V(b,a[1]);else var c=k(b),a=4==c[0]?V(c[1],a):i;return a}),e=k(b);switch(e[0]){case 1:if(2==k(w)[0])a=g;else if(k(s))a=g;else a:{for(e=p;;){p=k(e);if(1==p[0])a=k(a);
else switch(e=p[2],p=k(p[1]),p[0]){case 2:a=g;break;case 4:if(V(G,p[1]))a=g;else continue;break;default:continue}break a}a=d}break;case 2:if(1==k(w)[0])a=g;else if(k(s))a=g;else a:{for(e=p;;){p=k(e);if(1==p[0])a=k(a);else switch(e=p[2],p=k(p[1]),p[0]){case 1:a=g;break;case 4:if(V(E,p[1]))a=g;else continue;break;default:continue}break a}a=d}break;default:if(k(s))a=g;else a:{for(;;){s=k(p);if(1==s[0])a=k(a);else if(p=s[2],s=k(s[1]),4==s[0])if(V(e,s[1]))a=g;else continue;else{var l=k(e);if(4==l[0])if(V(l[1],
s))a=g;else continue;else continue}break a}a=d}}}}return a};h(c)?e=[2,m(function(){var b=k(a);return 1==b[0]?k(R):k(b[1])}),C]:(e=O(ae,c),e=Lb(ae,e,b),e=1==e[0]?[2,m(function(){var a=k(b);return 1==a[0]?k(R):k(a[1])}),C]:k(e))}return e}function ce(a){return n(Yd,[m(function(){return be(Xd,Vd,a)})])}var de=[2,E,[2,Ud,C]],ee=[2,G,[2,Wd,C]],fe=m(function(){return n(Kc,[Jc,Lc])});
function ge(a){var b=k(a);if(6==b[0])var c=b[2],a=m(function(){return ge(c)}),b=ge(b[1]),a=B(b,a);else a=[2,b,C];return a}function he(a){var b=k(a);switch(b[0]){case 5:var c=b[2],a=m(function(){return he(c)}),e=he(b[1]),a=B(e,a);break;case 6:a=[2,m(function(){return ge(b)}),C];break;default:a=[2,[2,b,C],C]}return a}function ie(a){return n(fe,[m(function(){return be(de,ee,m(function(){var b=he(a);return L(ce,b)}))})])}
var je=[4,E],ke=[2,G,[2,je,C]],le=[4,G],me=[2,E,[2,le,C]],ne=m(function(){return n(Kc,[Jc,Lc])});
function oe(a,b,c){if(Zd(function(a){return N(ae,a,c)},a))var e=[2,m(function(){var b=k(a);return 1==b[0]?k(R):k(b[1])}),C];else{var f=m(function(){return $d(c)}),h=function(a){a=k(a);if(1==a[0])a=i;else{var b=a[1],c=a[2],a=m(function(){return h(c)}),e=k(f);if(1==e[0])a=k(a);else{var w=e[1],p=e[2],s=m(function(){var a=k(w);if(4==a[0])a=V(b,a[1]);else var c=k(b),a=4==c[0]?V(c[1],a):i;return a}),e=k(b);switch(e[0]){case 1:if(2==k(w)[0])a=g;else if(k(s))a=g;else a:{for(e=p;;){p=k(e);if(1==p[0])a=k(a);
else switch(e=p[2],p=k(p[1]),p[0]){case 2:a=g;break;case 4:if(V(G,p[1]))a=g;else continue;break;default:continue}break a}a=d}break;case 2:if(1==k(w)[0])a=g;else if(k(s))a=g;else a:{for(e=p;;){p=k(e);if(1==p[0])a=k(a);else switch(e=p[2],p=k(p[1]),p[0]){case 1:a=g;break;case 4:if(V(E,p[1]))a=g;else continue;break;default:continue}break a}a=d}break;default:if(k(s))a=g;else a:{for(;;){s=k(p);if(1==s[0])a=k(a);else if(p=s[2],s=k(s[1]),4==s[0])if(V(e,s[1]))a=g;else continue;else{var l=k(e);if(4==l[0])if(V(l[1],
s))a=g;else continue;else continue}break a}a=d}}}}return a};h(c)?e=[2,m(function(){var b=k(a);return 1==b[0]?k(R):k(b[1])}),C]:(e=O(ae,c),e=Lb(ae,e,b),e=1==e[0]?[2,m(function(){var a=k(b);return 1==a[0]?k(R):k(a[1])}),C]:k(e))}return e}function pe(a){return n(ne,[m(function(){return oe(me,ke,a)})])}var qe=[2,G,[2,je,C]],re=[2,E,[2,le,C]],se=m(function(){return n(Kc,[Jc,Nc])});
function te(a){var b=k(a);if(5==b[0])var c=b[2],a=m(function(){return te(c)}),b=te(b[1]),a=B(b,a);else a=[2,b,C];return a}function ue(a){var b=k(a);switch(b[0]){case 5:a=[2,m(function(){return te(b)}),C];break;case 6:var c=b[2],a=m(function(){return ue(c)}),e=ue(b[1]),a=B(e,a);break;default:a=[2,[2,b,C],C]}return a}function ve(a){return n(se,[m(function(){return oe(qe,re,m(function(){var b=ue(a);return L(pe,b)}))})])}var we=m(function(){return v("parser: input not exhausted")}),xe=[3],W=[1,0];
function ye(a,b){var c=n(a,[b]);if(1==c[0])c=[1,c[1]];else{var e=k(c[1]),c=e[1],e=e[2],f=ye(a,c);1==f[0]?c=[2,[1,c,[2,e,C]]]:(c=k(f[1]),c=[2,[1,c[1],[2,e,c[2]]]])}return c}var X=m(function(){return v("not satisfied")}),Y=[1,C,X],ze=[1,Y];
function Ae(a){a=k(a);if(1==a[0])a=k(ze);else{var b=a[2],c=k(a[1]),e=k(c[1]);switch(e){case "\t":a=[2,[1,b,c]];break;case "\n":a=[2,[1,b,c]];break;case "\v":a=[2,[1,b,c]];break;case "\f":a=[2,[1,b,c]];break;case "\r":a=[2,[1,b,c]];break;case " ":a=[2,[1,b,c]];break;case "p":a=[2,[1,b,c]];break;default:a=k(9==e.charCodeAt(0)||10==e.charCodeAt(0)||13==e.charCodeAt(0)||32==e.charCodeAt(0))?[2,[1,b,c]]:[1,[1,a,X]]}}return a}
var Be=[12],Ce=[1,Y],De=[10],Ee=m(function(){return v("->")}),Fe=[1,function(a,b){var c=k(a)[1],e=k(b)[1];return c==e},function(a,b){var c=k(a)[1],e=k(b)[1];return c!=e}];function Ge(a,b){var c=k(a);if(c){var e=k(b);if(1==e[0])e=[1,C,C];else var f=e[2],h=m(function(){var a=Ge(c-1|0,f);return[1,a[1],a[2]]}),e=[1,[2,e[1],m(function(){var a=k(h)[1];return k(a)})],m(function(){var a=k(h)[2];return k(a)})]}else e=[1,C,b];return e}var He=[1,")"],Ie=[1,"("];
function Je(a){a=k(a)[1];a=String.fromCharCode(a.charCodeAt(0)).toLowerCase().charCodeAt(0);if(1114111>=a>>>0)a=[1,String.fromCharCode(a)];else var b=k([1,a])[1],a=x("Prelude.chr: bad argument: ",m(function(){return 0>b?[2,Ie,m(function(){return Ea(b,[2,He,C])})]:Ea(b,C)})),a=t(a);return a}
function Ke(a){var b=m(function(){return[1,z(a)]}),c=m(function(){return L(Je,a)});return k(function(e){var f;a:{f=c;for(var h=m(function(){return L(Je,e)});;){var j=k(f);if(1==j[0])f=g;else{f=j[1];var j=j[2],o=k(h);if(1==o[0])f=i;else if(h=o[2],n(M,[Fe,f,o[1]])){f=j;continue}else f=i}break a}f=d}if(f){var r=m(function(){var a=k(b)[1];0>a?a=[1,e,C]:(a=Ge(a,e),a=[1,a[2],a[1]]);return a});f=[2,[1,m(function(){var a=k(r)[1];return k(a)}),m(function(){var a=k(r)[2];return k(a)})]]}else f=[1,[1,e,a]];
return f})}var Le=m(function(){return Ke(Ee)}),Me=[11],Ne=m(function(){return v("<->")}),Oe=m(function(){return Ke(Ne)}),Pe=[9],Qe=[1,Y],Re=m(function(){return v("v\u2228")}),Se=[8],Te=[1,Y],Ue=m(function(){return v("^\u2227")}),Ve=[7],We=[1,Y],Xe=m(function(){return v("!\u00ac")}),Ye=[5],Ze=[2,[1,")"],C],$e=m(function(){return Ke(Ze)}),af=[4],bf=[2,[1,"("],C],cf=m(function(){return Ke(bf)}),df=[6],ef=[1,Y],ff=[1,Y];
function gf(a){a=k(a);if(1==a[0])a=k(ff);else var b=a[2],c=k(a[1]),a=k(ea(c[1].charCodeAt(0))[2])?[2,[1,b,c]]:[1,[1,a,X]];return a}
var hf=[1,Y],jf=[2],kf=[2,[1,"0"],C],lf=m(function(){return Ke(kf)}),mf=[2,function(a){a=n(lf,[a]);1==a[0]?a=[1,a[1]]:(a=k(a[1]),a=[2,[1,a[1],[1,jf,W,a[2]]]]);return a},[2,function(a){var b=k(a);if(1==b[0])a=k(hf);else{var c=b[2],a=k(b[1]);k(ea(a[1].charCodeAt(0))[2])?(b=ye(gf,c),1==b[0]?a=[1,b[1]]:(b=k(b[1]),a=[2,[1,b[1],[1,df,W,[2,a,b[2]]]]])):a=[1,[1,b,X]]}return a},[2,function(a){var b=k(a);if(1==b[0])a=k(ef);else{var c=b[2],a=k(b[1]),e=a[1];k(ea(e.charCodeAt(0))[2])?"v"==k(e)?a=[1,[1,b,X]]:(b=
k(c),1==b[0]?a=[2,[1,C,[1,df,W,[2,a,C]]]]:(c=k(b[1])[1].charCodeAt(0),a=k(ea(c)[2])?[1,[1,b,cb]]:[2,[1,b,[1,df,W,[2,a,C]]]])):a=[1,[1,b,X]]}return a},[2,function(a){a=n(cf,[a]);1==a[0]?a=[1,a[1]]:(a=k(a[1]),a=[2,[1,a[1],[1,af,W,a[2]]]]);return a},[2,function(a){a=n($e,[a]);1==a[0]?a=[1,a[1]]:(a=k(a[1]),a=[2,[1,a[1],[1,Ye,W,a[2]]]]);return a},[2,function(a){a=k(a);if(1==a[0])a=k(We);else var b=a[1],c=a[2],a=N(Fe,b,Xe)?[2,[1,c,[1,Ve,W,[2,b,C]]]]:[1,[1,a,X]];return a},[2,function(a){a=k(a);if(1==a[0])a=
k(Te);else var b=a[1],c=a[2],a=N(Fe,b,Ue)?[2,[1,c,[1,Se,W,[2,b,C]]]]:[1,[1,a,X]];return a},[2,function(a){a=k(a);if(1==a[0])a=k(Qe);else var b=a[1],c=a[2],a=N(Fe,b,Re)?[2,[1,c,[1,Pe,W,[2,b,C]]]]:[1,[1,a,X]];return a},[2,function(a){a=n(Oe,[a]);1==a[0]?a=[1,a[1]]:(a=k(a[1]),a=[2,[1,a[1],[1,Me,W,a[2]]]]);return a},[2,function(a){a=n(Le,[a]);1==a[0]?a=[1,a[1]]:(a=k(a[1]),a=[2,[1,a[1],[1,De,W,a[2]]]]);return a},[2,function(a){a=k(a);return 1==a[0]?k(Ce):[2,[1,a[2],[1,Be,W,[2,a[1],C]]]]},C]]]]]]]]]]];
function nf(a,b,c){a=n(a,[c]);return 1==a[0]?n(b,[c]):k(a)}var of=[1],pf=[2,[1,"1"],C],qf=m(function(){return Ke(pf)});function rf(a){a=n(qf,[a]);1==a[0]?a=[1,a[1]]:(a=k(a[1]),a=[2,[1,a[1],[1,of,W,a[2]]]]);return a}var sf=m(function(){return T(nf,rf,mf)});function tf(a){var b=ye(Ae,a);1==b[0]?a=n(sf,[a]):(a=k(b[1]),a=[2,[1,a[1],[1,xe,W,a[2]]]]);return a}var uf=[1,-1];function vf(a){a=k(a)[1];return 2==k(a)[0]?i:g}
function wf(a,b){var c=n(a,[b]);if(1==c[0])c=k(c);else var e=k(c[1]),c=e[2],e=k(e[1]),c=1==e[0]?[2,[1,C,c]]:[1,[1,e,cb]];return c}var Z=[1,C,X],xf=[1,Z];function yf(a){a=k(a);if(1==a[0])a=k(xf);else var b=a[2],c=k(a[1])[1],a=1==k(c)[0]?[2,[1,b,E]]:[1,[1,a,X]];return a}var zf=[1,Z];function Af(a){a=k(a);if(1==a[0])a=k(zf);else var b=a[2],c=k(a[1]),e=c[3],a=5==k(c[1])[0]?[2,[1,b,[3,e]]]:[1,[1,a,X]];return a}var Bf=[4,G],Cf=[1,Z];
function Df(a){a=k(a);if(1==a[0])a=k(Cf);else{var b=a[2],c=k(a[1])[1];6==k(c)[0]?(a=k(b),1==a[0]?(a=k(Ef),1==a[0]?a=k(a):(a=k(a[1]),a=[2,[1,a[1],[4,a[2]]]])):(b=a[2],c=k(a[1])[1],k(c)[0]?(a=n($,[a]),1==a[0]?a=k(a):(a=k(a[1]),a=[2,[1,a[1],[4,a[2]]]])):a=[2,[1,b,Bf]])):a=[1,[1,a,X]]}return a}var Ff=[1,Z],Gf=[1,Z];
function Hf(a,b){var c=k(b);if(1==c[0])c=k(Ff);else{var e=c[2],f=k(c[1])[1];if(3==k(f)[0])if(c=n(a,[e]),1==c[0])c=k(c);else if(e=k(c[1]),c=e[2],e=k(e[1]),1==e[0])c=k(Gf);else var f=e[2],h=k(e[1])[1],c=4==k(h)[0]?[2,[1,f,c]]:[1,[1,e,X]];else c=[1,[1,c,X]]}return c}
var Jf=m(function(){var a=L(Hf,If);if(1==a[0])a=k(Ic);else{var b=a[1],a=k(a[2]);if(1==a[0])a=k(b);else var c=a[1],e=a[2],f=m(function(){return T(nf,c,e)}),a=k(function(a){var c=n(b,[a]);return 1==c[0]?n(f,[a]):k(c)})}return a}),Kf=m(function(){return[2,Jf,C]}),Lf=m(function(){return[2,Df,Kf]}),Mf=m(function(){return[2,Af,Lf]}),$=m(function(){return T(nf,yf,Mf)}),Ef=m(function(){return n($,[C])}),Nf=[1,Z];
function Of(a){a=k(a);if(1==a[0])a=k(Nf);else var b=a[2],c=k(a[1])[1],a=8==k(c)[0]?[2,[1,b,Nc]]:[1,[1,a,X]];return a}var Pf=m(function(){return T(nf,Of,C)});
function Qf(a,b){function c(a,c){var e=Rf(a);if(1==e[0])if(e=k(a),1==e[0])if(e=n($,[C]),1==e[0])e=k(e);else var e=k(e[1]),f=e[2],e=[2,[1,e[1],m(function(){return n(c,[b,f])})]];else{var h=e[2],p=k(e[1])[1];if(k(p)[0])if(e=n($,[e]),1==e[0])e=k(e);else var e=k(e[1]),s=e[2],e=[2,[1,e[1],m(function(){return n(c,[b,s])})]];else e=[2,[1,h,m(function(){return n(c,[b,G])})]]}else var e=k(e[1]),l=e[2],e=[2,[1,e[1],m(function(){return n(c,[b,l])})]];return e}var e=k(a);if(1==e[0]){var f=n(Pf,[C]);1==f[0]?f=
[1,f[1]]:(f=k(f[1]),f=c(f[1],f[2]))}else{var f=e[2],h=k(e[1])[1];7==k(h)[0]?(e=Rf(f),1==e[0]?(f=k(f),1==f[0]?(f=n($,[C]),1==f[0]?f=k(f):(f=k(f[1]),f=[2,[1,f[1],[5,b,f[2]]]])):(e=f[2],h=k(f[1])[1],k(h)[0]?(f=n($,[f]),1==f[0]?f=k(f):(f=k(f[1]),f=[2,[1,f[1],[5,b,f[2]]]])):f=[2,[1,e,[5,b,G]]])):(f=k(e[1]),f=[2,[1,f[1],[5,b,f[2]]]])):(f=n(Pf,[e]),1==f[0]?f=[1,f[1]]:(f=k(f[1]),f=c(f[1],f[2])))}return f}
function Rf(a){a=k(a);if(1==a[0])if(a=k(Ef),1==a[0])a=k(a);else var a=k(a[1]),b=a[1],c=a[2],e=function(a,b){function c(a,e){var h=f(a);if(1==h[0])if(h=k(a),1==h[0])if(h=n($,[C]),1==h[0])h=k(h);else var h=k(h[1]),j=h[2],h=[2,[1,h[1],m(function(){return n(e,[b,j])})]];else{var q=h[2],o=k(h[1])[1];if(k(o)[0])if(h=n($,[h]),1==h[0])h=k(h);else var h=k(h[1]),p=h[2],h=[2,[1,h[1],m(function(){return n(e,[b,p])})]];else h=[2,[1,q,m(function(){return n(e,[b,G])})]]}else var h=k(h[1]),s=h[2],h=[2,[1,h[1],m(function(){return n(e,
[b,s])})]];return h}var e=k(a);if(1==e[0]){var h=n(Pf,[C]);1==h[0]?h=[1,h[1]]:(h=k(h[1]),h=c(h[1],h[2]))}else{var h=e[2],j=k(e[1])[1];7==k(j)[0]?(e=f(h),1==e[0]?(h=k(h),1==h[0]?(h=n($,[C]),1==h[0]?h=k(h):(h=k(h[1]),h=[2,[1,h[1],[5,b,h[2]]]])):(e=h[2],j=k(h[1])[1],k(j)[0]?(h=n($,[h]),1==h[0]?h=k(h):(h=k(h[1]),h=[2,[1,h[1],[5,b,h[2]]]])):h=[2,[1,e,[5,b,G]]])):(h=k(e[1]),h=[2,[1,h[1],[5,b,h[2]]]])):(h=n(Pf,[e]),1==h[0]?h=[1,h[1]]:(h=k(h[1]),h=c(h[1],h[2])))}return h},f=function(a){a=k(a);if(1==a[0])a=
e(b,c);else{var f=a[2],h=k(a[1])[1];k(h)[0]?(a=n($,[a]),1==a[0]?a=k(a):(a=k(a[1]),a=e(a[1],a[2]))):a=e(f,G)}return a},a=e(b,c);else{var h=a[2],j=k(a[1])[1];k(j)[0]?(a=n($,[a]),1==a[0]?a=k(a):(a=k(a[1]),a=Qf(a[1],a[2]))):a=Qf(h,G)}return a}function Sf(a,b){return[8,a,b]}var Tf=[1,Z];function Uf(a){a=k(a);if(1==a[0])a=k(Tf);else var b=a[2],c=k(a[1])[1],a=10==k(c)[0]?[2,[1,b,Sf]]:[1,[1,a,X]];return a}var Vf=m(function(){return T(nf,Uf,C)}),Wf=m(function(){return n(Vf,[C])});
function Xf(a,b){function c(b,c){var e=Yf(b);if(1==e[0])if(e=Rf(b),1==e[0])if(e=k(b),1==e[0])if(e=k(Ef),1==e[0])e=k(e);else var e=k(e[1]),f=e[2],e=[2,[1,e[1],m(function(){return n(c,[a,f])})]];else{var h=e[2],p=k(e[1])[1];if(k(p)[0])if(e=n($,[e]),1==e[0])e=k(e);else var e=k(e[1]),s=e[2],e=[2,[1,e[1],m(function(){return n(c,[a,s])})]];else e=[2,[1,h,m(function(){return n(c,[a,G])})]]}else var e=k(e[1]),l=e[2],e=[2,[1,e[1],m(function(){return n(c,[a,l])})]];else var e=k(e[1]),aa=e[2],e=[2,[1,e[1],m(function(){return n(c,
[a,aa])})]];return e}var e=k(b);if(1==e[0]){var f=k(Wf);1==f[0]?f=[1,f[1]]:(f=k(f[1]),f=c(f[1],f[2]))}else{var f=e[2],h=k(e[1])[1];9==k(h)[0]?(e=Yf(f),1==e[0]?(e=Rf(f),1==e[0]?(f=k(f),1==f[0]?(f=k(Ef),1==f[0]?f=k(f):(f=k(f[1]),f=[2,[1,f[1],[7,a,f[2]]]])):(e=f[2],h=k(f[1])[1],k(h)[0]?(f=n($,[f]),1==f[0]?f=k(f):(f=k(f[1]),f=[2,[1,f[1],[7,a,f[2]]]])):f=[2,[1,e,[7,a,G]]])):(f=k(e[1]),f=[2,[1,f[1],[7,a,f[2]]]])):(f=k(e[1]),f=[2,[1,f[1],[7,a,f[2]]]])):(f=n(Vf,[e]),1==f[0]?f=[1,f[1]]:(f=k(f[1]),f=c(f[1],
f[2])))}return f}
function Yf(a){var b=Rf(a);if(1==b[0])if(a=k(a),1==a[0])if(a=k(Ef),1==a[0])a=k(a);else var a=k(a[1]),c=a[1],e=a[2],f=function(a,b){function c(a,e){var f=h(a);if(1==f[0])if(f=k(a),1==f[0])if(f=n($,[C]),1==f[0])f=k(f);else var f=k(f[1]),j=f[2],f=[2,[1,f[1],m(function(){return n(e,[b,j])})]];else{var q=f[2],l=k(f[1])[1];if(k(l)[0])if(f=n($,[f]),1==f[0])f=k(f);else var f=k(f[1]),o=f[2],f=[2,[1,f[1],m(function(){return n(e,[b,o])})]];else f=[2,[1,q,m(function(){return n(e,[b,G])})]]}else var f=k(f[1]),
p=f[2],f=[2,[1,f[1],m(function(){return n(e,[b,p])})]];return f}var e=k(a);if(1==e[0]){var f=n(Pf,[C]);1==f[0]?f=[1,f[1]]:(f=k(f[1]),f=c(f[1],f[2]))}else{var f=e[2],j=k(e[1])[1];7==k(j)[0]?(e=h(f),1==e[0]?(f=k(f),1==f[0]?(f=n($,[C]),1==f[0]?f=k(f):(f=k(f[1]),f=[2,[1,f[1],[5,b,f[2]]]])):(e=f[2],j=k(f[1])[1],k(j)[0]?(f=n($,[f]),1==f[0]?f=k(f):(f=k(f[1]),f=[2,[1,f[1],[5,b,f[2]]]])):f=[2,[1,e,[5,b,G]]])):(f=k(e[1]),f=[2,[1,f[1],[5,b,f[2]]]])):(f=n(Pf,[e]),1==f[0]?f=[1,f[1]]:(f=k(f[1]),f=c(f[1],f[2])))}return f},
h=function(a){a=k(a);if(1==a[0])a=f(c,e);else{var b=a[2],h=k(a[1])[1];k(h)[0]?(a=n($,[a]),1==a[0]?a=k(a):(a=k(a[1]),a=f(a[1],a[2]))):a=f(b,G)}return a},j=function(a,b){function f(b,j){var l=o(b);if(1==l[0])if(l=h(b),1==l[0])if(l=k(b),1==l[0])l=[2,[1,c,m(function(){return n(j,[a,e])})]];else{var p=l[2],r=k(l[1])[1];if(k(r)[0])if(l=n($,[l]),1==l[0])l=k(l);else var l=k(l[1]),s=l[2],l=[2,[1,l[1],m(function(){return n(j,[a,s])})]];else l=[2,[1,p,m(function(){return n(j,[a,G])})]]}else var l=k(l[1]),w=
l[2],l=[2,[1,l[1],m(function(){return n(j,[a,w])})]];else var l=k(l[1]),aa=l[2],l=[2,[1,l[1],m(function(){return n(j,[a,aa])})]];return l}var j=k(b);if(1==j[0]){var l=k(Wf);1==l[0]?l=[1,l[1]]:(l=k(l[1]),l=f(l[1],l[2]))}else{var l=j[2],r=k(j[1])[1];9==k(r)[0]?(j=o(l),1==j[0]?(j=h(l),1==j[0]?(l=k(l),1==l[0]?l=[2,[1,c,[7,a,e]]]:(j=l[2],r=k(l[1])[1],k(r)[0]?(l=n($,[l]),1==l[0]?l=k(l):(l=k(l[1]),l=[2,[1,l[1],[7,a,l[2]]]])):l=[2,[1,j,[7,a,G]]])):(l=k(j[1]),l=[2,[1,l[1],[7,a,l[2]]]])):(l=k(j[1]),l=[2,[1,
l[1],[7,a,l[2]]]])):(l=n(Vf,[j]),1==l[0]?l=[1,l[1]]:(l=k(l[1]),l=f(l[1],l[2])))}return l},o=function(a){var b=h(a);if(1==b[0])if(a=k(a),1==a[0])a=j(e,c);else{var b=a[2],f=k(a[1])[1];k(f)[0]?(a=n($,[a]),1==a[0]?a=k(a):(a=k(a[1]),a=j(a[2],a[1]))):a=j(G,b)}else a=k(b[1]),a=j(a[2],a[1]);return a},a=j(e,c);else{var b=a[2],r=k(a[1])[1];k(r)[0]?(a=n($,[a]),1==a[0]?a=k(a):(a=k(a[1]),a=Xf(a[2],a[1]))):a=Xf(G,b)}else a=k(b[1]),a=Xf(a[2],a[1]);return a}
function Zf(a){var b=Yf(a);if(1==b[0])if(b=Rf(a),1==b[0])if(a=k(a),1==a[0])a=k(Ef);else var b=a[2],c=k(a[1])[1],a=k(c)[0]?n($,[a]):[2,[1,b,G]];else a=k(b);else a=k(b);return a}
var $f=[1,Z],ag=[2,function(a){a=k(a);if(1==a[0])a=k($f);else var b=a[2],c=k(a[1])[1],a=k(c)[0]?[1,[1,a,X]]:[2,[1,b,G]];return a},[2,yf,[2,Af,C]]],bg=m(function(){return[2,Df,ag]}),If=m(function(){return[2,Zf,bg]}),cg=m(function(){var a=L(wf,If);if(1==a[0])a=k(Ic);else{var b=a[1],a=k(a[2]);if(1==a[0])a=k(b);else var c=a[1],e=a[2],f=m(function(){return T(nf,c,e)}),a=k(function(a){var c=n(b,[a]);return 1==c[0]?n(f,[a]):k(c)})}return a});
function dg(a,b){var c=k(b);if(1==c[0])c=[1];else var e=c[2],c=k(c[1]),f=c[3],c=[2,[1,c[1],a,f],m(function(){return dg(m(function(){var b=k(a)[1],c=z(f);return[1,b+c|0]}),e)})];return c}
function eg(a){var b=ye(tf,a);if(1==b[0])var b=k(b[1]),c=b[1],e=b[2],b=Fa(m(function(){var b=z(a),e=z(c);return[1,b-e|0]}),m(function(){return x("tokenizer: ",e)}));else{var b=k(b[1]),f=b[2],h=k(b[1]);if(1==h[0])if(b=n(cg,[m(function(){var a=dg(W,f);return A(vf,a)})]),1==b[0]){var j=k(b[1]),b=j[2],j=k(j[1]);if(1==j[0])b=Fa(uf,b);else var o=j[1],b=Fa(m(function(){var a=k(o)[2];return k(a)}),b)}else{var b=k(b[1]),r=b[2],b=k(b[1]);if(1==b[0])if(b=k(bb)[1],b=k(y(b)[2]),1==b[0])b=k(eb);else{var j=k(b[1])[1],
q=k($a)[1],w=m(function(){return n(Db,[m(function(){return n(Fb,[r])})])}),b=m(function(){return n(yb,[w])}),p=F(b),p=u(p)[1];fa(j,q,p);j=k(Za)[1];j=k(y(j)[2]);1==j[0]?b=k(fb):(j=k(j[1])[1],q=k(Xa)[1],b=n(ie,[b]),b=F(b),b=u(b)[1],fa(j,q,b),b=k(Wa)[1],b=k(y(b)[2]),1==b[0]?b=k(gb):(j=k(b[1])[1],q=k(Ua)[1],b=m(function(){return n(Ab,[w])}),p=F(b),p=u(p)[1],fa(j,q,p),j=k(Ta)[1],j=k(y(j)[2]),1==j[0]?b=k(Ia):(j=k(j[1])[1],q=k(Sa)[1],b=n(ve,[b]),b=F(b),b=u(b)[1],fa(j,q,b),b=k(Ra)[1],b=k(y(b)[2]),1==b[0]?
b=k(Ka):(b=k(b[1])[1],j=k(Qa)[1],q=F(w),q=u(q)[1],fa(b,j,q),b=k(Pa)[1],b=k(y(b)[2]),1==b[0]?b=k(Ma):(b=k(b[1])[1],j=k(Oa)[1],q=n(Td,[r]),q=F(q),q=u(q)[1],b=[1,fa(b,j,q)[1],Ba])))))}else var s=b[1],b=Fa(m(function(){var a=k(s)[2];return k(a)}),we)}else b=Fa(m(function(){var b=z(a),c=z(h);return[1,b-c|0]}),db)}return b}var fg=[1,"value"],gg=m(function(){return D(za)}),hg=m(function(){return u(za)});
function ig(){var a=k(hg)[1],a=k(y(a)[2]);if(1==a[0])a=k(gg);else var a=k(a[1])[1],b=k(fg)[1],a=[1,0,a[b].toString()],c=a[2],a=[1,a[1],m(function(){return v(k([1,c])[1])})];return a}function jg(){var a=ig();return eg(a[2])}var kg=m(function(){return v("analyzeButton")}),lg=m(function(){return D(kg)}),mg=m(function(){return u(kg)});function ng(a,b){var c=k(a)[1];13==k(c)?(c=ig(),c=eg(c[2])):c=[1,b,Ba];return c}var og=m(function(){return D(za)});
function pg(){var a=k(mg)[1],a=k(y(a)[2]);1==a[0]?a=k(lg):(a=k(a[1])[1],ya(a,ga,jg),a=k(Aa)[1],a=k(y(a)[2]),1==a[0]?a=k(og):(a=k(a[1])[1],a=ya(a,ha,ng)));return a}window.onload=function(){k(k(pg)(0))};
