var d=void 0,f=!0,g=!1;function n(a){return a instanceof aa?(a.a&&(a.x=a.a(),a.a=0),a.x):a}function o(a){return new aa(a)}function aa(a){this.a=a}function ba(a){return 0<a?[1,[1,a,2]]:0>a?[2,[1,a,2]]:[3]}
function p(a,c){function b(){var b=c.concat(Array.prototype.slice.call(arguments));return p(a,b)}a=a instanceof aa?n(a):a;if(!a.apply)return a;var e=a.arity?a.arity:a.length;if(c.length===e)return a.apply(null,c);if(c.length>e)return e=c.splice(0,e),p(a.apply(null,e),c);b.arity=e-c.length;return b}function q(a,c){return(a&65535)*(c&65535)+(a&65535)*(c&4294901760)+(a&4294901760)*(c&65535)}function s(a){throw ca(a)[1];}function t(a){return da(a,[1])}
function da(a,c,b){var e=b?b:0;return e>=a.length?n(c):[2,[1,a.charAt(e)],o(function(){return da(a,c,e+1)})]}function ca(a){for(var a=n(a),c="";2==a[0];)a=ea(a),c+=a[0],a=a[1];return[1,c]}function ea(a){var c=n(a[1])[1];if("\\"==c){var b="",a=n(a[2]);if(1==a)return["\\",a];for(c=n(a[1])[1];"0"<=c&&"9">=c;)b+=c,a=n(a[2]),c=n(a[1])[1];if(0==b.length)return["\\",a];c=String.fromCharCode(Number(b));return[c,a]}return[c,n(a[2])]}
function fa(a,c,b){return a.addEventListener?(a.addEventListener(c,b,g),[1,0,f]):a.attachEvent?(a.attachEvent("on"+c,b),[1,0,f]):[1,0,g]}var ga=o(function(){return t("Maybe.fromJust: Nothing")}),ha=o(function(){return s(ga)});function ia(a,c,b){var e=o(function(){var h=p(a,[b]),i=h[1],h=h[2],j=p(c,[o(function(){var a=n(e);return 1==a[0]?n(ha):n(a[1])})]),k=j[2];return n(i==j[1])?n(h==k)?[2,b]:[1]:[1]});return n(e)}function ja(a){a=n(a)[1];return n(a)}
var u=[1],ka=[1,7238999624334008E3,1.0769272474234763E19,[1,7238999624334008E3,1.0769272474234763E19,o(function(){return t("base")}),o(function(){return t("GHC.IO.Exception")}),o(function(){return t("IOException")})],u];function la(){return n(ka)}function ma(a){var c=n(a),a=c[2],c=ja(c[1]);return ia(c,la,a)}function x(a,c){var b=n(a);if(1==b[0])b=n(c);else var e=b[2],b=[2,b[1],o(function(){return x(e,c)})];return b}
var na=o(function(){return t(": ")}),pa=o(function(){return t("already exists")}),qa=o(function(){return t("does not exist")}),ra=o(function(){return t("protocol error")}),sa=o(function(){return t("failed")}),ta=o(function(){return t("invalid argument")}),ua=o(function(){return t("inappropriate type")}),va=o(function(){return t("hardware fault")}),xa=o(function(){return t("unsupported operation")}),ya=o(function(){return t("timeout")}),za=o(function(){return t("resource vanished")}),Aa=o(function(){return t("interrupted")}),
Ba=o(function(){return t("resource busy")}),Ca=o(function(){return t("resource exhausted")}),Da=o(function(){return t("end of file")}),Ea=o(function(){return t("illegal operation")}),Fa=o(function(){return t("permission denied")}),Ha=o(function(){return t("user error")}),Ia=o(function(){return t("unsatisified constraints")}),Ja=o(function(){return t("system error")}),Ka=o(function(){return t(" (")}),La=[1,")"],Ma=[1,"}"],Na=o(function(){return t("{handle: ")});
function Oa(a,c,b,e,h,i){var j=o(function(){var a=o(function(){var a=o(function(){var a=n(e);return 1==a[0]?n(i):x(Ka,o(function(){return x(a,[2,La,i])}))});switch(n(c)[0]){case 1:var b=x(pa,a);break;case 2:b=x(qa,a);break;case 3:b=x(Ba,a);break;case 4:b=x(Ca,a);break;case 5:b=x(Da,a);break;case 6:b=x(Ea,a);break;case 7:b=x(Fa,a);break;case 8:b=x(Ha,a);break;case 9:b=x(Ia,a);break;case 10:b=x(Ja,a);break;case 11:b=x(ra,a);break;case 12:b=x(sa,a);break;case 13:b=x(ta,a);break;case 14:b=x(ua,a);break;
case 15:b=x(va,a);break;case 16:b=x(xa,a);break;case 17:b=x(ya,a);break;case 18:b=x(za,a);break;case 19:b=x(Aa,a)}return b}),h=n(b);return 1==h[0]?n(a):x(h,o(function(){return x(na,a)}))}),h=n(h);if(1==h[0])if(a=n(a),1==a[0])a=n(j);else if(a=n(a[1]),1==a[0])var k=a[1],a=x(Na,o(function(){return x(k,[2,Ma,o(function(){return x(na,j)})])}));else var l=a[1],a=x(Na,o(function(){return x(l,[2,Ma,o(function(){return x(na,j)})])}));else a=x(h[1],o(function(){return x(na,j)}));return a}
var Pa=[1,","],Ra=[1,"]"],Sa=[1,"["],Ta=[1,function(a,c,b){a=n(c);return Oa(a[1],a[2],a[3],a[4],a[6],b)},function(a){a=n(a);return Oa(a[1],a[2],a[3],a[4],a[6],u)},function(a,c){var b=n(a);if(1==b[0])b=da("[]",c);else var e=b[1],h=b[2],b=[2,Sa,o(function(){var a=n(e);return Oa(a[1],a[2],a[3],a[4],a[6],o(function(){function a(c){c=n(c);if(1==c[0])c=n(b);else var e=c[1],h=c[2],c=[2,Pa,o(function(){var b=n(e);return Oa(b[1],b[2],b[3],b[4],b[6],o(function(){return a(h)}))})];return c}var b=[2,Ra,c];return a(h)}))})];
return b}],Va=o(function(){return[1,la,Ta,Ua,ma]});function Ua(a){return[1,Va,a]}var Wa=[1],Xa=[8],Ya=[1,function(a,c,b){a=p(a,[b]);return p(c,[a[2],a[1]])},function(a,c,b){a=p(a,[b])[1];return p(c,[a])},function(a,c){return[1,c,a]},function(a){throw o(function(){return Ua(o(function(){return[1,Wa,Xa,u,a,Wa,Wa]}))});}];function y(a){a=n(a)[2];return n(a)}function z(a){a=n(a)[3];return n(a)}var Za=[1];function $a(a,c,b){return n(c)?n(b):p(z,[a,Za])}function A(a,c){return p(a,[c])}
var C=[1,function(a,c){var b=n(a)[1],e=n(c)[1];return b==e},function(a,c){var b=n(a)[1],e=n(c)[1];return b!=e}];function D(a){a=n(a)[1];return n(a)}
var ab=[1,-1],bb=[1,0],cb=[1,1],db=[1,function(a,c){var b=n(a)[1],e=n(c)[1];return[1,b+e|0]},function(a,c){var b=n(a)[1],e=n(c)[1];return[1,q(b,e)|0]},function(a,c){var b=n(a)[1],e=n(c)[1];return[1,b-e|0]},function(a){return[1,-n(a)[1]]},function(a){var a=n(a),c=a[1];return 0<=c?n(a):[1,-c]},function(a){a=n(a)[1];return 0>a?n(ab):n(a)?n(cb):n(bb)},function(a){a=n(a);switch(a[0]){case 1:var c=n(a[1]),c=1==c[0]?n(c[1]):0;break;case 2:c=n(a[1]);c=1==c[0]?0-c[1]>>>0:0;break;case 3:c=0}return[1,c&4294967295]}];
function eb(a){a=n(a)[7];return n(a)}var fb=[13,d],gb=[1,"load"],hb=[1,"mousemove"],ib=[1,"mouseover"],jb=[1,"mouseout"],kb=[1,"click"],lb=[1,"dblclick"],mb=[1,"mousedown"],nb=[1,"mouseup"],ob=[1,"keypress"],pb=[1,"keyup"],qb=[1,"keydown"],rb=[1,"unload"],sb=[1,"change"],tb=[1,"focus"],ub=[1,"blur"];
function vb(a,c,b){function e(a){n(b);"change"==a&&"text"==h.type.toLowerCase()&&fa(h,"keyup",args);var c;switch(a){case "click":case "dblclick":case "mouseup":case "mousedown":c=function(a){p(b,[[1,a.button],0])};break;case "keypress":case "keyup":case "keydown":c=function(a){p(b,[[1,a.keyCode],0])};break;default:c=function(){p(b,[0])}}var a=fa(h,a,c),e=a[2];return[1,a[1],o(function(){return n(e)?f:g})]}var h=n(a)[1];switch(n(c)[0]){case 1:var a=n(gb)[1],i=e(a);break;case 2:a=n(rb)[1];i=e(a);break;
case 3:a=n(sb)[1];i=e(a);break;case 4:a=n(tb)[1];i=e(a);break;case 5:a=n(ub)[1];i=e(a);break;case 6:a=n(hb)[1];i=e(a);break;case 7:a=n(ib)[1];i=e(a);break;case 8:a=n(jb)[1];i=e(a);break;case 9:a=n(kb)[1];i=e(a);break;case 10:a=n(lb)[1];i=e(a);break;case 11:a=n(mb)[1];i=e(a);break;case 12:a=n(nb)[1];i=e(a);break;case 13:a=n(ob)[1];i=e(a);break;case 14:a=n(pb)[1];i=e(a);break;case 15:a=n(qb)[1],i=e(a)}return i}var wb=o(function(){return t(" could be found!")});
function xb(a,c){var b=ca(a)[1],e;e=(b=document.getElementById(b))?[1,0,[2,[1,b]]]:[1,0,[1]];b=e[1];e=n(e[2]);1==e[0]?(b=da("No element with ID ",o(function(){return x(a,wb)})),b=s(b)):b=p(c,[e[1],b]);return b}function F(a){a=n(a)[1];return n(a)}var yb=[1,"-"];function zb(a,c){for(;;){if(10>a)return[2,[1,String.fromCharCode(48+a|0)],c];var b=[2,[1,String.fromCharCode(48+a%10|0)],c],a=(a-a%10)/10,c=b}}
function Ab(a,c){if(0>a)var b=n(a),e=-2147483648==b?[2,yb,o(function(){return zb(214748364,o(function(){return zb(8,c)}))})]:[2,yb,o(function(){return zb(-b,c)})];else e=zb(a,c);return e}var Bb=[1,")"],Cb=[1,"("];function Db(a,c,b){return 0>c?6<a?[2,Cb,o(function(){return Ab(c,[2,Bb,b])})]:Ab(c,b):Ab(c,b)}
var Fb=[1,function(a,c,b){a=n(a)[1];c=n(c)[1];return Db(a,c,b)},function(a){a=n(a)[1];return Db(0,a,u)},function(a,c){var b=n(a);if(1==b[0])b=da("[]",c);else var e=b[1],h=b[2],b=[2,Sa,o(function(){var a=n(e)[1];return Db(0,a,o(function(){function a(c){c=n(c);if(1==c[0])c=n(b);else var e=c[1],h=c[2],c=[2,Pa,o(function(){var b=n(e)[1];return Db(0,b,o(function(){return a(h)}))})];return c}var b=[2,Ra,c];return a(h)}))})];return b}];function Gb(a){a=n(a)[2];return n(a)}
function Hb(a){a=ca(a)[1];"undefined"!=typeof alert?alert(a):print(a);return[1,0,Za]}function Ib(a,c){var b=n(a)[1],e=ca(c)[1],b=[1,0,b[e].toString()],h=b[2];return[1,b[1],o(function(){return t(n([1,h])[1])})]}function Jb(a,c,b){a=n(a)[1];c=ca(c)[1];b=ca(b)[1];a[c]=b;return[1,0,Za]}function Kb(a){return n(a)}function Lb(a){return 5==n(a)[0]?f:g}function Mb(a){return 6==n(a)[0]?f:g}function Nb(a,c){return n(a)?f:n(c)}
function Ob(a,c){return p(Nb,[o(function(){switch(n(c)[0]){case 1:var a=f;break;case 2:a=f;break;case 3:a=f;break;case 4:a=f;break;default:a=g}return a}),o(function(){return p(a,[c])})])?G(c):p(x,[[2,[1,"("],u],o(function(){return p(x,[o(function(){return G(c)}),[2,[1,")"],u]])})])}
function G(a){a=n(a);switch(a[0]){case 1:var c=[2,[1,"1"],u];break;case 2:c=[2,[1,"0"],u];break;case 3:c=n(a[1]);break;case 4:var b=a[1],c=p(x,[[2,[1,"!"],u],o(function(){return Ob(o(function(){return p(Kb,[g])}),b)})]);break;case 5:var e=a[1],h=a[2],c=p(x,[o(function(){return Ob(Lb,e)}),o(function(){return p(x,[o(function(){return p(t,[" ^ "])}),o(function(){return Ob(Lb,h)})])})]);break;case 6:var i=a[1],j=a[2],c=p(x,[o(function(){return Ob(Mb,i)}),o(function(){return p(x,[o(function(){return p(t,
[" v "])}),o(function(){return Ob(Mb,j)})])})]);break;case 7:var k=a[1],l=a[2],c=p(x,[[2,[1,"("],u],o(function(){return p(x,[o(function(){return G(k)}),o(function(){return p(x,[o(function(){return p(t,[") -> ("])}),o(function(){return p(x,[o(function(){return G(l)}),[2,[1,")"],u]])})])})])})]);break;case 8:var m=a[1],r=a[2],c=p(x,[[2,[1,"("],u],o(function(){return p(x,[o(function(){return G(m)}),o(function(){return p(x,[o(function(){return p(t,[") <-> ("])}),o(function(){return p(x,[o(function(){return G(r)}),
[2,[1,")"],u]])})])})])})])}return c}function H(a,c,b){return p(a,[o(function(){return p(c,[b])})])}function Pb(a){return[4,a]}
function Qb(a){var c=Qb,a=n(a);switch(a[0]){case 1:var b=[1];break;case 2:b=[2];break;case 3:b=[3,a[1]];break;case 4:var e=a[1],b=p(A,[Pb,o(function(){return p(c,[e])})]);break;case 5:var h=a[1],i=a[2],b=[5,o(function(){return p(c,[h])}),o(function(){return p(c,[i])})];break;case 6:var j=a[1],k=a[2],b=[6,o(function(){return p(c,[j])}),o(function(){return p(c,[k])})];break;case 7:var l=a[1],m=a[2],b=[7,o(function(){return p(c,[l])}),o(function(){return p(c,[m])})];break;case 8:var r=a[1],v=a[2],b=
[8,o(function(){return p(c,[r])}),o(function(){return p(c,[v])})]}return b}
function K(a,c){return p(a,[o(function(){var b=n(c);switch(b[0]){case 1:var e=[1];break;case 2:e=[2];break;case 3:e=[3,b[1]];break;case 4:var h=b[1],e=p(A,[Pb,o(function(){return K(a,h)})]);break;case 5:var i=b[1],j=b[2],e=[5,o(function(){return K(a,i)}),o(function(){return K(a,j)})];break;case 6:var k=b[1],l=b[2],e=[6,o(function(){return K(a,k)}),o(function(){return K(a,l)})];break;case 7:var m=b[1],r=b[2],e=[7,o(function(){return K(a,m)}),o(function(){return K(a,r)})];break;case 8:var v=b[1],w=
b[2],e=[8,o(function(){return K(a,v)}),o(function(){return K(a,w)})]}return e})])}
function Rb(a){a=n(a);if(6==a[0]){var c=a[2],b=n(a[1]);if(5==b[0]){var e=o(function(){return p(H,[Rb,function(a){return[6,c,a]}])}),a=n(b);switch(a[0]){case 1:var h=[1];break;case 2:h=[2];break;case 3:h=[3,a[1]];break;case 4:var i=a[1],h=p(A,[Pb,o(function(){return p(e,[i])})]);break;case 5:var j=a[1],k=a[2],h=[5,o(function(){return p(e,[j])}),o(function(){return p(e,[k])})];break;case 6:var l=a[1],m=a[2],h=[6,o(function(){return p(e,[l])}),o(function(){return p(e,[m])})];break;case 7:var r=a[1],
v=a[2],h=[7,o(function(){return p(e,[r])}),o(function(){return p(e,[v])})];break;case 8:var w=a[1],B=a[2],h=[8,o(function(){return p(e,[w])}),o(function(){return p(e,[B])})]}}else h=n(c),h=5==h[0]?p(A,[Rb,[6,h,b]]):n(a)}else h=n(a);return h}function Sb(a){return K(Rb,a)}var Tb=o(function(){return p(H,[Qb,Sb])});
function Ub(a){a=n(a);if(5==a[0]){var c=a[2],b=n(a[1]);if(6==b[0]){var e=o(function(){return p(H,[Ub,function(a){return[5,c,a]}])}),a=n(b);switch(a[0]){case 1:var h=[1];break;case 2:h=[2];break;case 3:h=[3,a[1]];break;case 4:var i=a[1],h=p(A,[Pb,o(function(){return p(e,[i])})]);break;case 5:var j=a[1],k=a[2],h=[5,o(function(){return p(e,[j])}),o(function(){return p(e,[k])})];break;case 6:var l=a[1],m=a[2],h=[6,o(function(){return p(e,[l])}),o(function(){return p(e,[m])})];break;case 7:var r=a[1],
v=a[2],h=[7,o(function(){return p(e,[r])}),o(function(){return p(e,[v])})];break;case 8:var w=a[1],B=a[2],h=[8,o(function(){return p(e,[w])}),o(function(){return p(e,[B])})]}}else h=n(c),h=6==h[0]?p(A,[Ub,[5,h,b]]):n(a)}else h=n(a);return h}function Vb(a){return K(Ub,a)}var Wb=o(function(){return p(H,[Qb,Vb])});
function L(a){a=n(a);if(4==a[0]){var c=n(a[1]);switch(c[0]){case 5:a=p(A,[function(a){a=n(a);switch(a[0]){case 1:var c=[1];break;case 2:c=[2];break;case 3:c=[3,a[1]];break;case 4:var h=a[1],c=p(A,[Pb,o(function(){return L(h)})]);break;case 5:var i=a[1],j=a[2],c=[5,o(function(){return L(i)}),o(function(){return L(j)})];break;case 6:var k=a[1],l=a[2],c=[6,o(function(){return L(k)}),o(function(){return L(l)})];break;case 7:var m=a[1],r=a[2],c=[7,o(function(){return L(m)}),o(function(){return L(r)})];
break;case 8:var v=a[1],w=a[2],c=[8,o(function(){return L(v)}),o(function(){return L(w)})]}return c},[6,[4,c[1]],[4,c[2]]]]);break;case 6:a=p(A,[function(a){a=n(a);switch(a[0]){case 1:var c=[1];break;case 2:c=[2];break;case 3:c=[3,a[1]];break;case 4:var h=a[1],c=p(A,[Pb,o(function(){return L(h)})]);break;case 5:var i=a[1],j=a[2],c=[5,o(function(){return L(i)}),o(function(){return L(j)})];break;case 6:var k=a[1],l=a[2],c=[6,o(function(){return L(k)}),o(function(){return L(l)})];break;case 7:var m=
a[1],r=a[2],c=[7,o(function(){return L(m)}),o(function(){return L(r)})];break;case 8:var v=a[1],w=a[2],c=[8,o(function(){return L(v)}),o(function(){return L(w)})]}return c},[5,[4,c[1]],[4,c[2]]]]);break;default:a=n(a)}}else a=n(a);return a}function Xb(a){a=n(a);if(4==a[0])var c=n(a[1]),a=4==c[0]?n(c[1]):n(a);else a=n(a);return a}var Yb=o(function(){return p(H,[function(a){return K(Xb,a)},function(a){return K(L,a)}])}),Zb=o(function(){return p(H,[Qb,Yb])});
function M(a){var c=n(a);switch(c[0]){case 7:a=[6,[4,c[1]],c[2]];break;case 8:a=c[1];c=c[2];a=p(A,[function(a){a=n(a);switch(a[0]){case 1:var c=[1];break;case 2:c=[2];break;case 3:c=[3,a[1]];break;case 4:var h=a[1],c=p(A,[Pb,o(function(){return M(h)})]);break;case 5:var i=a[1],j=a[2],c=[5,o(function(){return M(i)}),o(function(){return M(j)})];break;case 6:var k=a[1],l=a[2],c=[6,o(function(){return M(k)}),o(function(){return M(l)})];break;case 7:var m=a[1],r=a[2],c=[7,o(function(){return M(m)}),o(function(){return M(r)})];
break;case 8:var v=a[1],w=a[2],c=[8,o(function(){return M(v)}),o(function(){return M(w)})]}return c},[5,[7,a,c],[7,c,a]]]);break;default:a=n(c)}return a}function $b(a){return K(M,a)}var ac=o(function(){return p(H,[Qb,$b])});function bc(a){a=n(a)[1];return n(a)}function N(a,c){var b=n(c);if(1==b[0])b=[1];else var e=b[1],h=b[2],b=[2,o(function(){return p(a,[e])}),o(function(){return N(a,h)})];return b}
function cc(a,c,b){b=n(b);if(1==b[0])b=[1];else var e=b[1],h=b[2],b=p(a,[c,e])?n(h):[2,e,o(function(){return cc(a,c,h)})];return b}function dc(a,c,b){return cc(o(function(){return D(a)}),c,b)}function ec(a,c,b){a:{for(;;){b=n(b);if(1==b[0]){a=n(c);break a}var e=b[2],c=dc(a,b[1],c),b=e}a=d}return a}
function fc(a,c){function b(c,h){for(;;){var i=n(h);if(1==i[0])i=[1];else{var j=i[2];if(p(a,[i[1]]))i=[2,[1,c],function(a,b,c){return o(function(){return b(a+1|0,c)})}(c,b,j)];else{c=c+1|0;h=j;continue}}return i}}return b(0,c)}function gc(a,c){return p(fc,[o(function(){return p(D,[a,c])})])}var hc=o(function(){return t("List.maximumBy: empty list")}),ic=o(function(){return s(hc)});
function jc(a,c){var b=n(c),e;if(1==b[0])e=n(ic);else a:{e=b[1];for(b=b[2];;){b=n(b);if(1==b[0]){e=n(e);break a}var h=b[2];e=function(a,b,c){return o(function(){return 3==p(c,[a,b])[0]?n(a):n(b)})}(e,b[1],a);b=h}e=d}return e}var kc=o(function(){return t("List.minimumBy: empty list")}),lc=o(function(){return s(kc)});
function mc(a,c){var b=n(c),e;if(1==b[0])e=n(lc);else a:{e=b[1];for(b=b[2];;){b=n(b);if(1==b[0]){e=n(e);break a}var h=b[2];e=function(a,b,c){return o(function(){return 3==p(c,[a,b])[0]?n(b):n(a)})}(e,b[1],a);b=h}e=d}return e}function nc(a,c,b){for(;;){b=n(b);if(1==b[0])a=g;else{var e=b[2];if(p(D,[a,c,b[1]]))a=f;else{b=e;continue}}return a}}
function oc(a,c){function b(c,h){for(var i;;){var j=n(c);if(1==j[0])i=[1];else if(i=j[1],j=j[2],nc(a,i,h)){c=j;continue}else i=[2,i,function(a,b,c,e){return o(function(){return e(c,[2,a,b])})}(i,h,j,b)];return i}}return b(c,u)}
function pc(a,c){function b(c){c=n(c);if(1==c[0])c=[1,u,u];else var e=c[1],j=c[2],k=o(function(){var a=b(j);return[1,a[1],a[2]]}),c=p(a,[e])?[1,[2,e,o(function(){var a=n(k)[1];return n(a)})],o(function(){var a=n(k)[2];return n(a)})]:[1,o(function(){var a=n(k)[1];return n(a)}),[2,e,o(function(){var a=n(k)[2];return n(a)})]];return c}var e=b(c);return[1,e[1],e[2]]}var qc=ba(0);function rc(a){a=n(a)[1];return n(a)}
function sc(a,c){var b;a:{b=c;for(var e=o(function(){return p(eb,[a,qc])});;){b=n(b);if(1==b[0]){b=n(e);break a}e=function(a,b,c){return o(function(){return p(rc,[b,a,c])})}(e,a,b[1]);b=b[2]}b=d}return b}function O(a){a=n(a)[2];return n(a)}function tc(a,c,b,e){return p(O,[a,o(function(){return p(c,[b])}),o(function(){return p(c,[e])})])}function uc(a,c){for(;;){var b=n(c);if(1==b[0])return n(a);var e=b[3],a=[2,b[2],function(a,b){return o(function(){return uc(a,b)})}(a,b[4])],c=e}}
function Q(a){return uc(u,a)}function vc(a,c,b){for(;;){var e=n(c);if(1==e[0])a=1==n(b)[0]?f:g;else{var c=e[1],e=e[2],h=n(b);if(1==h[0])a=g;else if(b=h[2],p(D,[a,c,h[1]])){c=e;continue}else a=g}return a}}function wc(a,c,b){function e(e){function h(j){if(e==j)var j=Q(b),k=Q(c),j=vc(a,k,j);else j=g;return j}var k=n(b);return 1==k[0]?h(0):h(k[1])}var h=n(c);return 1==h[0]?e(0):e(h[1])}function xc(a){a=n(a)[1];return n(a)}
function R(a,c,b){for(;;){var e=n(c);if(1==e[0])a=1==n(b)[0]?[2]:[1];else{var c=e[1],e=e[2],h=n(b);if(1==h[0])a=[3];else if(b=h[2],c=p(O,[a,c,h[1]]),2==c[0]){c=e;continue}else a=n(c)}return a}}
function yc(a){return[1,o(function(){var c=o(function(){return xc(a)});return[1,function(a,e){return wc(c,a,e)},function(a,e){return wc(c,a,e)?g:f}]}),function(c,b){var e=Q(b),h=Q(c);return R(a,h,e)},function(c,b){var e=Q(b),h=Q(c);return 1==R(a,h,e)[0]?f:g},function(c,b){var e=Q(b),h=Q(c);return 1==R(a,h,e)[0]?g:f},function(c,b){var e=Q(b),h=Q(c);return 3==R(a,h,e)[0]?f:g},function(c,b){var e=Q(b),h=Q(c);return 3==R(a,h,e)[0]?g:f},function(c,b){var e=Q(b),h=Q(c);return 3==R(a,h,e)[0]?n(c):n(b)},
function(c,b){var e=Q(b),h=Q(c);return 3==R(a,h,e)[0]?n(b):n(c)}]}var zc=[1],S=[1],Ac=o(function(){return t("Failure in Data.Map.balanceL")}),Bc=o(function(){return s(Ac)});
function Cc(a,c,b){var e=n(b);if(1==e[0])if(c=n(c),1==c[0])c=n(a),c=[2,1,n(c),n(S),n(S)];else{var h=c[1],i=c[2],b=c[4],j=n(c[3]);if(1==j[0])if(b=n(b),1==b[0])b=n(a),c=[2,2,n(b),n(c),n(S)];else var c=b[2],b=n(a),b=[2,1,n(b),n(S),n(S)],k=[2,1,n(i),n(S),n(S)],c=[2,3,n(c),n(k),n(b)];else{var l=j[1],c=n(b);if(1==c[0])c=n(a),c=[2,1,n(c),n(S),n(S)],c=[2,3,n(i),n(j),n(c)];else{var b=c[1],m=c[2],r=c[3],v=c[4];b<(q(2,l)|0)?(k=n(a),c=[2,1+b|0,n(k),n(c),n(S)],c=[2,1+h|0,n(i),n(j),n(c)]):(c=function(b){var c=
n(v);if(1==c[0])c=n(a),c=[2,1,n(c),n(S),n(S)];else var e=c[1],k=n(a),c=[2,1+e|0,n(k),n(c),n(S)];b=[2,(1+l|0)+b|0,n(i),n(j),n(r)];return b=[2,1+h|0,n(m),n(b),n(c)]},b=n(r),c=1==b[0]?c(0):c(b[1]))}}}else{var w=e[1],c=n(c);if(1==c[0])c=n(a),c=[2,1+w|0,n(c),n(S),n(e)];else{var B=c[1],E=c[2],b=c[3],k=c[4];if(B>(q(3,w)|0)){var J=n(b);if(1==J[0])c=n(Bc);else{var I=J[1],c=n(k);if(1==c[0])c=n(Bc);else{var b=c[1],T=c[2],P=c[3],Z=c[4];b<(q(2,I)|0)?(k=n(a),c=[2,(1+w|0)+b|0,n(k),n(c),n(e)],c=[2,(1+B|0)+w|0,n(E),
n(J),n(c)]):(c=function(b){var c=n(Z);if(1==c[0])c=n(a),c=[2,1+w|0,n(c),n(S),n(e)];else var h=c[1],i=n(a),c=[2,(1+w|0)+h|0,n(i),n(c),n(e)];b=[2,(1+I|0)+b|0,n(E),n(J),n(P)];return b=[2,(1+B|0)+w|0,n(T),n(b),n(c)]},b=n(P),c=1==b[0]?c(0):c(b[1]))}}}else b=n(a),c=[2,(1+B|0)+w|0,n(b),n(c),n(e)]}}return c}var Dc=o(function(){return t("Failure in Data.Map.balanceR")}),Ec=o(function(){return s(Dc)});
function Fc(a,c,b){var e=n(c);if(1==e[0])if(c=n(b),1==c[0])c=n(a),c=[2,1,n(c),n(S),n(S)];else{var h=c[1],i=c[2],j=c[4],b=n(c[3]);if(1==b[0])b=n(j),1==b[0]?(b=n(a),c=[2,2,n(b),n(S),n(c)]):(c=n(a),c=[2,1,n(c),n(S),n(S)],c=[2,3,n(i),n(c),n(b)]);else{var c=b[1],k=b[2],l=b[3],m=b[4],r=n(j);if(1==r[0])b=n(a),c=[2,1,n(i),n(S),n(S)],b=[2,1,n(b),n(S),n(S)],c=[2,3,n(k),n(b),n(c)];else{var v=r[1];c<(q(2,v)|0)?(j=n(a),c=[2,1+c|0,n(j),n(S),n(b)],c=[2,1+h|0,n(i),n(c),n(r)]):(c=function(b){var c=n(a),e=n(m),e=1==
e[0]?[2,1+v|0,n(i),n(S),n(r)]:[2,(1+v|0)+e[1]|0,n(i),n(e),n(r)],b=[2,1+b|0,n(c),n(S),n(l)];return b=[2,1+h|0,n(k),n(b),n(e)]},b=n(l),c=1==b[0]?c(0):c(b[1]))}}}else{var w=e[1],b=n(b);if(1==b[0])c=n(a),c=[2,1+w|0,n(c),n(e),n(S)];else{var B=b[1],E=b[2],j=b[3],c=b[4];if(B>(q(3,w)|0))if(b=n(j),1==b[0])c=n(Ec);else{var j=b[1],J=b[2],I=b[3],T=b[4],P=n(c);if(1==P[0])c=n(Ec);else{var Z=P[1];j<(q(2,Z)|0)?(c=n(a),c=[2,(1+w|0)+j|0,n(c),n(e),n(b)],c=[2,(1+w|0)+B|0,n(E),n(c),n(P)]):(c=function(b){var c=n(a),h=
n(T),h=1==h[0]?[2,1+Z|0,n(E),n(S),n(P)]:[2,(1+Z|0)+h[1]|0,n(E),n(h),n(P)],b=[2,(1+w|0)+b|0,n(c),n(e),n(I)];return b=[2,(1+w|0)+B|0,n(J),n(b),n(h)]},b=n(I),c=1==b[0]?c(0):c(b[1]))}}else c=n(a),c=[2,(1+w|0)+B|0,n(c),n(e),n(b)]}}return c}function Gc(a,c){var b=n(c);if(1==b[0])var e=n(a),e=[2,1,n(e),n(S),n(S)];else var e=b[2],h=b[3],b=Gc(a,b[4]),e=Fc(e,h,b);return e}function Hc(a,c){var b=n(c);if(1==b[0])var e=n(a),e=[2,1,n(e),n(S),n(S)];else var e=b[2],h=b[4],b=Hc(a,b[3]),e=Cc(e,b,h);return e}
function Ic(a,c,b,e,h,i){c=n(c);if(1==c[0])b=[2,b,n(e),n(h),n(i)],b=Hc(a,b);else{var j=c[1],k=c[2],l=c[3],m=c[4];(q(3,j)|0)<b?(b=Jc(a,j,k,l,m,h),b=Cc(e,b,i)):(q(3,b)|0)<j?(b=Ic(a,m,b,e,h,i),b=Fc(k,l,b)):(a=n(a),e=[2,b,n(e),n(h),n(i)],b=[2,(j+b|0)+1|0,n(a),n(c),n(e)])}return b}
function Jc(a,c,b,e,h,i){i=n(i);if(1==i[0])c=[2,c,n(b),n(e),n(h)],c=Gc(a,c);else{var j=i[1],k=i[2],l=i[3],m=i[4];(q(3,c)|0)<j?(c=Jc(a,c,b,e,h,l),c=Cc(k,c,m)):(q(3,j)|0)<c?(c=Ic(a,h,j,k,l,m),c=Fc(b,e,c)):(a=n(a),b=[2,c,n(b),n(e),n(h)],c=[2,(c+j|0)+1|0,n(a),n(b),n(i)])}return c}
function Kc(a,c,b){c=n(c);if(1==c[0])a=Hc(a,b);else{var e=c[1],h=c[2],i=c[3],j=c[4],b=n(b);if(1==b[0])a=Gc(a,c);else{var k=b[1],l=b[2],m=b[3],r=b[4];(q(3,e)|0)<k?(a=Jc(a,e,h,i,j,m),a=Cc(l,a,r)):(q(3,k)|0)<e?(a=Ic(a,j,k,l,m,r),a=Fc(h,i,a)):(a=n(a),a=[2,(e+k|0)+1|0,n(a),n(c),n(b)])}}return a}
function Lc(a,c,b){b=n(b);if(1==b[0])b=[1,a,c];else var e=b[2],h=b[3],i=b[4],j=o(function(){return Lc(e,h,i)}),b=[1,o(function(){var a=n(j)[1];return n(a)}),o(function(){var b=n(j)[2];return Cc(a,c,b)})];return b}function Mc(a,c,b){c=n(c);if(1==c[0])c=[1,a,b];else var e=c[2],h=c[3],i=c[4],j=o(function(){return Mc(e,h,i)}),c=[1,o(function(){var a=n(j)[1];return n(a)}),o(function(){var c=n(j)[2];return Fc(a,c,b)})];return c}
function Nc(a,c){var b=n(a);if(1==b[0])b=n(c);else{var e=b[1],h=b[2],i=b[3],j=b[4],k=n(c);if(1==k[0])b=n(b);else{var l=k[2],m=k[3],r=k[4];e>k[1]?(b=Lc(h,i,j),b=Fc(b[1],b[2],k)):(k=Mc(l,m,r),b=Cc(k[1],b,k[2]))}}return b}function Oc(a,c,b,e,h){a=n(a);if(1==a[0])b=[2,c,n(b),n(e),n(h)];else{var i=a[1],j=a[2],k=a[3],l=a[4];(q(3,i)|0)<c?(c=Pc(i,j,k,l,e),b=Cc(b,c,h)):(q(3,c)|0)<i?(b=Oc(l,c,b,e,h),b=Fc(j,k,b)):(b=[2,c,n(b),n(e),n(h)],b=Nc(a,b))}return b}
function Pc(a,c,b,e,h){h=n(h);if(1==h[0])c=[2,a,n(c),n(b),n(e)];else{var i=h[1],j=h[2],k=h[3],l=h[4];(q(3,a)|0)<i?(c=Pc(a,c,b,e,k),c=Cc(j,c,l)):(q(3,i)|0)<a?(a=Oc(e,i,j,k,l),c=Fc(c,b,a)):(c=[2,a,n(c),n(b),n(e)],c=Nc(c,h))}return c}
function Qc(a,c,b){var e=n(b);if(1==e[0])a=[1];else{var b=e[2],h=e[3],e=e[4];if(p(c,[b]))e=Qc(a,c,e),a=Qc(a,c,h),a=Kc(b,a,e);else{var i=Qc(a,c,e),a=Qc(a,c,h),b=n(a);if(1==b[0])a=n(i);else{var h=b[1],a=b[2],c=b[3],e=b[4],j=n(i);if(1==j[0])a=n(b);else{var k=j[1],i=j[2],l=j[3],m=j[4];(q(3,h)|0)<k?(a=Pc(h,a,c,e,l),a=Cc(i,a,m)):(q(3,k)|0)<h?(b=Oc(e,k,i,l,m),a=Fc(a,c,b)):a=Nc(b,j)}}}}return a}
function Rc(a,c,b){function e(b,c){for(;;){var j=n(c);if(1==j[0])return n(b);var k=j[3],b=function(a,b,c,e,h){return o(function(){return p(h,[b,o(function(){return e(a,c)})])})}(b,j[2],j[4],e,a),c=k}}return e(c,b)}function Sc(a,c,b){function e(b,c){var j=n(b),k=n(c);if(1==k[0])var l=[2,1,n(j),n(S),n(S)];else{var m=k[1],l=k[2],r=k[3],k=k[4];switch(p(O,[a,j,l])[0]){case 1:var r=e(j,r),v=Cc(l,r,k);break;case 2:v=[2,m,n(j),n(r),n(k)];break;case 3:j=e(j,k),v=Fc(l,r,j)}l=v}return l}return e(c,b)}
function Tc(a,c){var b;a:{b=S;for(var e=c;;){e=n(e);if(1==e[0]){b=n(b);break a}var h=e[2];b=Sc(a,e[1],b);e=h}b=d}return b}var Uc=[1,S,Wa,S];
function Vc(a,c,b){b=n(b);if(1==b[0])var e=n(Uc);else{var h=b[2],i=b[3],j=b[4];switch(p(O,[a,c,h])[0]){case 1:var k=o(function(){return Vc(a,c,i)}),e=[1,o(function(){var a=n(k)[1];return n(a)}),o(function(){var a=n(k)[2];return n(a)}),o(function(){var a=n(k)[3];return Kc(h,a,j)})];break;case 2:e=[1,i,[2,h],j];break;case 3:var l=o(function(){return Vc(a,c,j)}),e=[1,o(function(){var a=n(l)[1];return Kc(h,i,a)}),o(function(){var a=n(l)[2];return n(a)}),o(function(){var a=n(l)[3];return n(a)})]}}return e}
function Wc(a,c,b){for(;;){var e=n(c);if(1==e[0])a=f;else{var h=e[2],c=e[3],e=e[4],b=n(b);if(1==b[0])a=g;else{var h=Vc(a,h,b),i=h[1],b=h[3];if(1==n(h[2])[0])a=g;else if(Wc(a,c,i)){c=e;continue}else a=g}}return a}}function Xc(a,c,b){function e(e){var h=n(b);return 1==h[0]?0>=e?Wc(a,c,S):g:e<=h[1]?Wc(a,c,h):g}var h=n(c);return 1==h[0]?e(0):e(h[1])}function Yc(a,c,b,e){a=Q(e);b=N(b,a);return Tc(c,b)}var Zc=o(function(){return n(Q)}),$c=[1];function ad(a){a=n(a)[6];return n(a)}
function bd(a){a=n(a)[4];return n(a)}
function cd(a,c,b,e){c=n(c);if(1==c[0])if(c=n(b),1==c[0])a=n(e);else a:{for(c=c[1];;){e=n(e);if(1==e[0])a=[1];else if(b=e[3],p(bd,[a,e[2],c])){e=b;continue}else a=n(e);break a}a=d}else if(c=c[1],b=n(b),1==b[0])a:{for(;;){e=n(e);if(1==e[0])a=[1];else if(b=e[4],p(ad,[a,e[2],c])){e=b;continue}else a=n(e);break a}a=d}else a:{for(b=b[1];;){e=n(e);if(1==e[0])a=[1];else{var h=e[2],i=e[3],j=e[4];if(p(ad,[a,h,c])){e=j;continue}else if(p(bd,[a,h,b])){e=i;continue}else a=n(e)}break a}a=d}return a}
function dd(a,c,b,e,h){h=n(h);if(1==h[0])c=n(e);else{var i=h[2],j=h[3],k=h[4],e=n(e);if(1==e[0]){b=n(b);if(1==b[0])b=n(k);else var l=function(b,c){for(;;){var e=n(c);if(1==e[0])var h=[1];else{var h=e[2],i=e[3],e=e[4];switch(p(O,[a,h,b])[0]){case 1:var j=l(b,e),j=Kc(h,i,j);break;case 2:j=n(i);break;case 3:c=i;continue}h=j}return h}},b=l(b[1],k);c=n(c);if(1==c[0])c=n(j);else var m=function(b,c){for(;;){var e=n(c);if(1==e[0])var h=[1];else{var h=e[2],i=e[3],e=e[4];switch(p(O,[a,b,h])[0]){case 1:var i=
m(b,i),j=Kc(h,i,e);break;case 2:j=n(e);break;case 3:c=e;continue}h=j}return h}},c=m(c[1],j)}else var i=e[2],j=e[3],e=e[4],k=[2,n(i)],r=cd(a,k,b,h),b=dd(a,k,b,e,r),h=cd(a,c,k,h),c=dd(a,c,k,j,h);c=Kc(i,c,b)}return c}
function ed(a,c,b){var e=n(c);if(1==e[0])b=n(b);else{var c=e[2],h=e[3],i=e[4],j=n(b);if(1==j[0])b=n(e);else var k=j[2],l=j[3],m=j[4],b=o(function(){var b;if(1==n(l)[0])if(1==n(m)[0]){var c=function(b,e){var h=n(b),i=n(e);if(1==i[0])var j=[2,1,n(h),n(S),n(S)];else{var j=i[2],k=i[3],m=i[4];switch(p(O,[a,h,j])[0]){case 1:var k=c(h,k),l=Cc(j,k,m);break;case 2:l=n(i);break;case 3:m=c(h,m),l=Fc(j,k,m)}j=l}return j};b=c(k,e)}else b=dd(a,$c,$c,e,j);else b=dd(a,$c,$c,e,j);return b}),b=1==n(h)[0]?1==n(i)[0]?
Sc(a,c,j):n(b):n(b)}return b}function fd(a){a=n(a)[2];return n(a)}var gd=[1,C,function(a,c){var b=n(a)[1],e=n(c)[1];return b<e?[1]:b==e?[2]:[3]},function(a,c){var b=n(a)[1],e=n(c)[1];return b<e},function(a,c){var b=n(a)[1],e=n(c)[1];return b>=e},function(a,c){var b=n(a)[1],e=n(c)[1];return b>e},function(a,c){var b=n(a)[1],e=n(c)[1];return b<=e},function(a,c){var b=n(a),e=b[1],h=n(c);return e<=h[1]?n(h):n(b)},function(a,c){var b=n(a),e=b[1],h=n(c);return e<=h[1]?n(b):n(h)}];
function hd(a){return[1,function(c,b){return vc(a,c,b)},function(c,b){return vc(a,c,b)?g:f}]}function id(a){return[1,o(function(){return hd(o(function(){return xc(a)}))}),function(c,b){return R(a,c,b)},function(c,b){return 1==R(a,c,b)[0]?f:g},function(c,b){return 1==R(a,c,b)[0]?g:f},function(c,b){return 3==R(a,c,b)[0]?f:g},function(c,b){return 3==R(a,c,b)[0]?g:f},function(c,b){return 3==R(a,c,b)[0]?n(c):n(b)},function(c,b){return 3==R(a,c,b)[0]?n(b):n(c)}]}function jd(a){return n(a)?g:f}
function kd(a){a=n(a);if(1==a[0])a=[1];else var c=a[2],a=x(a[1],o(function(){return kd(c)}));return a}function ld(a){return kd(a)}function md(a,c){for(;;){var b=n(c);if(1==b[0])var e=[1];else if(e=b[1],b=b[2],p(a,[e]))e=[2,e,function(a,b){return o(function(){return md(a,b)})}(a,b)];else{c=b;continue}return e}}function U(a){a:{for(var c=0;;){a=n(a);if(1==a[0]){a=n(c);break a}c=c+1|0;a=a[2]}a=d}return[1,a]}
function nd(a,c){return[1,function(b,e){var h=n(a)[1],i=n(b),j=i[1],i=i[2],k=n(e);return p(h,[j,k[1]])?p(D,[c,i,k[2]]):g},function(b,e){var h=n(a)[1],i=n(b),j=i[1],i=i[2],k=n(e);return p(h,[j,k[1]])?p(D,[c,i,k[2]])?g:f:f}]}function od(a,c){return p(jd,[o(function(){return p(D,[pd,a,c])})])}function qd(a,c){switch(n(a)[0]){case 1:switch(n(c)[0]){case 1:var b=f;break;case 2:b=g;break;case 3:b=g}var e=b;break;case 2:e=2==n(c)[0]?f:g;break;case 3:e=3==n(c)[0]?f:g}return e}
var pd=o(function(){return[1,qd,od]}),rd=o(function(){return p(hd,[pd])}),sd=o(function(){return p(hd,[C])}),td=o(function(){return p(nd,[rd,sd])});function ud(a){a=n(a)[3];return n(a)}function vd(a){a=n(a)[5];return n(a)}
function wd(a,c){return[1,o(function(){return nd(o(function(){return xc(a)}),o(function(){return xc(c)}))}),function(b,e){var h=n(a)[2],i=n(b),j=i[1],i=i[2],k=n(e),l=k[2];switch(p(h,[j,k[1]])[0]){case 1:var m=[1];break;case 2:m=p(O,[c,i,l]);break;case 3:m=[3]}return m},function(b,e){var h=n(a)[2],i=n(b),j=i[1],i=i[2],k=n(e),l=k[2];switch(p(h,[j,k[1]])[0]){case 1:var m=f;break;case 2:m=p(ud,[c,i,l]);break;case 3:m=g}return m},function(b,e){var h=n(a)[2],i=n(b),j=i[1],i=i[2],k=n(e),l=k[2];switch(p(h,
[j,k[1]])[0]){case 1:var m=g;break;case 2:m=p(bd,[c,i,l]);break;case 3:m=f}return m},function(b,e){var h=n(a)[2],i=n(b),j=i[1],i=i[2],k=n(e),l=k[2];switch(p(h,[j,k[1]])[0]){case 1:var m=g;break;case 2:m=p(vd,[c,i,l]);break;case 3:m=f}return m},function(b,e){var h=n(a)[2],i=n(b),j=i[1],i=i[2],k=n(e),l=k[2];switch(p(h,[j,k[1]])[0]){case 1:var m=f;break;case 2:m=p(ad,[c,i,l]);break;case 3:m=g}return m},function(b,e){var h=n(a)[2],i=n(b),j=i[1],i=i[2],k=n(e),l=k[1],k=k[2];switch(p(h,[j,l])[0]){case 1:var m=
[1,l,k];break;case 2:m=p(ad,[c,i,k])?[1,l,k]:[1,j,i];break;case 3:m=[1,j,i]}return m},function(b,e){var h=n(a)[2],i=n(b),j=i[1],i=i[2],k=n(e),l=k[1],k=k[2];switch(p(h,[j,l])[0]){case 1:var m=[1,j,i];break;case 2:m=p(ad,[c,i,k])?[1,j,i]:[1,l,k];break;case 3:m=[1,l,k]}return m}]}function xd(a,c){switch(n(a)[0]){case 1:switch(n(c)[0]){case 1:var b=g;break;case 2:b=f;break;case 3:b=f}var e=b;break;case 2:e=3==n(c)[0]?f:g;break;case 3:n(c),e=g}return e}
function yd(a,c){switch(n(a)[0]){case 1:n(c);var b=f;break;case 2:switch(n(c)[0]){case 1:var e=g;break;case 2:e=f;break;case 3:e=f}b=e;break;case 3:b=3==n(c)[0]?f:g}return b}function zd(a,c){switch(n(a)[0]){case 1:n(c);var b=g;break;case 2:switch(n(c)[0]){case 1:var e=f;break;case 2:e=g;break;case 3:e=g}b=e;break;case 3:b=3==n(c)[0]?g:f}return b}
function Ad(a,c){switch(n(a)[0]){case 1:switch(n(c)[0]){case 1:var b=f;break;case 2:b=g;break;case 3:b=g}var e=b;break;case 2:e=3==n(c)[0]?g:f;break;case 3:n(c),e=f}return e}function Bd(a,c){switch(n(a)[0]){case 1:switch(n(c)[0]){case 1:var b=[2];break;case 2:b=[1];break;case 3:b=[1]}var e=b;break;case 2:switch(n(c)[0]){case 1:var h=[3];break;case 2:h=[2];break;case 3:h=[1]}e=h;break;case 3:e=3==n(c)[0]?[2]:[3]}return e}function Cd(a,c,b){return p(ad,[a,c,b])?n(b):n(c)}
var Ed=o(function(){return p(Cd,[Dd])});function Fd(a,c,b){return p(ad,[a,c,b])?n(c):n(b)}var Gd=o(function(){return p(Fd,[Dd])}),Dd=o(function(){return[1,pd,Bd,xd,Ad,zd,yd,Ed,Gd]}),Hd=o(function(){return p(id,[Dd])}),Id=o(function(){return p(id,[gd])}),Jd=o(function(){return p(wd,[Hd,Id])}),Kd=[3],Ld=o(function(){return t("Prelude.(!!): negative index\n")}),Md=o(function(){return s(Ld)}),Nd=o(function(){return t("Prelude.(!!): index too large\n")}),Od=o(function(){return s(Nd)});
function Pd(a,c){var b=n(c)[1];if(0>b)b=n(Md);else a:{for(var e=a;;){var h=n(e);if(1==h[0])b=n(Od);else if(e=h[1],h=h[2],b=n(b)){b=b-1|0;e=h;continue}else b=n(e);break a}b=d}return b}var Qd=o(function(){return t(": empty list")}),Rd=o(function(){return t("Prelude.")});function Sd(a){var c=x(Rd,o(function(){return x(a,Qd)}));return s(c)}var Td=o(function(){return t("head")}),Ud=o(function(){return Sd(Td)});function Vd(a){a=n(a);return 1==a[0]?n(Ud):n(a[1])}
function Wd(a){function c(a,b){var e=n(b);if(1==e[0])e=n(zc);else{var k=e[1],e=n(e[2]);if(1==e[0])e=n(k);else var l=e[1],e=p(A,[function(b){return c(a,b)},[2,o(function(){var b=o(function(){return p(yc,[a])}),c=o(function(){var b=o(function(){return p(yc,[a])});return p(Rc,[function(c,e){return p(ed,[b,o(function(){var b=o(function(){return p(yc,[a])});return p(Rc,[function(e,i){return p(Sc,[b,o(function(){return p(ed,[a,c,e])}),i])},zc,l])}),e])},zc,k])});return p(Rc,[function(c){return p(A,[o(function(){return p(Qc,
[b])}),o(function(){return p(H,[jd,o(function(){return p(Xc,[a,c])})])})])},c,c])}),e[2]]])}return e}var b=o(function(){return p(A,[o(function(){return p(oc,[td])}),o(function(){return p(N,[o(function(){return p(Pd,[a])}),o(function(){return p(A,[o(function(){return p(N,[Vd])}),o(function(){return p(md,[o(function(){return p(H,[o(function(){return p(D,[C,[1,1]])}),U])}),o(function(){return p(N,[function(b){return p(fc,[o(function(){return p(H,[o(function(){return p(nc,[C,b])}),fd])}),a])},o(function(){return p(A,
[o(function(){return p(H,[o(function(){return p(oc,[C])}),o(function(){return p(H,[ld,o(function(){return p(N,[fd])})])})])}),a])})])})])})])})])})])}),e=o(function(){return p(ec,[td,a,b])});return p(x,[b,o(function(){return p(A,[function(a){var b=n(a);return 1==b[0]?[1]:p(jc,[o(function(){return p(A,[o(function(){return p(tc,[gd])}),o(function(){return p(H,[o(function(){return p(sc,[db])}),o(function(){return p(N,[o(function(){return p(H,[U,o(function(){return p(H,[o(function(){return p(gc,[pd,Kd])}),
bc])})])})])})])})])}),o(function(){var a=p(pc,[o(function(){return p(H,[o(function(){return p(D,[C,o(function(){return p(A,[U,o(function(){return p(mc,[o(function(){return p(tc,[gd,U])}),b])})])})])}),U])}),b])[1];return n(a)})])},o(function(){return p(A,[o(function(){return p(H,[Zc,o(function(){return p(Yc,[o(function(){return p(yc,[Jd])}),o(function(){return p(id,[Jd])}),Zc])})])}),o(function(){return p(A,[function(a){return c(Jd,a)},o(function(){return p(A,[o(function(){return p(N,[o(function(){return p(H,
[o(function(){return p(Tc,[o(function(){return p(yc,[Jd])})])}),o(function(){return p(N,[o(function(){return p(Tc,[Jd])})])})])})])}),o(function(){function a(b){b=n(b);if(1==b[0])b=[1];else var c=b[1],k=b[2],b=[2,o(function(){return p(A,[o(function(){return p(N,[function(a){return[2,a,u]}])}),o(function(){return p(md,[o(function(){return p(H,[o(function(){return p(nc,[C,c])}),fd])}),e])})])}),o(function(){return a(k)})];return b}return a(o(function(){return p(A,[o(function(){return p(oc,[C])}),o(function(){return p(ld,
[o(function(){return p(N,[fd,e])})])})])}))})])})])})])})])})])}function Xd(a,c,b){return p(a,[b,c])}function Yd(a,c){if(a>c)var b=[1];else var e=function(a){return[2,[1,a],o(function(){return a==c?[1]:e(a+1|0)})]},b=e(a);return b}function Zd(a,c,b){return b>c?b>a?[1]:[2,[1,a],u]:[2,[1,a],o(function(){function e(a){return a<i?[2,[1,a],u]:[2,[1,a],o(function(){return e(a+h|0)})]}var h=c-a|0,i=b-h|0;return e(c)})]}
function $d(a,c,b){return b<c?b<a?[1]:[2,[1,a],u]:[2,[1,a],o(function(){function e(a){return a>i?[2,[1,a],u]:[2,[1,a],o(function(){return e(a+h|0)})]}var h=c-a|0,i=b-h|0;return e(c)})]}function ae(a){return n(a)}
var be=o(function(){return t("Prelude.Enum.pred{Int}: tried to take `pred' of minBound")}),ce=o(function(){return s(be)}),de=o(function(){return t("Prelude.Enum.succ{Int}: tried to take `succ' of maxBound")}),ee=o(function(){return s(de)}),fe=[1,function(a){a=n(a)[1];a=n(a);return 2147483647==a?n(ee):[1,a+1|0]},function(a){a=n(a)[1];a=n(a);return-2147483648==a?n(ce):[1,a-1|0]},ae,ae,function(a){a=n(a)[1];return Yd(a,2147483647)},function(a,c){var b=n(a)[1],e=n(c)[1];return e>=b?$d(b,e,2147483647):
Zd(b,e,-2147483648)},function(a,c){var b=n(a)[1],e=n(c)[1];return Yd(b,e)},function(a,c,b){a=n(a)[1];c=n(c)[1];b=n(b)[1];return c>=a?$d(a,c,b):Zd(a,c,b)}];function ge(a){a=n(a)[5];return n(a)}function he(a,c){var b=n(a);if(1==b[0])var e=[1];else{var e=b[1],h=b[2],b=n(c);if(1==b[0])e=[1];else var i=b[2],e=[2,[1,e,b[1]],o(function(){return he(h,i)})]}return e}function ie(a,c,b,e){return p(a,[o(function(){return p(c,[b])}),o(function(){return p(c,[e])})])}
function je(a,c,b){var e=o(function(){return D(a)});return x(c,o(function(){function a(b,c){for(var i;;){var j=n(b);if(1==j[0])i=[1];else{i=j[1];var j=j[2],k;a:{k=e;for(var B=i,E=c;;){E=n(E);if(1==E[0])k=g;else{var J=E[2];if(p(k,[B,E[1]]))k=f;else{E=J;continue}}break a}k=d}if(k){b=j;continue}else i=[2,i,function(a,b,c,e){return o(function(){return e(c,[2,a,b])})}(i,c,j,a)]}return i}}var i;a:{i=a(b,u);for(var j=c;;){j=n(j);if(1==j[0]){i=n(i);break a}var k=j[2];i=cc(e,j[1],i);j=k}i=d}return i}))}
function ke(a,c){return n(a)?n(c):g}function le(a){a=n(a)[2];return n(a)}function me(a,c,b){for(;;){b=n(b);if(1==b[0])a=f;else{var e=b[2];if(p(le,[a,c,b[1]])){b=e;continue}else a=g}return a}}function ne(a){return 1==n(a)[0]?f:g}function oe(a,c,b){c=n(c);if(1==c[0])b=[1];else{var e=c[1],h=c[2],b=n(b);if(1==b[0])b=[1];else var i=b[1],j=b[2],b=[2,o(function(){return p(a,[e,i])}),o(function(){return oe(a,h,j)})]}return b}
function pe(a){var c=o(function(){return p(Xd,[he,o(function(){function a(b){b=n(b);if(1==b[0])b=[1];else var c=b[2],b=[2,[2,b[1],u],o(function(){return a(c)})];return b}return a(o(function(){return p(ge,[fe,[1,0]])}))}),a])});a:{for(var b=c,e=u,h=u;;){var i=n(b);if(1==i[0]){h=n(h);if(1==h[0]){c=p(A,[function(){return o(function(){return p(oc,[td])})}(),function(a,b){return o(function(){return p(x,[a,b])})}(e,c)]);break a}e=function(a,b){return o(function(){return p(x,[a,b])})}(e,c);c=b=h;h=u}else var b=
i[2],j=n(i[1]),i=j[1],j=j[2],k=function(a,b,c){return o(function(){return p(md,[function(c){var e=n(c)[1];return p(ke,[o(function(){return p(a,[b,e])}),o(function(){return p(D,[C,o(function(){return p(A,[o(function(){return p(H,[U,o(function(){return p(md,[jd])})])}),o(function(){return p(oe,[o(function(){return D(pd)}),b,e])})])}),[1,1]])})])},c])})}(function(){return o(function(){return p(ie,[o(function(){return D(sd)}),o(function(){return p(gc,[pd,Kd])})])})}(),i,b),h=function(a,b,c,e,h){return o(function(){return p(x,
[a,o(function(){return p(N,[function(a){var a=n(a),e=a[1],i=a[2];return[1,o(function(){return p(b,[c,e])}),o(function(){return p(je,[C,h,i])})]},e])})])})}(h,function(){return o(function(){return p(oe,[function(a,b){return p(D,[pd,a,b])?n(a):[3]}])})}(),i,k,j),l=function(a,b,c,e){return o(function(){if(p(A,[jd,o(function(){return p(ne,[c])})]))var h=[2,[1,b,e],c],i=p(md,[function(a){return p(me,[td,a,h])},a]);else i=n(a);return i})}(c,i,k,j),e=function(a,b,c,e,h){return o(function(){return p(ke,[o(function(){return p(ne,
[e])}),o(function(){return p(nc,[td,[1,c,h],b])})])?[2,[1,c,h],a]:n(a)})}(e,c,i,k,j),c=l}c=d}return c}function qe(a){a=n(a);if(1==a[0])a=[1];else var c=a[2],a=[2,n(a[1])[2],o(function(){return qe(c)})];return a}function re(a,c){for(;;){var b=n(c);if(1==b[0])return n(a);var e=b[4],a=[2,[1,b[2],b[3]],function(a,b){return o(function(){return re(a,b)})}(a,b[5])],c=e}}function V(a){return re(u,a)}function se(a){a=V(a);return qe(a)}function te(a){return n(a)?[1]:[2]}
var ue=o(function(){return p(H,[o(function(){return p(N,[te])}),se])}),ve=o(function(){return p(N,[ue])});function we(a){a=n(a)[2];return n(a)}function xe(a){return n(a)}function ye(a){return p(we,[ze,a,xe])}function Ae(a){a=n(a)[3];return n(a)}function Be(a,c){return p(Ae,[ze,o(function(){return p(H,[o(function(){var b=n(a)[2];return n(b)}),c])}),o(function(){var b=n(a)[1];return n(b)})])}var Ce=o(function(){return t("foldl1")}),De=o(function(){return Sd(Ce)});
function Ee(a,c,b){a:{for(;;){b=n(b);if(1==b[0]){a=n(c);break a}var e=b[2],c=function(a,b,c){return o(function(){return p(c,[a,b])})}(c,b[1],a),b=e}a=d}return a}function Fe(a,c){var b=n(c);return 1==b[0]?n(De):Ee(a,b[1],b[2])}function Ge(a,c,b){function e(b){b=n(b);if(1==b[0])b=n(c);else var i=b[2],b=p(a,[b[1],o(function(){return e(i)})]);return b}return e(b)}function He(a,c,b){b=n(b);if(1==b[0])c=n(c);else var e=b[1],h=b[2],c=p(a,[c,o(function(){return He(a,e,h)})]);return c}
var Ie=o(function(){return t("foldr1")}),Je=o(function(){return Sd(Ie)});function Ke(a,c){var b=n(c);if(1==b[0])var e=n(Je);else if(e=b[1],b=n(b[2]),1==b[0])e=n(e);else var h=b[1],i=b[2],e=p(a,[e,o(function(){return He(a,h,i)})]);return e}var ze=o(function(){return[1,ye,Be,Ge,Ee,Ke,Fe]});function Le(a){a=n(a)[5];return n(a)}function Me(a,c){return[5,a,c]}function Ne(a,c){return[6,a,c]}
var Oe=[1,function(a,c){var b=n(a)[1],e=n(c)[1];return b==e},function(a,c){var b=n(a)[1],e=n(c)[1];return b!=e}],Pe=[1,Oe,function(a,c){var b=n(a)[1],e=n(c)[1];return b==e?[2]:b<=e?[1]:[3]},function(a,c){var b=n(a)[1],e=n(c)[1];return b<e},function(a,c){var b=n(a)[1],e=n(c)[1];return b>=e},function(a,c){var b=n(a)[1],e=n(c)[1];return b>e},function(a,c){var b=n(a)[1],e=n(c)[1];return b<=e},function(a,c){var b=n(a),e=b[1],h=n(c);return e<=h[1]?n(h):n(b)},function(a,c){var b=n(a),e=b[1],h=n(c);return e<=
h[1]?n(b):n(h)}],Qe=o(function(){return p(id,[Pe])});function Re(a,c){var b=n(a);return 3==b[0]?p(Sc,[Qe,b[1],c]):n(c)}var Se=[2],Te=[1];
function Ue(a,c,b){b=n(b);switch(b[0]){case 1:var e=p(a,[Te,c]);break;case 2:e=p(a,[Se,c]);break;case 3:e=p(a,[b,c]);break;case 4:var h=b[1],e=p(a,[b,o(function(){return Ue(a,c,h)})]);break;case 5:var i=b[1],j=b[2],e=p(a,[b,o(function(){return Ue(a,o(function(){return Ue(a,c,j)}),i)})]);break;case 6:var k=b[1],l=b[2],e=p(a,[b,o(function(){return Ue(a,o(function(){return Ue(a,c,l)}),k)})]);break;case 7:var m=b[1],r=b[2],e=p(a,[b,o(function(){return Ue(a,o(function(){return Ue(a,c,r)}),m)})]);break;
case 8:var v=b[1],w=b[2],e=p(a,[b,o(function(){return Ue(a,o(function(){return Ue(a,c,w)}),v)})])}return e}function Ve(a){a=n(a);if(1==a[0])a=[1];else var c=a[2],a=[2,n(a[1])[1],o(function(){return Ve(c)})];return a}function We(a){a=V(a);return Ve(a)}var W=[1],Xe=o(function(){return t("Failure in Data.Map.balanceL")}),Ye=o(function(){return s(Xe)});
function Ze(a,c,b,e){var h=n(e);if(1==h[0])if(b=n(b),1==b[0])b=n(a),b=[2,1,n(b),c,n(W),n(W)];else{var i=b[1],j=b[2],k=b[3],e=b[5],l=n(b[4]);if(1==l[0])if(e=n(e),1==e[0])e=n(a),b=[2,2,n(e),c,n(b),n(W)];else var b=e[2],e=e[3],m=n(a),m=[2,1,n(m),c,n(W),n(W)],r=[2,1,n(j),k,n(W),n(W)],b=[2,3,n(b),e,n(r),n(m)];else{var v=l[1],b=n(e);if(1==b[0])b=n(a),b=[2,1,n(b),c,n(W),n(W)],b=[2,3,n(j),k,n(l),n(b)];else{var e=b[1],w=b[2],B=b[3],E=b[4],J=b[5];e<(q(2,v)|0)?(m=n(a),b=[2,1+e|0,n(m),c,n(b),n(W)],b=[2,1+i|0,
n(j),k,n(l),n(b)]):(b=function(b){var e=n(J);if(1==e[0])e=n(a),e=[2,1,n(e),c,n(W),n(W)];else var h=e[1],m=n(a),e=[2,1+h|0,n(m),c,n(e),n(W)];b=[2,(1+v|0)+b|0,n(j),k,n(l),n(E)];return b=[2,1+i|0,n(w),B,n(b),n(e)]},e=n(E),b=1==e[0]?b(0):b(e[1]))}}}else{var I=h[1],b=n(b);if(1==b[0])b=n(a),b=[2,1+I|0,n(b),c,n(W),n(h)];else{var T=b[1],P=b[2],Z=b[3],e=b[4],m=b[5];if(T>(q(3,I)|0)){var oa=n(e);if(1==oa[0])b=n(Ye);else{var Qa=oa[1],b=n(m);if(1==b[0])b=n(Ye);else{var e=b[1],Eb=b[2],wa=b[3],Ga=b[4],tg=b[5];e<
(q(2,Qa)|0)?(m=n(a),b=[2,(1+I|0)+e|0,n(m),c,n(b),n(h)],b=[2,(1+T|0)+I|0,n(P),Z,n(oa),n(b)]):(b=function(b){var e=n(tg);if(1==e[0])e=n(a),e=[2,1+I|0,n(e),c,n(W),n(h)];else var i=e[1],j=n(a),e=[2,(1+I|0)+i|0,n(j),c,n(e),n(h)];b=[2,(1+Qa|0)+b|0,n(P),Z,n(oa),n(Ga)];return b=[2,(1+T|0)+I|0,n(Eb),wa,n(b),n(e)]},e=n(Ga),b=1==e[0]?b(0):b(e[1]))}}}else e=n(a),b=[2,(1+T|0)+I|0,n(e),c,n(b),n(h)]}}return b}var $e=o(function(){return t("Failure in Data.Map.balanceR")}),af=o(function(){return s($e)});
function bf(a,c,b,e){var h=n(b);if(1==h[0])if(b=n(e),1==b[0])b=n(a),b=[2,1,n(b),c,n(W),n(W)];else{var i=b[1],j=b[2],k=b[3],l=b[5],e=n(b[4]);if(1==e[0])e=n(l),1==e[0]?(e=n(a),b=[2,2,n(e),c,n(W),n(b)]):(b=n(a),b=[2,1,n(b),c,n(W),n(W)],b=[2,3,n(j),k,n(b),n(e)]);else{var b=e[1],m=e[2],r=e[3],v=e[4],w=e[5],B=n(l);if(1==B[0])e=n(a),b=[2,1,n(j),k,n(W),n(W)],e=[2,1,n(e),c,n(W),n(W)],b=[2,3,n(m),r,n(e),n(b)];else{var E=B[1];b<(q(2,E)|0)?(l=n(a),b=[2,1+b|0,n(l),c,n(W),n(e)],b=[2,1+i|0,n(j),k,n(b),n(B)]):(b=
function(b){var e=n(a),h=n(w),h=1==h[0]?[2,1+E|0,n(j),k,n(W),n(B)]:[2,(1+E|0)+h[1]|0,n(j),k,n(h),n(B)],b=[2,1+b|0,n(e),c,n(W),n(v)];return b=[2,1+i|0,n(m),r,n(b),n(h)]},e=n(v),b=1==e[0]?b(0):b(e[1]))}}}else{var J=h[1],e=n(e);if(1==e[0])b=n(a),b=[2,1+J|0,n(b),c,n(h),n(W)];else{var I=e[1],T=e[2],P=e[3],l=e[4],b=e[5];if(I>(q(3,J)|0))if(e=n(l),1==e[0])b=n(af);else{var l=e[1],Z=e[2],oa=e[3],Qa=e[4],Eb=e[5],wa=n(b);if(1==wa[0])b=n(af);else{var Ga=wa[1];l<(q(2,Ga)|0)?(b=n(a),b=[2,(1+J|0)+l|0,n(b),c,n(h),
n(e)],b=[2,(1+J|0)+I|0,n(T),P,n(b),n(wa)]):(b=function(b){var e=n(a),i=n(Eb),i=1==i[0]?[2,1+Ga|0,n(T),P,n(W),n(wa)]:[2,(1+Ga|0)+i[1]|0,n(T),P,n(i),n(wa)],b=[2,(1+J|0)+b|0,n(e),c,n(h),n(Qa)];return b=[2,(1+J|0)+I|0,n(Z),oa,n(b),n(i)]},e=n(Qa),b=1==e[0]?b(0):b(e[1]))}}else b=n(a),b=[2,(1+J|0)+I|0,n(b),c,n(h),n(e)]}}return b}function cf(a,c,b){var e=n(b);if(1==e[0])a=n(a),c=[2,1,n(a),c,n(W),n(W)];else var b=e[2],h=e[3],i=e[4],c=cf(a,c,e[5]),c=bf(b,h,i,c);return c}
function df(a,c,b){var e=n(b);if(1==e[0])a=n(a),c=[2,1,n(a),c,n(W),n(W)];else var b=e[2],h=e[3],i=e[5],c=df(a,c,e[4]),c=Ze(b,h,c,i);return c}function ef(a,c,b,e,h,i,j,k,l){e=n(e);if(1==e[0])h=[2,h,n(i),j,n(k),n(l)],b=df(c,b,h);else{var m=e[1],r=e[2],v=e[3],w=e[4],B=e[5];(q(3,m)|0)<h?(b=ff(a,c,b,m,r,v,w,B,k),b=Ze(i,j,b,l)):(q(3,h)|0)<m?(b=ef(a,c,b,B,h,i,j,k,l),b=bf(r,v,w,b)):(c=n(c),i=[2,h,n(i),j,n(k),n(l)],b=[2,(m+h|0)+1|0,n(c),b,n(e),n(i)])}return b}
function ff(a,c,b,e,h,i,j,k,l){l=n(l);if(1==l[0])e=[2,e,n(h),i,n(j),n(k)],b=cf(c,b,e);else{var m=l[1],r=l[2],v=l[3],w=l[4],B=l[5];(q(3,e)|0)<m?(b=ff(a,c,b,e,h,i,j,k,w),b=Ze(r,v,b,B)):(q(3,m)|0)<e?(b=ef(a,c,b,k,m,r,v,w,B),b=bf(h,i,j,b)):(c=n(c),h=[2,e,n(h),i,n(j),n(k)],b=[2,(e+m|0)+1|0,n(c),b,n(h),n(l)])}return b}
function gf(a,c,b,e,h){e=n(e);if(1==e[0])b=df(c,b,h);else{var i=e[1],j=e[2],k=e[3],l=e[4],m=e[5],h=n(h);if(1==h[0])b=cf(c,b,e);else{var r=h[1],v=h[2],w=h[3],B=h[4],E=h[5];(q(3,i)|0)<r?(b=ff(a,c,b,i,j,k,l,m,B),b=Ze(v,w,b,E)):(q(3,r)|0)<i?(b=ef(a,c,b,m,r,v,w,B,E),b=bf(j,k,l,b)):(a=n(c),b=[2,(i+r|0)+1|0,n(a),b,n(e),n(h)])}}return b}
function hf(a,c,b,e){e=n(e);if(1==e[0])e=[1,[1,a,c],b];else var h=e[2],i=e[3],j=e[4],k=e[5],l=o(function(){return hf(h,i,j,k)}),e=[1,o(function(){var a=n(l)[1];return n(a)}),o(function(){var e=n(l)[2];return Ze(a,c,b,e)})];return e}function jf(a,c,b,e){b=n(b);if(1==b[0])b=[1,[1,a,c],e];else var h=b[2],i=b[3],j=b[4],k=b[5],l=o(function(){return jf(h,i,j,k)}),b=[1,o(function(){var a=n(l)[1];return n(a)}),o(function(){var b=n(l)[2];return bf(a,c,b,e)})];return b}
function kf(a,c){var b=n(a);if(1==b[0])b=n(c);else{var e=b[1],h=b[2],i=b[3],j=b[4],k=b[5],l=n(c);if(1==l[0])b=n(b);else{var m=l[2],r=l[3],v=l[4],w=l[5];e>l[1]?(e=hf(h,i,j,k),b=e[2],e=n(e[1]),b=bf(e[1],e[2],b,l)):(e=jf(m,r,v,w),l=e[2],e=n(e[1]),b=Ze(e[1],e[2],b,l))}}return b}
function lf(a,c,b,e,h,i){a=n(a);if(1==a[0])b=[2,c,n(b),e,n(h),n(i)];else{var j=a[1],k=a[2],l=a[3],m=a[4],r=a[5];(q(3,j)|0)<c?(c=mf(j,k,l,m,r,h),b=Ze(b,e,c,i)):(q(3,c)|0)<j?(b=lf(r,c,b,e,h,i),b=bf(k,l,m,b)):(b=[2,c,n(b),e,n(h),n(i)],b=kf(a,b))}return b}
function mf(a,c,b,e,h,i){i=n(i);if(1==i[0])c=[2,a,n(c),b,n(e),n(h)];else{var j=i[1],k=i[2],l=i[3],m=i[4],r=i[5];(q(3,a)|0)<j?(c=mf(a,c,b,e,h,m),c=Ze(k,l,c,r)):(q(3,j)|0)<a?(a=lf(h,j,k,l,m,r),c=bf(c,b,e,a)):(c=[2,a,n(c),b,n(e),n(h)],c=kf(c,i))}return c}
function nf(a,c,b){var e=n(b);if(1==e[0])a=[1];else{var b=e[2],h=e[3],i=e[4],e=e[5];if(p(c,[b,h]))e=nf(a,c,e),c=nf(a,c,i),a=gf(a,b,h,c,e);else{var j=nf(a,c,e),a=nf(a,c,i),h=n(a);if(1==h[0])a=n(j);else{var i=h[1],a=h[2],c=h[3],b=h[4],e=h[5],k=n(j);if(1==k[0])a=n(h);else{var l=k[1],j=k[2],m=k[3],r=k[4],v=k[5];(q(3,i)|0)<l?(a=mf(i,a,c,b,e,r),a=Ze(j,m,a,v)):(q(3,l)|0)<i?(h=lf(e,l,j,m,r,v),a=bf(a,c,b,h)):a=kf(h,k)}}}}return a}function of(a,c,b){return nf(a,function(a,b){return p(c,[b])},b)}
function pf(a,c){var b=o(function(){return nd(a,c)});return n(function(a,c){function i(i){function j(l){if(i==l)var l=V(c),m=V(a),l=vc(b,m,l);else l=g;return l}var m=n(c);return 1==m[0]?j(0):j(m[1])}var j=n(a);return 1==j[0]?i(0):i(j[1])})}
function qf(a,c){return[1,o(function(){var b=o(function(){return xc(a)}),e=o(function(){return xc(c)});return[1,o(function(){return pf(b,e)}),function(a,c){return p(pf,[b,e,a,c])?g:f}]}),o(function(){var b=o(function(){return wd(a,c)});return n(function(a,c){var i=V(c),j=V(a);return R(b,j,i)})}),function(b,e){var h=V(e),i=V(b);return 1==R(o(function(){return wd(a,c)}),i,h)[0]?f:g},function(b,e){var h=V(e),i=V(b);return 1==R(o(function(){return wd(a,c)}),i,h)[0]?g:f},function(b,e){var h=V(e),i=V(b);
return 3==R(o(function(){return wd(a,c)}),i,h)[0]?f:g},function(b,e){var h=V(e),i=V(b);return 3==R(o(function(){return wd(a,c)}),i,h)[0]?g:f},function(b,e){var h=V(e),i=V(b);return 3==R(o(function(){return wd(a,c)}),i,h)[0]?n(b):n(e)},function(b,e){var h=V(e),i=V(b);return 3==R(o(function(){return wd(a,c)}),i,h)[0]?n(e):n(b)}]}
var rf=[1,[1,function(a,c){return n(a)?n(c):n(c)?g:f},function(a,c){return n(a)?n(c)?g:f:n(c)}],function(a,c){return n(a)?n(c)?[2]:[3]:n(c)?[1]:[2]},function(a,c){if(n(a)){n(c);var b=g}else b=n(c);return b},function(a,c){if(n(a)){n(c);var b=f}else b=n(c)?g:f;return b},function(a,c){if(n(a))var b=n(c)?g:f;else n(c),b=g;return b},function(a,c){if(n(a))var b=n(c);else n(c),b=f;return b},function(a,c){if(n(a)){n(c);var b=f}else b=n(c);return b},function(a,c){if(n(a))var b=n(c);else n(c),b=g;return b}],
sf=o(function(){return p(qf,[Qe,rf])}),tf=o(function(){return p(of,[sf,xe])}),uf=o(function(){return p(H,[We,tf])}),vf=[1];function wf(a,c,b,e){function h(b,c,e){var l=n(b),m=n(e);if(1==m[0])c=[2,1,n(l),c,n(W),n(W)];else{var r=m[1],e=m[2],b=m[3],v=m[4],m=m[5];switch(p(O,[a,l,e])[0]){case 1:var c=h(l,c,v),w=Ze(e,b,c,m);break;case 2:w=[2,r,n(l),c,n(v),n(m)];break;case 3:c=h(l,c,m),w=bf(e,b,v,c)}c=w}return c}return h(c,b,e)}function xf(a,c){var b=n(a);return[2,1,n(b),c,n(W),n(W)]}var yf=[1];
function zf(a,c,b,e){c=n(c);if(1==c[0])if(c=n(b),1==c[0])a=n(e);else a:{for(c=c[1];;){e=n(e);if(1==e[0])a=[1];else if(b=e[4],p(bd,[a,e[2],c])){e=b;continue}else a=n(e);break a}a=d}else if(c=c[1],b=n(b),1==b[0])a:{for(;;){e=n(e);if(1==e[0])a=[1];else if(b=e[5],p(ad,[a,e[2],c])){e=b;continue}else a=n(e);break a}a=d}else a:{for(b=b[1];;){e=n(e);if(1==e[0])a=[1];else{var h=e[2],i=e[4],j=e[5];if(p(ad,[a,h,c])){e=j;continue}else if(p(bd,[a,h,b])){e=i;continue}else a=n(e)}break a}a=d}return a}
function Af(a,c,b,e,h){h=n(h);if(1==h[0])c=n(e);else{var i=h[2],j=h[3],k=h[4],l=h[5],e=n(e);if(1==e[0]){b=n(b);if(1==b[0])b=n(l);else var m=function(b,c){for(;;){var e=n(c);if(1==e[0])var h=[1];else{var h=e[2],i=e[3],j=e[4],e=e[5];switch(p(O,[a,h,b])[0]){case 1:var k=m(b,e),k=gf(a,h,i,j,k);break;case 2:k=n(j);break;case 3:c=j;continue}h=k}return h}},b=m(b[1],l);c=n(c);if(1==c[0])c=n(k);else var r=function(b,c){for(;;){var e=n(c);if(1==e[0])var h=[1];else{var h=e[2],i=e[3],j=e[4],e=e[5];switch(p(O,
[a,b,h])[0]){case 1:var j=r(b,j),k=gf(a,h,i,j,e);break;case 2:k=n(e);break;case 3:c=e;continue}h=k}return h}},c=r(c[1],k)}else var i=e[2],j=e[3],k=e[4],l=e[5],e=[2,n(i)],v=zf(a,e,b,h),b=Af(a,e,b,l,v),h=zf(a,c,e,h),c=Af(a,c,e,k,h);c=gf(a,i,j,c,b)}return c}function Bf(a,c,b){return n(b)}
function Cf(a,c,b){var e=n(c);if(1==e[0])b=n(b);else{var c=e[2],h=e[3],i=e[4],j=e[5],k=n(b);if(1==k[0])b=n(e);else var l=k[2],m=k[3],r=k[4],v=k[5],b=o(function(){var b;if(1==n(r)[0])if(1==n(v)[0]){var c=function(b,e,h,i){var j=n(e),k=n(i);if(1==k[0])e=[2,1,n(j),h,n(W),n(W)];else{var l=k[1],e=k[2],m=k[3],i=k[4],k=k[5];switch(p(O,[a,j,e])[0]){case 1:var i=c(b,j,h,i),r=Ze(e,m,i,k);break;case 2:e=o(function(){return p(b,[j,h,m])});r=[2,l,n(j),e,n(i),n(k)];break;case 3:r=c(b,j,h,k),r=bf(e,m,i,r)}e=r}return e};
b=c(Bf,l,m,e)}else b=Af(a,yf,yf,e,k);else b=Af(a,yf,yf,e,k);return b}),b=1==n(i)[0]?1==n(j)[0]?wf(a,c,h,k):n(b):n(b)}return b}function Df(a){var c=o(function(){return[2,a,c]});return n(c)}function Ef(a,c){var b=n(a);if(b){var e=n(c);if(1==e[0])e=[1];else var h=e[2],e=[2,e[1],o(function(){return Ef(b-1|0,h)})]}else e=[1];return e}function Ff(a,c){var b=n(a)[1];return 0<=b?Ef(b,c):[1]}
function Gf(a){a=n(a);if(1==a[0])a=[1];else var c=a[1],b=a[2],a=function(){var a=n(b);if(1==a[0])var h=function(a){a=n(a);if(1==a[0])a=[1];else var b=a[2],a=[2,[2,a[1],u],o(function(){return h(b)})];return a},i=h(c);else var j=function(b){b=n(b);if(1==b[0])b=[1];else var c=b[1],h=b[2],i=function(a){a=n(a);if(1==a[0])a=j(h);else var b=a[2],a=[2,[2,c,a[1]],o(function(){return i(b)})];return a},b=i(o(function(){return Gf(a)}));return b},i=j(c);return i},a=1==n(c)[0]?1==n(b)[0]?[2,u,u]:a():a();return a}
var Hf=[1,1.605959309876327E19,1.3945565038419476E19,[1,1.605959309876327E19,1.3945565038419476E19,o(function(){return t("base")}),o(function(){return t("Control.Exception.Base")}),o(function(){return t("PatternMatchFail")})],u];function If(){return n(Hf)}function Jf(a){var c=n(a),a=c[2],c=ja(c[1]);return ia(c,If,a)}
var Kf=[1,function(a,c,b){a=n(c)[1];return x(a,b)},function(a){a=n(a)[1];return n(a)},function(a,c){var b=n(a);if(1==b[0])b=da("[]",c);else var e=b[1],h=b[2],b=[2,Sa,o(function(){var a=n(e)[1];return x(a,o(function(){function a(c){c=n(c);if(1==c[0])c=n(b);else var e=c[1],h=c[2],c=[2,Pa,o(function(){var b=n(e)[1];return x(b,o(function(){return a(h)}))})];return c}var b=[2,Ra,c];return a(h)}))})];return b}],Mf=o(function(){return[1,If,Kf,Lf,Jf]});function Lf(a){return[1,Mf,a]}
var Nf=o(function(){return t("Non-exhaustive patterns in")}),Of=[1," "],Pf=[2,[1,"\n"],u];function Qf(a){a=n(a)[1];return"|"==n(a)?g:f}function Rf(a,c){var b=n(c);if(1==b[0])b=[1,u,u];else{var e=b[1],h=b[2];if(p(a,[e]))var i=o(function(){var b=Rf(a,h);return[1,b[1],b[2]]}),b=[1,[2,e,o(function(){var a=n(i)[1];return n(a)})],o(function(){var a=n(i)[2];return n(a)})];else b=[1,u,b]}return b}
function Sf(a,c,b){a:{for(var e;;){var c=n(c),h=n(b);if(1==h[0])a=[1];else{var i=h[3],b=h[4],j=h[5];switch(p(O,[a,c,h[2]])[0]){case 1:continue;case 2:e=[2,i];break;case 3:b=j;continue}a=e}break a}a=d}return a}function Tf(a){a=n(a);return 1==a[0]?n(ha):n(a[1])}var Uf=o(function(){return t("Prelude.undefined")}),Vf=o(function(){return s(Uf)});
function Wf(a){function c(c){var i=n(c);switch(i[0]){case 1:var j=[1];break;case 2:j=[2];break;case 3:var k=i[1],j=p(A,[o(function(){return p(H,[b,Tf])}),o(function(){return p(Sf,[Qe,k,a])})]);break;case 4:switch(n(i[1])[0]){case 1:c=[2];break;case 2:c=[1];break;default:c=p(t,["Logic.eval.reduce: Impossible"]),c=s(c)}j=c;break;case 5:j=p(A,[b,o(function(){var a=o(function(){var a=n(i);switch(a[0]){case 5:a=[1,a[1],a[2]];break;case 6:a=[1,a[1],a[2]];break;case 7:a=[1,a[1],a[2]];break;case 8:a=[1,a[1],
a[2]];break;default:a=n(Vf)}return a});return p(ke,[o(function(){return p(A,[e,o(function(){return p(bc,[a])})])}),o(function(){return p(A,[e,o(function(){return p(fd,[a])})])})])})]);break;case 6:j=p(A,[b,o(function(){var a=o(function(){var a=n(i);switch(a[0]){case 5:a=[1,a[1],a[2]];break;case 6:a=[1,a[1],a[2]];break;case 7:a=[1,a[1],a[2]];break;case 8:a=[1,a[1],a[2]];break;default:a=n(Vf)}return a});return p(Nb,[o(function(){return p(A,[e,o(function(){return p(bc,[a])})])}),o(function(){return p(A,
[e,o(function(){return p(fd,[a])})])})])})]);break;case 7:j=p(A,[o(function(){return p(H,[b,o(function(){return Wf(a)})])}),o(function(){return M(i)})]);break;case 8:j=p(A,[o(function(){return p(H,[b,o(function(){return Wf(a)})])}),o(function(){return M(i)})])}return j}function b(a){return n(a)?[1]:[2]}function e(a){switch(n(a)[0]){case 1:a=f;break;case 2:a=g;break;default:var b=[1,o(function(){function a(b,c){return x(b,o(function(){return da(": ",o(function(){return x(Nf,o(function(){return x(c,
Pf)}))}))}))}var b=t("PropositionalLogic/Logic.hs:(154,11)-(155,26)|function toBool"),c=Rf(Qf,b),b=c[1],e=n(c[2]);1==e[0]?b=a(b,u):(c=e[2],e=n(e[1])[1],b="|"==n(e)?a(b,[2,Of,c]):a(b,u));return b})],c=Lf;throw o(function(){return p(c,[b])});}return a}return p(H,[e,function(a){return K(c,a)}])}
function Xf(a){return p(A,[function(c){return p(A,[o(function(){return p(H,[function(a){a=n(a);return 1==a[0]?[1]:p(A,[o(function(){return p(H,[o(function(){return p(Le,[ze,Ne])}),o(function(){return p(N,[o(function(){return p(Le,[ze,Me])})])})])}),a])},o(function(){return p(H,[o(function(){return p(H,[o(function(){return p(md,[o(function(){return p(H,[jd,ne])})])}),o(function(){return p(N,[o(function(){return p(Ge,[function(a,c){var h=n(a),i=h[1];switch(n(h[2])[0]){case 1:var j=[2,[3,i],c];break;
case 2:j=[2,[4,[3,i]],c];break;case 3:j=n(c)}return j},u])})])})])}),o(function(){return p(N,[o(function(){return p(A,[he,o(function(){return p(A,[Zc,o(function(){return Ue(Re,zc,a)})])})])})])})])})])}),c])},o(function(){return p(N,[bc,o(function(){return p(A,[o(function(){return p(H,[Wd,o(function(){return p(H,[pe,o(function(){return p(H,[ve,uf])})])})])}),o(function(){return p(A,[o(function(){return p(H,[o(function(){return p(Ge,[function(c){return p(wf,[sf,c,o(function(){return p(Wf,[c,a])})])},
vf])}),o(function(){return p(H,[o(function(){return p(N,[o(function(){return p(Ge,[o(function(){return p(Cf,[Qe])}),vf])})])}),function(a){return p(A,[o(function(){return p(N,[o(function(){return p(oe,[xf,a])})])}),o(function(){return p(A,[o(function(){return p(H,[Gf,o(function(){return p(Ff,[o(function(){return p(U,[a])})])})])}),o(function(){return p(Df,[[2,f,[2,g,u]]])})])})])}])})])}),o(function(){return p(A,[Zc,o(function(){return Ue(Re,zc,a)})])})])})])})])})])}
function Yf(a,c){for(;;){var b=n(c);if(1==b[0])b=g;else{var e=b[2];if(p(a,[b[1]]))b=f;else{c=e;continue}}return b}}function Zf(a){for(;;){a=n(a);if(1==a[0])a=g;else{var c=a[2];if(n(a[1]))a=f;else{a=c;continue}}return a}}function $f(a){a:{for(var c=u;;){a=n(a);if(1==a[0]){a=n(c);break a}c=[2,a[1],c];a=a[2]}a=d}return a}function ag(a,c){return p(jd,[o(function(){return p(D,[X,a,c])})])}var bg=o(function(){return p(hd,[Oe])});
function cg(a,c){function b(){switch(n(a)[0]){case 1:switch(n(c)[0]){case 1:var b=f;break;case 2:b=g;break;case 3:b=g;break;case 4:b=g;break;case 5:b=g;break;case 6:b=g;break;case 7:b=g;break;case 8:b=g}var e=b;break;case 2:switch(n(c)[0]){case 1:var h=g;break;case 2:h=f;break;case 3:h=g;break;case 4:h=g;break;case 5:h=g;break;case 6:h=g;break;case 7:h=g;break;case 8:h=g}e=h;break;case 3:switch(n(c)[0]){case 3:b=f;break;case 4:b=g;break;case 5:b=g;break;case 6:b=g;break;case 7:b=g;break;case 8:b=
g;break;default:b=g}e=b;break;case 4:switch(n(c)[0]){case 3:b=g;break;case 4:b=f;break;case 5:b=g;break;case 6:b=g;break;case 7:b=g;break;case 8:b=g;break;default:b=g}e=b;break;case 5:switch(n(c)[0]){case 3:b=g;break;case 4:b=g;break;case 5:b=f;break;case 6:b=g;break;case 7:b=g;break;case 8:b=g;break;default:b=g}e=b;break;case 6:switch(n(c)[0]){case 3:b=g;break;case 4:b=g;break;case 5:b=g;break;case 6:b=f;break;case 7:b=g;break;case 8:b=g;break;default:b=g}e=b;break;case 7:switch(n(c)[0]){case 3:b=
g;break;case 4:b=g;break;case 5:b=g;break;case 6:b=g;break;case 7:b=f;break;case 8:b=g;break;default:b=g}e=b;break;case 8:switch(n(c)[0]){case 3:b=g;break;case 4:b=g;break;case 5:b=g;break;case 6:b=g;break;case 7:b=g;break;case 8:b=f;break;default:b=g}e=b}return e}var e=n(a);switch(e[0]){case 3:var e=e[1],h=n(c),e=3==h[0]?p(D,[bg,e,h[1]]):b();break;case 4:e=e[1];h=n(c);e=4==h[0]?p(D,[X,e,h[1]]):b();break;case 5:var i=e[1],j=e[2],e=n(c);if(5==e[0])var k=e[1],l=e[2],e=p(ke,[o(function(){return p(D,
[X,i,k])}),o(function(){return p(D,[X,j,l])})]);else e=b();break;case 6:var m=e[1],r=e[2],e=n(c);if(6==e[0])var v=e[1],w=e[2],e=p(ke,[o(function(){return p(D,[X,m,v])}),o(function(){return p(D,[X,r,w])})]);else e=b();break;case 7:var B=e[1],E=e[2],e=n(c);if(7==e[0])var J=e[1],I=e[2],e=p(ke,[o(function(){return p(D,[X,B,J])}),o(function(){return p(D,[X,E,I])})]);else e=b();break;case 8:var T=e[1],P=e[2],e=n(c);if(8==e[0])var Z=e[1],oa=e[2],e=p(ke,[o(function(){return p(D,[X,T,Z])}),o(function(){return p(D,
[X,P,oa])})]);else e=b();break;default:e=b()}return e}var X=o(function(){return[1,cg,ag]});
function dg(a,c,b){if(p(Nb,[o(function(){return p(Yf,[function(a){return p(nc,[X,a,b])},a])}),o(function(){return p(Zf,[o(function(){function a(c){c=n(c);if(1==c[0])c=[1];else var e=c[1],k=c[2],l=function(b){b=n(b);if(1==b[0])b=a(k);else var c=b[1],i=b[2],b=[2,o(function(){function a(){var b=n(c);if(4==b[0])b=p(D,[X,e,b[1]]);else var h=n(e),b=4==h[0]?p(D,[X,h[1],b]):g;return b}switch(n(e)[0]){case 1:var b=2==n(c)[0]?f:a();break;case 2:b=1==n(c)[0]?f:a();break;default:b=a()}return b}),o(function(){return l(i)})];
return b},c=l(o(function(){return p($f,[b])}));return c}return a(b)})])})]))var e=[2,o(function(){return p(Vd,[a])}),u];else e=p(ec,[X,o(function(){return p(oc,[X,b])}),c]),e=1==e[0]?[2,o(function(){return p(Vd,[c])}),u]:n(e);return e}function eg(a){a=n(a);if(6==a[0])var c=a[1],b=a[2],a=p(x,[o(function(){return eg(c)}),o(function(){return eg(b)})]);else a=[2,a,u];return a}
var fg=o(function(){var a=[2,Te,[2,[4,Se],u]],c=[2,Se,[2,[4,Te],u]];return p(H,[function(b){return dg(c,a,b)},o(function(){return p(H,[o(function(){return p(N,[o(function(){return p(Le,[ze,Ne])})])}),o(function(){function a(c){var h=n(c);switch(h[0]){case 5:var i=h[1],j=h[2],c=p(x,[o(function(){return a(i)}),o(function(){return a(j)})]);break;case 6:c=[2,o(function(){return eg(h)}),u];break;default:c=[2,[2,h,u],u]}return c}return p(H,[o(function(){var a=[2,Se,[2,[4,Te],u]],b=[2,Te,[2,[4,Se],u]];return p(N,
[function(c){return dg(b,a,c)}])}),a])})])})])}),gg=o(function(){return p(Le,[ze,Me])}),hg=o(function(){return p(H,[gg,fg])});
function ig(a,c,b){if(p(Nb,[o(function(){return p(Yf,[function(a){return p(nc,[X,a,b])},a])}),o(function(){return p(Zf,[o(function(){function a(c){c=n(c);if(1==c[0])c=[1];else var e=c[1],k=c[2],l=function(b){b=n(b);if(1==b[0])b=a(k);else var c=b[1],i=b[2],b=[2,o(function(){function a(){var b=n(c);if(4==b[0])b=p(D,[X,e,b[1]]);else var h=n(e),b=4==h[0]?p(D,[X,h[1],b]):g;return b}switch(n(e)[0]){case 1:var b=2==n(c)[0]?f:a();break;case 2:b=1==n(c)[0]?f:a();break;default:b=a()}return b}),o(function(){return l(i)})];
return b},c=l(o(function(){return p($f,[b])}));return c}return a(b)})])})]))var e=[2,o(function(){return p(Vd,[a])}),u];else e=p(ec,[X,o(function(){return p(oc,[X,b])}),c]),e=1==e[0]?[2,o(function(){return p(Vd,[c])}),u]:n(e);return e}function jg(a){a=n(a);if(5==a[0])var c=a[1],b=a[2],a=p(x,[o(function(){return jg(c)}),o(function(){return jg(b)})]);else a=[2,a,u];return a}
var kg=o(function(){var a=[2,Se,[2,[4,Te],u]],c=[2,Te,[2,[4,Se],u]];return p(H,[function(b){return ig(c,a,b)},o(function(){return p(H,[o(function(){return p(N,[o(function(){return p(Le,[ze,Me])})])}),o(function(){function a(c){var h=n(c);switch(h[0]){case 5:c=[2,o(function(){return jg(h)}),u];break;case 6:var i=h[1],j=h[2],c=p(x,[o(function(){return a(i)}),o(function(){return a(j)})]);break;default:c=[2,[2,h,u],u]}return c}return p(H,[o(function(){var a=[2,Te,[2,[4,Se],u]],b=[2,Se,[2,[4,Te],u]];return p(N,
[function(c){return ig(b,a,c)}])}),a])})])})])}),lg=o(function(){return p(Le,[ze,Ne])}),mg=o(function(){return p(H,[lg,kg])});function ng(a){a=n(a)[3];return n(a)}function og(a){a=n(a)[4];return n(a)}function pg(a,c){return p(jd,[o(function(){return p(D,[qg,a,c])})])}function rg(a){a=n(a);return a instanceof Array?a[0]-1:a-1}function sg(a,c){var b=p(rg,[a]),e=p(rg,[c]);return b==e}var qg=o(function(){return[1,sg,pg]});function ug(a,c,b){return p(F,[a,c,function(){return n(b)}])}
var vg=o(function(){return p(ug,[Y])});function wg(a,c){return p(A,[function(a){return n(a)},function(b){b=p(a,[b]);1==b[0]?b=[1,b[1]]:(b=n(b[1]),b=p(c,[b[2],b[1]]));return b}])}function xg(a,c){return[1,[1,a,c]]}var yg=o(function(){return p(H,[function(a){return n(a)},o(function(){return p(Xd,[xg])})])});function zg(a,c){return[2,[1,a,c]]}var Ag=o(function(){return p(H,[function(a){return n(a)},o(function(){return p(Xd,[zg])})])}),Y=o(function(){return[1,wg,vg,Ag,yg]}),Bg=[3];
function Cg(a){a=n(a);return 1==a[0]?[2,[1,u,Za]]:[1,[1,a,o(function(){return p(t,["eof"])})]]}function Dg(a,c){return p(A,[function(a){return n(a)},function(b){var e=p(a,[b]);return 1==e[0]?p(c,[b]):n(e)}])}var Eg=o(function(){return p(Ke,[Dg])});function Fg(a){return[3,a]}function Gg(a){a=n(a)[3];return n(a)}var Hg=o(function(){return p(H,[o(function(){return z(Y)}),o(function(){return p(H,[Fg,Gg])})])}),Ig=[6];
function Jg(a,c){function b(){return[1,[1,c,o(function(){return p(t,["not satisfied"])})]]}var e=n(c);if(1==e[0])var h=b();else h=e[1],e=e[2],h=p(a,[h])?[2,[1,e,h]]:b();return h}function Kg(a){a=n(a)[1];return n(a)}function Lg(a){return p(A,[Jg,o(function(){return p(H,[o(function(){return p(D,[qg,a])}),Kg])})])}
var Mg=o(function(){return Lg(Ig)}),Ng=o(function(){return p(F,[Y,Mg,Hg])}),Og=o(function(){return p(z,[Y,Se])}),Pg=[2],Qg=o(function(){return Lg(Pg)}),Rg=o(function(){return p(y,[Y,Qg,Og])}),Sg=o(function(){return p(z,[Y,Te])}),Tg=[1],Ug=o(function(){return Lg(Tg)}),Vg=o(function(){return p(y,[Y,Ug,Sg])}),Wg=[2,Vg,[2,Rg,[2,Ng,u]]],Xg=o(function(){return p(H,[o(function(){return z(Y)}),Pb])}),Yg=[7],Zg=[4],$g=[5],bh=o(function(){return p(A,[Eg,o(function(){return p(N,[function(a){return p(y,[Y,o(function(){return Lg(Zg)}),
o(function(){return p(F,[Y,a,function(a){return p(y,[Y,o(function(){return Lg($g)}),o(function(){return p(z,[Y,a])})])}])})])},ah])})])}),ch=o(function(){return[2,bh,u]}),eh=o(function(){return[2,dh,ch]}),fh=o(function(){return[2,Ng,eh]}),gh=o(function(){return[2,Rg,fh]}),hh=o(function(){return[2,Vg,gh]}),ih=o(function(){return p(Eg,[hh])}),jh=o(function(){return p(y,[Y,o(function(){return Lg(Yg)}),ih])}),dh=o(function(){return p(F,[Y,jh,Xg])}),kh=o(function(){return[2,dh,Wg]}),lh=[8],mh=[9],nh=[2,
o(function(){return p(y,[Y,o(function(){return Lg(lh)}),o(function(){return p(z,[Y,Me])})])}),[2,o(function(){return p(y,[Y,o(function(){return Lg(mh)}),o(function(){return p(z,[Y,Ne])})])}),u]];function oh(a){return p(F,[Y,o(function(){return p(Eg,[nh])}),function(c){return p(F,[Y,o(function(){return p(A,[function(a){return n(a)},function(a){var c=p(ph,[a]);return 1==c[0]?p(ih,[a]):n(c)}])}),function(b){return p(A,[o(function(){return z(Y)}),o(function(){return p(c,[a,b])})])}])}])}
var ph=o(function(){return p(F,[Y,ih,oh])});function qh(a,c){return[7,a,c]}var rh=[10];function sh(a,c){return[8,a,c]}var th=[11],uh=[2,o(function(){return p(y,[Y,o(function(){return Lg(rh)}),o(function(){return p(z,[Y,qh])})])}),[2,o(function(){return p(y,[Y,o(function(){return Lg(th)}),o(function(){return p(z,[Y,sh])})])}),u]];
function vh(a){return p(F,[Y,o(function(){return p(Eg,[uh])}),function(c){return p(F,[Y,o(function(){var a=o(function(){return p(A,[function(a){return n(a)},function(a){var b=p(wh,[a]);return 1==b[0]?p(ph,[a]):n(b)}])});return p(A,[function(a){return n(a)},function(c){var h=p(a,[c]);return 1==h[0]?p(ih,[c]):n(h)}])}),function(b){return p(A,[o(function(){return z(Y)}),o(function(){return p(c,[a,b])})])}])}])}
var xh=o(function(){return p(A,[function(a){return n(a)},function(a){var c=p(ph,[a]);return 1==c[0]?p(ih,[a]):n(c)}])}),wh=o(function(){return p(F,[Y,xh,vh])});function yh(a){var c=p(wh,[a]);return 1==c[0]?p(ph,[a]):n(c)}function zh(a){return n(a)}var Ah=o(function(){return p(A,[zh,yh])});function Bh(a){var c=p(Ah,[a]);return 1==c[0]?p(ih,[a]):n(c)}function Ch(a){return n(a)}
var Dh=o(function(){return p(A,[Ch,Bh])}),ah=o(function(){return[2,Dh,kh]}),Eh=o(function(){return p(H,[o(function(){return p(A,[Eg,o(function(){return p(N,[function(a){return p(F,[Y,a,function(a){return p(y,[Y,Cg,o(function(){return p(z,[Y,a])})])}])},ah])})])}),o(function(){return p(md,[o(function(){return p(H,[o(function(){return p(le,[qg,Bg])}),Kg])})])})])});function Fh(a){return n(a)}var Gh=o(function(){return p(A,[Fh,Eh])}),Hh=[1,0];
function Ih(a,c){var b=n(c);if(1==b[0])b=[1];else var e=b[2],b=n(b[1]),h=b[3],b=[2,[1,b[1],a,h],o(function(){return Ih(o(function(){return p(rc,[db,a,o(function(){return p(U,[h])})])}),e)})];return b}function Jh(a){return p(y,[Y,Cg,o(function(){return p(A,[o(function(){return z(Y)}),o(function(){return Ih(Hh,a)})])})])}function Kh(a,c,b){return p(F,[a,b,function(b){return p(z,[a,o(function(){return p(c,[b])})])}])}
function Lh(a,c,b,e){var a=n(a),h=a[1],i=a[3];return p(h,[b,function(a){return p(h,[e,function(b){return p(i,[o(function(){return p(c,[a,b])})])}])}])}
var Mh=[1,function(a,c){function b(a){for(;;){var h=n(a);if(1==h[0])a=[1];else if(a=h[2],h=p(c,[h[1]]),1==h[0])continue;else a=[2,h[1],function(a,b,c){return o(function(){return x(c,o(function(){return b(a)}))})}(a,b,h[2])];return a}}return b(a)},function(a,c){function b(a){a=n(a);if(1==a[0])a=[1];else var h=a[2],a=x(c,o(function(){return b(h)}));return a}return b(a)},function(a){return[2,a,u]},function(){return[1]}];function Nh(a,c){return[2,a,c]}
function Oh(a){a=n(a)[1].charCodeAt(0);return n(65<=a&&90>=a||97<=a&&122>=a||229==a||228==a||246==a||197==a||196==a||214==a)?f:g}function Ph(a){a=n(a)[1];a=n(a);switch(a){case "\t":a=f;break;case "\n":a=f;break;case "\v":a=f;break;case "\f":a=f;break;case "\r":a=f;break;case " ":a=f;break;case "p":a=f;break;default:a=n(9==a.charCodeAt(0)||10==a.charCodeAt(0)||13==a.charCodeAt(0)||32==a.charCodeAt(0))?f:g}return a}var Qh=[12];
function Rh(a){return p(Lh,[Y,Nh,a,o(function(){var c=o(function(){return Rh(a)}),b=o(function(){return p(z,[Y,u])});return p(A,[function(a){return n(a)},function(a){var h=p(c,[a]);return 1==h[0]?p(b,[a]):n(h)}])})])}function Sh(a,c,b){b=n(b);return 1==b[0]?p(a,[b[1]]):p(c,[b[1]])}
function Th(a){return p(A,[function(a){return n(a)},function(c){return p(Sh,[o(function(){return p(H,[function(a){return[1,[1,c,a]]},fd])}),o(function(){return p(H,[function(a){return[2,[1,c,a]]},fd])}),o(function(){return p(a,[c])})])}])}
function Uh(a){return p(y,[Y,o(function(){return p(A,[Th,o(function(){var a=o(function(){var a=o(function(){return p(H,[jd,Oh])});return p(y,[Y,function(c){return Jg(a,c)},o(function(){return p(z,[Y,Za])})])});return p(A,[function(a){return n(a)},function(b){var e=p(a,[b]);return 1==e[0]?Cg(b):n(e)}])})])}),o(function(){return p(A,[o(function(){return z(Y)}),[2,a,u]])})])}
function Vh(a){function c(){return[1,[1,a,o(function(){return p(t,["not satisfied"])})]]}var b=n(a);if(1==b[0])b=c();else var e=b[1],b=b[2],b=p(ke,[o(function(){return p(Oh,[e])}),o(function(){return p(le,[Oe,e,[1,"v"]])})])?[2,[1,b,e]]:c();return b}var Wh=o(function(){return p(F,[Y,Vh,Uh])});function Xh(a,c,b){for(;;){var e=n(c);if(1==e[0])a=f;else{var c=e[1],e=e[2],h=n(b);if(1==h[0])a=g;else if(b=h[2],p(D,[a,c,h[1]])){c=e;continue}else a=g}return a}}
function Yh(a,c){return p(a,[o(function(){var a=n(c)[1];return n(a)}),o(function(){var a=n(c)[2];return n(a)})])}function Zh(a,c){var b=n(a);if(b){var e=n(c);if(1==e[0])e=[1,u,u];else var h=e[2],i=o(function(){var a=Zh(b-1|0,h);return[1,a[1],a[2]]}),e=[1,[2,e[1],o(function(){var a=n(i)[1];return n(a)})],o(function(){var a=n(i)[2];return n(a)})]}else e=[1,u,c];return e}function $h(a,c){var b=n(a)[1];0>b?b=[1,u,c]:(b=Zh(b,c),b=[1,b[1],b[2]]);return b}
function ai(a){a=n(a)[1];a=String.fromCharCode(a.charCodeAt(0)).toLowerCase().charCodeAt(0);if(1114111>=a>>>0)a=[1,String.fromCharCode(a)];else var c=n([1,a])[1],a=da("Prelude.chr: bad argument: ",o(function(){return Db(9,c,u)})),a=s(a);return a}
function bi(a){function c(a){a=n(a);return[1,a[2],a[1]]}var b=o(function(){return p(ie,[o(function(){return p(Xh,[Oe])}),o(function(){return p(N,[ai])})])});return p(A,[function(a){return n(a)},function(e){return p(b,[a,e])?p(A,[o(function(){return p(Yh,[zg])}),o(function(){return p(A,[c,o(function(){return p($h,[o(function(){return p(U,[a])}),e])})])})]):[1,[1,e,a]]}])}function $(a,c){return p(F,[Y,c,function(b){return p(A,[o(function(){return z(Y)}),[1,a,[1,0],b]])}])}
var ci=o(function(){return p(A,[Rh,o(function(){return p(Eg,[[2,o(function(){return p(A,[function(a){return $(Bg,a)},o(function(){return Rh(function(a){return Jg(Ph,a)})})])}),[2,o(function(){return p(A,[function(a){return $(Tg,a)},o(function(){return bi([2,[1,"1"],u])})])}),[2,o(function(){return p(A,[function(a){return $(Pg,a)},o(function(){return bi([2,[1,"0"],u])})])}),[2,o(function(){return p(A,[function(a){return $(Ig,a)},o(function(){function a(a){return Jg(Oh,a)}return p(Lh,[Y,Nh,a,o(function(){return Rh(a)})])})])}),
[2,o(function(){return p(A,[function(a){return $(Ig,a)},Wh])}),[2,o(function(){return p(A,[function(a){return $(Zg,a)},o(function(){return bi([2,[1,"("],u])})])}),[2,o(function(){return p(A,[function(a){return $($g,a)},o(function(){return bi([2,[1,")"],u])})])}),[2,o(function(){return p(A,[function(a){return $(Yg,a)},o(function(){var a=o(function(){return p(t,["!\u00ac"])});return p(A,[o(function(){return p(Kh,[Y,o(function(){return z(Mh)})])}),function(c){return Jg(function(b){return p(nc,[Oe,b,
a])},c)}])})])}),[2,o(function(){return p(A,[function(a){return $(lh,a)},o(function(){var a=o(function(){return p(t,["^\u2227"])});return p(A,[o(function(){return p(Kh,[Y,o(function(){return z(Mh)})])}),function(c){return Jg(function(b){return p(nc,[Oe,b,a])},c)}])})])}),[2,o(function(){return p(A,[function(a){return $(mh,a)},o(function(){var a=o(function(){return p(t,["v\u2228"])});return p(A,[o(function(){return p(Kh,[Y,o(function(){return z(Mh)})])}),function(c){return Jg(function(b){return p(nc,
[Oe,b,a])},c)}])})])}),[2,o(function(){return p(A,[function(a){return $(th,a)},o(function(){return bi(o(function(){return p(t,["<->"])}))})])}),[2,o(function(){return p(A,[function(a){return $(rh,a)},o(function(){return bi(o(function(){return p(t,["->"])}))})])}),[2,o(function(){return p(A,[function(a){return $(Qh,a)},o(function(){var a=o(function(){return p(Kb,[f])});return p(Kh,[Y,o(function(){return z(Mh)}),function(c){return Jg(a,c)}])})])}),u]]]]]]]]]]]]]])})])}),di=o(function(){return p(F,[Y,
ci,Jh])});
function ei(a){var c=p(di,[a]);if(1==c[0])var c=n(c[1]),b=c[1],e=c[2],c=[1,[1,o(function(){return p(ng,[db,o(function(){return p(U,[a])}),o(function(){return p(U,[b])})])}),o(function(){return p(x,[o(function(){return p(t,["tokenizer: "])}),e])})]];else{var c=n(c[1]),h=c[2],i=n(c[1]);if(1==i[0])if(c=p(Gh,[h]),1==c[0])if(h=n(c[1]),c=h[2],h=n(h[1]),1==h[0])c=[1,[1,o(function(){return p(og,[db,[1,1]])}),c]];else var j=h[1],c=[1,[1,o(function(){var a=n(j)[2];return n(a)}),c]];else if(h=n(c[1]),c=h[2],
h=n(h[1]),1==h[0])c=[2,c];else var k=h[1],c=[1,[1,o(function(){var a=n(k)[2];return n(a)}),o(function(){return p(t,["parser: input not exhausted"])})]];else c=[1,[1,o(function(){return p(ng,[db,o(function(){return p(U,[a])}),o(function(){return p(U,[i])})])}),o(function(){return p(t,["tokenizer: input not exhausted"])})]]}return c}
function fi(){return p(F,[Ya,o(function(){return p(A,[o(function(){return p(xb,[o(function(){return p(t,["formulaInput"])})])}),function(a){return p(Ib,[a,o(function(){return p(t,["value"])})])}])}),function(a){a=p(ei,[a]);if(1==a[0])var a=n(a[1]),c=a[1],b=a[2],a=p(A,[Hb,o(function(){return p(x,[o(function(){return p(t,["error at character "])}),o(function(){return p(x,[o(function(){return p(Gb,[Fb,c])}),o(function(){return p(x,[o(function(){return p(t,[": "])}),b])})])})])})]);else var e=a[1],h=
o(function(){return p(Xf,[e])}),i=o(function(){return p(Zb,[o(function(){return p(ac,[e])})])}),j=o(function(){return p(Tb,[i])}),k=o(function(){return p(hg,[j])}),l=o(function(){return p(Wb,[i])}),m=o(function(){return p(mg,[l])}),a=p(y,[Ya,o(function(){return p(A,[o(function(){return p(xb,[o(function(){return p(t,["cnfCode"])})])}),function(a){return p(A,[o(function(){return p(Jb,[a,o(function(){return p(t,["innerHTML"])})])}),o(function(){return p(G,[j])})])}])}),o(function(){return p(y,[Ya,o(function(){return p(A,
[o(function(){return p(xb,[o(function(){return p(t,["scnfCode"])})])}),function(a){return p(A,[o(function(){return p(Jb,[a,o(function(){return p(t,["innerHTML"])})])}),o(function(){return p(G,[k])})])}])}),o(function(){return p(y,[Ya,o(function(){return p(A,[o(function(){return p(xb,[o(function(){return p(t,["dnfCode"])})])}),function(a){return p(A,[o(function(){return p(Jb,[a,o(function(){return p(t,["innerHTML"])})])}),o(function(){return p(G,[l])})])}])}),o(function(){return p(y,[Ya,o(function(){return p(A,
[o(function(){return p(xb,[o(function(){return p(t,["sdnfCode"])})])}),function(a){return p(A,[o(function(){return p(Jb,[a,o(function(){return p(t,["innerHTML"])})])}),o(function(){return p(G,[m])})])}])}),o(function(){return p(y,[Ya,o(function(){return p(A,[o(function(){return p(xb,[o(function(){return p(t,["nnfCode"])})])}),function(a){return p(A,[o(function(){return p(Jb,[a,o(function(){return p(t,["innerHTML"])})])}),o(function(){return p(G,[i])})])}])}),o(function(){return p(A,[o(function(){return p(xb,
[o(function(){return p(t,["simplifiedCode"])})])}),function(a){return p(A,[o(function(){return p(Jb,[a,o(function(){return p(t,["innerHTML"])})])}),o(function(){return p(G,[h])})])}])})])})])})])})])})]);return a}])}
var gi=o(function(){return p(A,[o(function(){return p(xb,[o(function(){return p(t,["formulaInput"])})])}),function(a){return p(vb,[a,fb,function(a){return p($a,[Ya,o(function(){return p(D,[C,a,o(function(){return p(eb,[db,ba(13)])})])}),o(function(){return fi()})])}])}])}),hi=[9,d],ii=o(function(){return p(A,[o(function(){return p(xb,[o(function(){return p(t,["analyzeButton"])})])}),function(a){return p(vb,[a,hi,fi])}])}),ji=o(function(){return p(y,[Ya,ii,gi])});window.onload=function(){n(n(ji)(0))};
